! * SNOW PARAMETERS
!     ------------------------------------------------------------------
NAMELIST/NAMPARSNOW/&
! * snow related (new parameterization) constants
& RLWCSWEA, RLWCSWEB, RLWCSWEC, RTEMPAMP, RHOMINSNA, RHOMINSNB, &
& RHOMINSNC, RHOMINSND, RSNDTOVERA, RSNDTOVERB, RSNDTOVERC, &
& RSNDTDESTA, RSNDTDESTB, RSNDTDESTC, RSNDTDESTROI, RSNDAMOB, RSNDMOB, &
& RSNDAW, RSNDBW, RSNDKV, RSNDATAUW, RSNDBTAUW, RSNDWCOMPMAX, SSAG2, &
& SSASNEXTMIN, SSASNEXTMAX, SNHCONDAV, SNHCONDBV, SNHCONDCV, &
& SNHCONDPOV, RHOMAXSN_NEW, SSASNEXTCNST, SSAG1, &
& SSAG3, SSAGSNSMAX, RSNLARGE, RSNLARGESN, RSNLARGEWT, RSNSNOW, &
& RSNSNOWHVEG, RSNRTTEMP, RSNPERT, RSNGLC, RSMINZ, FSNTCONDA, &
& FSNTCONDB, FSNTCONDC, RLICE, RQSNCRINV, RDARSICE, RDANSICE, RRCSICE, &
& RCONDSICE, RSNPER, RHOMINSN, RTAUF, RTAUA, RALAMSN, RDSNMAX, &
& RHODELTASN, RSFRESH, RALFMINSN, RALFMAXSN
!     ------------------------------------------------------------------

