! * AGS PARAMETERS
!     ------------------------------------------------------------------
NAMELIST/NAMPARAGS/&
! * ags related constants
& RAW, RASW, RBW, RDMAXN, RDMAXX, RPARCF, RPCCO2, RIAOPT, &
& RDSPOPT, RXGT, RDIFRACF, RSHP1AMMAX, RSHP2AMMAX, RSHP1GMES, RSHP2GMES, &
& RMAXFZERO, RCC_NIT_BASE_DIL, RLAIB_NITROA, RLAIB_NITROB, RLAIB_NITROMIN, &
& RVGMES_FLDEXP, RESPBSTR_COEF, REPS_COEF, RGSC_COEF, RXBOMEGA, RRDCF, &
& RCONDCTMIN, RCONDSTMIN, RANFMINIT, RRESPFACTOR_NIT, RCNS_NIT, RCA_1X_CO2_NIT, &
& RCA_2X_CO2_NIT, RCC_NIT, RCO2FRAC
!     ------------------------------------------------------------------
