MODULE SUSDP_DFLT_CTL_MOD
CONTAINS
SUBROUTINE SUSDP_DFLT_CTL(PTVL, PTVH, PSLT, PSSDP2, YDVEG)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_VEG , ONLY : TVEG
USE YOMSURF_SSDP_MOD

IMPLICIT NONE

REAL(KIND=JPRB), INTENT(IN)  :: PTVL(:)
REAL(KIND=JPRB), INTENT(IN)  :: PTVH(:)
REAL(KIND=JPRB), INTENT(IN)  :: PSLT(:)
REAL(KIND=JPRB), INTENT(OUT) :: PSSDP2(:,:)
TYPE(TVEG),      INTENT(IN)  :: YDVEG

INTEGER(KIND=JPIM) :: JL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUSDP_DFLT_CTL_MOD:SUSDP_DFLT_CTL',0,ZHOOK_HANDLE)
ASSOCIATE(RVCOVH2D=>PSSDP2(:,SSDP2D_ID%NRVCOVH2D), RVCOVL2D=>PSSDP2(:,SSDP2D_ID%NRVCOVL2D), &
       &  RVLAMSKH2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKH2D), RVLAMSKL2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKL2D), &
       &  RVLAMSKSH2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKSH2D), RVLAMSKSL2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKSL2D), &
       &  RVRSMINH2D=>PSSDP2(:,SSDP2D_ID%NRVRSMINH2D), RVRSMINL2D=>PSSDP2(:,SSDP2D_ID%NRVRSMINL2D), & 
       &  RVZ0MH2D=>PSSDP2(:,SSDP2D_ID%NRVZ0MH2D), RVZ0ML2D=>PSSDP2(:,SSDP2D_ID%NRVZ0ML2D), &
       &  RVZ0HH2D=>PSSDP2(:,SSDP2D_ID%NRVZ0HH2D), RVZ0HL2D=>PSSDP2(:,SSDP2D_ID%NRVZ0HL2D), &
       &  RVRSMINB2D=>PSSDP2(:,SSDP2D_ID%NRVRSMINB2D))


RVCOVH2D(:) = YDVEG%RVCOV(PTVH(:))
RVCOVL2D(:) = YDVEG%RVCOV(PTVL(:))
RVLAMSKH2D(:) = YDVEG%RVLAMSK(PTVH(:))
RVLAMSKL2D(:) = YDVEG%RVLAMSK(PTVL(:))
RVLAMSKSH2D(:) = YDVEG%RVLAMSKS(PTVH(:))
RVLAMSKSL2D(:) = YDVEG%RVLAMSKS(PTVL(:))
RVRSMINH2D(:) = YDVEG%RVRSMIN(PTVH(:))
RVRSMINL2D(:) = YDVEG%RVRSMIN(PTVL(:))
RVZ0MH2D(:) = YDVEG%RVZ0M(PTVH(:))
RVZ0ML2D(:) = YDVEG%RVZ0M(PTVL(:))
RVZ0HH2D(:) = YDVEG%RVZ0H(PTVH(:))
RVZ0HL2D(:) = YDVEG%RVZ0H(PTVL(:))
RVRSMINB2D(:) = 50.0_JPRB

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUSDP_DFLT_CTL_MOD:SUSDP_DFLT_CTL',1,ZHOOK_HANDLE)
END SUBROUTINE SUSDP_DFLT_CTL
END MODULE SUSDP_DFLT_CTL_MOD
