#!/usr/bin/env bash
# (C) Copyright 2024- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.


# Forcing type: insitu or era5 or 2D
FORCING_TYPE=2D
SITE=EU-001_20220101-20220102

# Turn on validation
VALIDATE=true

FORCING_DIR=tests/2.0/${FORCING_TYPE}_${SITE}
INICLM_DIR=tests/2.0/${FORCING_TYPE}_${SITE}
