MODULE BUFFER_UTILS
    USE YOMDIM1S, ONLY : NPROMA
    USE PARKIND1, ONLY : JPIM, JPRB
    USE YOMDPHY, ONLY : NPOI
CONTAINS
  SUBROUTINE UNPACK_BUFFER(ARR, RECV_BUF)
    IMPLICIT NONE

    REAL(KIND=JPRB), INTENT(INOUT) :: ARR(:,:)
    REAL(KIND=JPRB), INTENT(IN) :: RECV_BUF(:)

    INTEGER(KIND=JPIM) :: IST,IEND,IBL,IPROMA

    !$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA) SHARED(ARR,RECV_BUF)
    DO IST = 1, NPOI, NPROMA
      IEND = MIN(IST+NPROMA-1,NPOI)
      IBL = (IST-1)/NPROMA + 1
      IPROMA = IEND-IST+1

      ARR(1:IPROMA,IBL) = RECV_BUF(IST:IEND)
    ENDDO
    !$OMP END PARALLEL DO
  END SUBROUTINE UNPACK_BUFFER

  SUBROUTINE PACK_BUFFER(ARR, SEND_BUF)
    IMPLICIT NONE

    REAL(KIND=JPRB), INTENT(IN) :: ARR(:,:)
    REAL(KIND=JPRB), INTENT(INOUT) :: SEND_BUF(:)

    INTEGER(KIND=JPIM) :: IST,IEND,IBL,IPROMA

    !$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA) SHARED(SEND_BUF,ARR)
    DO IST = 1, NPOI, NPROMA
      IEND = MIN(IST+NPROMA-1,NPOI)
      IBL = (IST-1)/NPROMA + 1
      IPROMA = IEND-IST+1

      SEND_BUF(IST:IEND) = ARR(1:IPROMA,IBL)
    ENDDO
    !$OMP END PARALLEL DO
  END SUBROUTINE PACK_BUFFER
END MODULE BUFFER_UTILS
