SUBROUTINE CPG1S

USE YOMDPHY  ,  ONLY : NCSS     ,NLEV     ,NGPP     ,NPOI     ,NTILES   ,&
     &                 NTRAC   ,NVHILO    ,NCOM     ,YDSURF   ,NCSNEC   ,&
     &                 NBLOCKS
USE YOMCDH1S  , ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVVEGS,NDHFVEGS
 
USE YOMDYN1S , ONLY : NSTEP    ,TDT,TSTEP
USE YOMGPD1S , ONLY : VFZ0F    ,VFALBF   ,&
     &            VFALUVP  ,VFALUVD  ,VFALNIP  ,VFALNID  , &
     &            VFALUVI  ,VFALUVV  ,VFALUVG  , &
     &            VFALNII  ,VFALNIV  ,VFALNIG  , &
     &            VFITM    , &
     &            VFZ0H    ,VFCVL    ,VFCVH    ,VFCUR    ,VFTVL    ,VFTVH    , &
     &            VFLAIL   ,VFLAIH   ,VFFWET   ,VFRSML   ,VFRSMH   , &
     &            VFSOTY   ,VFCI     ,VFSST    ,VFSDOR   , &
     &            VFCO2TYP, &
     &            VDALB    ,VDZ0F    ,VDZ0H    , &
     &            VDIEWSSTL,VDINSSSTL,VDISSHFTL,VDIETL   ,VDTSKTL,&
     &            VFLDEPTH,VFCLAKEF   ,& ! FLAKE
     &            VFZO     ,VFHO     ,VFHO_INV ,VFDO     ,VFOCDEPTH, & !KPP 
     &            VFADVT ,VFADVS  ,VFTRI0   ,VFTRI1   ,VFSWDK_SAVE,&  !KPP
     &            VDANDAYVT,VDANFMVT , &
     &            VDRESPBSTR,VDRESPBSTR2,VDBIOMASS_LAST,&
     &            VDBLOSSVT,VDBGAINVT

USE YOMGF1S  , ONLY : UNLEV0   ,VNLEV0   ,TNLEV0   ,QNLEV0   , CNLEV0  ,&
     &            PNLP0    ,UNLEV1   ,VNLEV1   ,TNLEV1   ,QNLEV1   , PNLP1, &
     &            CNLEV1   ,FSSRD    ,FSTRD    ,FLSRF    ,FCRF     , &
     &            FLSSF    , &
     &            FCSF     ,RALT
USE YOMGP1S0 , ONLY : GP0      ,TSLNU0   ,QLINU0   ,FSNNU0   , &
     &            TSNNU0   ,ASNNU0   ,RSNNU0   , WSNNU0,&
     &            TRENU0   ,WRENU0   ,TILNU0,&
     &            TLICENU0,TLMNWNU0,TLWMLNU0,TLBOTNU0,TLSFNU0,& ! FLAKE
     &            HLICENU0,HLMLNU0 ,&                           ! FLAKE
     &            UONU0    ,VONU0    ,TONU0    ,SONU0,&         ! KPP
!     &            UONUC    ,VONUC    ,USTRCNU  ,VSTRNUC,&       ! KPP
     &            LAINU0, BSTRNU0, BSTR2NU0
USE YOMGP1S1 , ONLY : GP1
USE PTRGP1S  , ONLY : MTSLNU   ,MQLINU   ,MFSNNU   , &
     &            MTSNNU   ,MASNNU   ,MRSNNU   , &
     &            MTRENU   ,MWRENU   ,MTILNU, & 
     &            MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &            MHLICENU,MHLMLNU,&                            ! FLAKE 
     &            MUONU    ,MVONU    ,MTONU    ,MSONU,&           !KPP
     &            MLAINU , MBSTRNU, MBSTR2NU,MWSNNU
USE YOMLOG1S,   ONLY: IDBGS1

USE YOMGC1S  , ONLY : GEMU     ,GELAM    ,GELAT
USE YOMCT01S , ONLY : NSTART
USE YOMCST   , ONLY : RG
USE YOERIP   , ONLY : RCODECM  ,RSIDECM  ,RCOVSRM  ,RSIVSRM
USE YOMDIM1S , ONLY : NPROMA

! USE YOS_OCEAN_ML, ONLY : LEOCML
! USE YOS_CST , ONLY : RTT

USE YOMRIP   , ONLY :  RCODEC  ,RSIDEC  ,RCOVSR  ,RSIVSR
USE YOEPHY   , ONLY :  RLAIINT

USE YOMGDI1S , ONLY : GDI1S    ,N2DDI ,&
                      &GDIAUX1S ,N2DDIAUX

USE YOS_SURF, ONLY : TSURF, GET_SURF
USE YOMLUN1S, ONLY : NULOUT
USE OMP_LIB
USE MPL_MODULE

#ifdef DOC
! (C) Copyright 1995- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *CPG1S* - Grid point calculations.

!     Purpose.
!     --------
!           Grid point calculations .

!**   Interface.
!     ----------
!        *CALL* *CPG1S*

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Called by STEPO1S.

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the one column model

!     Author.
!     -------
!        Pedro Viterbo   *ECMWF*

!     Modifications.
!     --------------
!        Original : 95-03-21
!        Bart vd Hurk (KNMI): multi-column setup
!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on:
!        Marita Voogt (KNMI) "C-Tessel" 09/2005
!        Sebastien Lafont (ECMWF) "C-TESSEL"

!     ------------------------------------------------------------------
#endif
USE PARKIND1  ,ONLY : JPIM     ,JPRB,    JPRD
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK
IMPLICIT NONE


CHARACTER*1 :: CDCONF 
REAL(KIND=JPRB) ::  ZAPRS(NPROMA,0:NLEV,NBLOCKS),ZAPHIF(NPROMA,NLEV,NBLOCKS)
REAL(KIND=JPRB) ::  ZDIFTQ(NPROMA,0:NLEV,NBLOCKS),ZDIFTS(NPROMA,0:NLEV,NBLOCKS)
REAL(KIND=JPRB) ::  ZFRSO(NPROMA,0:NLEV,NBLOCKS),ZFRTH(NPROMA,0:NLEV,NBLOCKS)
REAL(KIND=JPRB) ::  ZSTRTU(NPROMA,0:NLEV,NBLOCKS),ZSTRTV(NPROMA,0:NLEV,NBLOCKS)

REAL(KIND=JPRB), DIMENSION(NPROMA,NBLOCKS) ::  ZAN,ZAG,ZRD &
     &   , ZRSOIL_STR,ZRECO,ZCO2FLUX,ZCH4FLUX
REAL(KIND=JPRB), DIMENSION(NPROMA,NBLOCKS) ::  ZLAI,ZBIOM,ZBLOSS,ZBGAIN &
     &   , ZBIOMSTR,ZBIOMSTR2


REAL(KIND=JPRB) ::  ZMU0M(NPROMA,NBLOCKS),   ZFTG12(NPROMA,NBLOCKS)  &
     &   , ZFWEV(NPROMA,NBLOCKS)   ,ZFWSB(NPROMA,NBLOCKS)   ,ZFWG12(NPROMA,NBLOCKS) &
     &   , ZFWMLT(NPROMA,NBLOCKS)  ,ZFWROD(NPROMA,NBLOCKS)  ,ZFWRO1(NPROMA,NBLOCKS) &
     &   , ZFTLHEV(NPROMA,NBLOCKS) ,ZFTLHSB(NPROMA,NBLOCKS) ,ZVDIS(NPROMA,NBLOCKS)  &
     &   , ZCFLX(NPROMA,NTRAC,NBLOCKS)
REAL(KIND=JPRB) :: ZDHTLS(NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS) 
REAL(KIND=JPRB) :: ZDHTSS(NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS) 
REAL(KIND=JPRB) :: ZDHSSS(NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS) 
REAL(KIND=JPRB) :: ZDHTTS(NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS) 
REAL(KIND=JPRB) :: ZDHWLS(NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS) 
REAL(KIND=JPRB) :: ZDHTIS(NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS) 
REAL(KIND=JPRB) :: ZDHIIS(NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS)
REAL(KIND=JPRB) :: ZDHRESS(NPROMA,2    ,NDHVRESS+NDHFRESS,NBLOCKS) 

REAL(KIND=JPRB) :: ZDIFM(NPROMA,0:NCOM,NBLOCKS)     !KPP
REAL(KIND=JPRB) :: ZDIFT(NPROMA,0:NCOM,NBLOCKS)     !KPP
REAL(KIND=JPRB) :: ZDIFS(NPROMA,0:NCOM,NBLOCKS)     !KPP
REAL(KIND=JPRB) :: ZOTKE(NPROMA,0:NCOM,NBLOCKS)     !TKE
REAL(KIND=JPRB) :: UONUC(NPOI,0:NCOM)     !KPP 
REAL(KIND=JPRB) :: VONUC(NPOI,0:NCOM)     !KPP
REAL(KIND=JPRB) :: USTRCNU(NPOI)          !KPP
REAL(KIND=JPRB) :: VSTRNUC(NPOI)          !KPP

REAL(KIND=JPRB) :: ZDHCO2S(NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS)
REAL(KIND=JPRB) :: ZDHBIOS(NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS)
REAL(KIND=JPRB) :: ZDHVEGS(NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS)

REAL(KIND=JPRB) ::  ZLAIHI(NPOI)
REAL(KIND=JPRB) ::  ZLAILI(NPOI)

REAL(KIND=JPRB) ::  ZEVAPTIU(NPROMA,NTILES,NBLOCKS)

 
!    *ZU10M*        U-COMPONENT WIND AT 10 M                      M/S
!    *ZV10M*        V-COMPONENT WIND AT 10 M                      M/S
!    *ZT2M*         TEMPERATURE AT 2M                                K
!    *ZD2M*         DEW POINT TEMPERATURE AT 2M                      K
!    *ZQ2M*         SPECIFIC HUMIDITY AT 2M                       KG/KG
!    *ZMEAN*        AREA AVERAGED WIND SP. AT 10 M INT. FROM KLEV   M/S
!    *ZGUST*        GUST AT 10 M                                    M/S
!    *ZZIDLWV*      Zi/L used for gustiness in wave model           m/m
!                   (NOTE: Positive values of Zi/L are set to ZERO)
!    *ZBLH*         BOUNDARY LAYER HEIGHT                            M
REAL(KIND=JPRB), DIMENSION(NPROMA,NBLOCKS) :: ZU10M,ZV10M,ZT2M,ZD2M,&
     &    ZQ2M,ZMEAN,ZGUST,ZZIDLWV,ZBLH
     
REAL(KIND=JPRB),ALLOCATABLE,TARGET:: ZGPE(:,:,:) 
REAL(KIND=JPRB), POINTER:: ZTSAE1(:,:,:),ZWSAE1(:,:,:) &
     &   , ZSNSE1(:,:,:)  , ZTSNE1(:,:,:)  , ZASNE1(:,:)  , ZRSNE1(:,:,:)  ,ZWLE1(:,:) &
     &   , ZTLE1(:,:)   ,ZTILE1(:,:,:),ZWSNE1(:,:,:)
REAL(KIND=JPRB),POINTER :: ZTLICENE1(:,:),ZTLMNWNE1(:,:),ZTLWMLNE1(:,:) &        ! FLAKE
     &   ,ZTLBOTNE1(:,:),ZTLSFNE1(:,:),ZHLICENE1(:,:),ZHLMLNE1(:,:)                ! FLAKE 
REAL(KIND=JPRB),POINTER :: ZUOE1(:,:,:),ZVOE1(:,:,:), ZTOE1(:,:,:), ZSOE1(:,:,:)   !KPP

REAL(KIND=JPRB), POINTER:: ZLAIE1(:,:,:) , ZBSTRE1(:,:,:) , ZBSTR2E1(:,:,:)

INTEGER(KIND=JPIM) :: IST,IEND,IPROMA,IFLEV, IBL, NTHREADS
INTEGER(KIND=JPIM) :: JL,J
! INTEGER(KIND=JPIM) :: OMP_GET_MAX_THREADS

TYPE(TSURF), POINTER :: YSURF

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

#include "callpar1s.intfb.h"
#include "upddiag.intfb.h"

IF (LHOOK) CALL DR_HOOK('CPG1S',0,ZHOOK_HANDLE)


!     ------------------------------------------------------------------

YSURF => GET_SURF(YDSURF)
ASSOCIATE(LEOCML=>YSURF%YOCEAN_ML%LEOCML,RTT=>YSURF%YCST%RTT)

! Some initialisations
ZDHRESS(:,:,:,:)=0._JPRB
ZDHTTS(:,:,:,:)=0._JPRB
ZDHVEGS(:,:,:,:)=0._JPRB

! Allocate variables
ALLOCATE (ZGPE(NPROMA,NGPP,NBLOCKS))
ZTSAE1 => ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)
ZWSAE1 => ZGPE(:,MQLINU:MQLINU+NCSS-1,:)
ZSNSE1 => ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:)
ZTSNE1 => ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:)
ZWSNE1 => ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:)
ZRSNE1 => ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:)
ZASNE1 => ZGPE(:,MASNNU,:)
ZTLE1  => ZGPE(:,MTRENU,:)
ZWLE1  => ZGPE(:,MWRENU,:)
ZTILE1 => ZGPE(:,MTILNU:MTILNU+NCSS-1,:)

!* < FLAKE
ZTLICENE1 => ZGPE(:,MTLICENU,:)
ZTLMNWNE1 => ZGPE(:,MTLMNWNU,:)
ZTLWMLNE1 => ZGPE(:,MTLWMLNU,:)
ZTLBOTNE1 => ZGPE(:,MTLBOTNU,:)
ZTLSFNE1  => ZGPE(:,MTLSFNU,:)
ZHLICENE1 => ZGPE(:,MHLICENU,:)
ZHLMLNE1  => ZGPE(:,MHLMLNU,:)
!* FLAKE > 

ZUOE1 => ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  !KPP
ZVOE1 => ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  !KPP
ZTOE1 => ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  !KPP
ZSOE1 => ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  !KPP
UONUC(:,:)=0.0     !KPP 
VONUC(:,:)=0.0     !KPP
USTRCNU(:)=0.0     !KPP
VSTRNUC(:)=0.0     !KPP

!* < CTESSEL
ZLAIE1 => ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)
ZBSTRE1 => ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)
ZBSTR2E1 => ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:)
!* CTESSEL >



!*       1.    INITIAL COMPUTATIONS.
!              ---------------------


!     TIME STEP




!*       1.1  INITIALIZING SURFACE VARIABLES AT T-DT (FIRST TIMESTEP).
!             --------------------------------------------------------    

! --- original setting without openMP
!IST=1
!IEND=NPOI
!IPROMA=NPOI
! ---
IFLEV=NLEV
!$OMP PARALLEL
NTHREADS=OMP_GET_MAX_THREADS()
!$OMP END PARALLEL 

IF ( IDBGS1 > 1 ) THEN
  WRITE(NULOUT,*) 'CPG1S:',NPROMA,NPOI,NTHREADS
ENDIF

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1

  GP1(:,1:NGPP,IBL)=GP0(:,1:NGPP,IBL)

!     STAFF FOR CALLPAR1S

  ZAPHIF(:,:,IBL)=RG*RALT
  ZAPRS(:,IFLEV,IBL)=PNLP0(:,IBL)
  ZAPRS(:,IFLEV-1,IBL)=PNLP0(:,IBL)-RALT*0.0065
! Added "MIN(1._JPRB , ... ) to computation of ZMU0M. This ensures ZMU0M is between physical boundaries.
  ZMU0M(:,IBL)=MIN(1._JPRB, MAX( RSIDECM*GEMU(:,IBL) &
     & -RCODECM*RCOVSRM*SQRT(1._JPRB-GEMU(:,IBL)**2)*COS(GELAM(:,IBL)) &
     & +RCODECM*RSIVSRM*SQRT(1._JPRB-GEMU(:,IBL)**2)*SIN(GELAM(:,IBL)) &
     & ,0._JPRB) )

  IF(LEOCML) THEN
! replace SST with the top layer temp. of the ocean mixed layer (~ 1m depth)
    VFSST(:,IBL) = TONU0(:,1,IBL) + RTT ! The unit of PSST(VFSST) is K.  
  ENDIF

!! init 
  ZCFLX(:,:,IBL) = 0._JPRB 

!*      2.   CALL PHYSICS.
!            -------------
  CDCONF='F'
  CALL CALLPAR1S (CDCONF &
     & , 1, IPROMA   , IPROMA , IBL, NCSS  , NTILES, NVHILO & 
     & , IFLEV  ,NSTART ,NSTEP  ,NTRAC   &
     & , NLEVI  ,NCOM   ,NCSNEC          &                 !KPP
     & , NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS &
     & , NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS &
     & , NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS &
     & , NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS &
     & , NDHVCO2S,NDHFCO2S &
     & , NDHVBIOS,NDHFBIOS,NDHVVEGS,NDHFVEGS  &
     & , TDT &
!-----------------------------------------------------------------------
! - INPUT .
     & , ZAPHIF(1:IPROMA,:,IBL) , ZAPRS(1:IPROMA,:,IBL) &
     & , UNLEV0(1:IPROMA,:,IBL) , VNLEV0(1:IPROMA,:,IBL) , TNLEV0(1:IPROMA,:,IBL) , QNLEV0(1:IPROMA,:,IBL), CNLEV0(1:IPROMA,:,IBL) &
     & , FSNNU0(1:IPROMA,:,IBL) &
     & , ASNNU0(1:IPROMA,IBL) , RSNNU0(1:IPROMA,:,IBL) , TSNNU0(1:IPROMA,:,IBL),WSNNU0(1:IPROMA,:,IBL) &
     & , TSLNU0(1:IPROMA,:,IBL) , WRENU0(1:IPROMA,IBL) , TRENU0(1:IPROMA,IBL) , QLINU0(1:IPROMA,:,IBL) &
     & , TILNU0(1:IPROMA,:,IBL) &
     & , TLICENU0(1:IPROMA,IBL),TLMNWNU0(1:IPROMA,IBL),TLWMLNU0(1:IPROMA,IBL),TLBOTNU0(1:IPROMA,IBL),TLSFNU0(1:IPROMA,IBL) & ! FLAKE
     & , HLICENU0(1:IPROMA,IBL),HLMLNU0(1:IPROMA,IBL),VFLDEPTH(1:IPROMA,IBL),VFCLAKEF(1:IPROMA,IBL) &   ! FLAKE 
     & , VFALBF(1:IPROMA,IBL) &
     & , VFALUVP(1:IPROMA,IBL),VFALUVD(1:IPROMA,IBL) ,VFALNIP(1:IPROMA,IBL) ,VFALNID(1:IPROMA,IBL) &
     & , VFALUVI(1:IPROMA,IBL),VFALUVV(1:IPROMA,IBL) ,VFALUVG(1:IPROMA,IBL) &
     & , VFALNII(1:IPROMA,IBL),VFALNIV(1:IPROMA,IBL) ,VFALNIG(1:IPROMA,IBL) &
     & , VFCVL(1:IPROMA,IBL)  , VFCVH(1:IPROMA,IBL)  , VFCUR(1:IPROMA,IBL) , VFTVL(1:IPROMA,IBL)  , VFCO2TYP(1:IPROMA,IBL), VFTVH(1:IPROMA,IBL)  &
     & , VFLAIL(1:IPROMA,IBL) , VFLAIH(1:IPROMA,IBL) , VFFWET(1:IPROMA,IBL) , VFRSML(1:IPROMA,IBL) , VFRSMH(1:IPROMA,IBL) &
     & , VFSOTY(1:IPROMA,IBL) , VFSDOR(1:IPROMA,IBL) &
     & , VFCI(1:IPROMA,IBL)   , VFSST(1:IPROMA,IBL)   , GEMU(1:IPROMA,IBL),  GELAT(1:IPROMA,IBL), ZCFLX(1:IPROMA,:,IBL) &
     & , VDIEWSSTL(1:IPROMA,:,IBL),VDINSSSTL(1:IPROMA,:,IBL),VDISSHFTL(1:IPROMA,:,IBL),VDIETL(1:IPROMA,:,IBL)   ,VDTSKTL(1:IPROMA,:,IBL) &
     & , VDANDAYVT(1:IPROMA,:,IBL),VDANFMVT(1:IPROMA,:,IBL) &
     & , VDRESPBSTR(1:IPROMA,:,IBL),VDRESPBSTR2(1:IPROMA,:,IBL),VDBIOMASS_LAST(1:IPROMA,:,IBL),BSTRNU0(1:IPROMA,:,IBL),BSTR2NU0(1:IPROMA,:,IBL) & 
     & , VDBLOSSVT(1:IPROMA,:,IBL),VDBGAINVT(1:IPROMA,:,IBL) &
     & , VFITM(1:IPROMA,IBL) &
     & , VFZ0F(1:IPROMA,IBL)  , ZMU0M(1:IPROMA,IBL) &
     & , VFZ0H(1:IPROMA,IBL) &
     & , VFZO(1:IPROMA,:,IBL)     ,VFHO(1:IPROMA,:,IBL)     ,VFHO_INV(1:IPROMA,:,IBL)  ,VFDO(1:IPROMA,:,IBL)      ,VFOCDEPTH(1:IPROMA,IBL)  &!KPP
     & , VFADVT(1:IPROMA,:,IBL)   ,VFADVS(1:IPROMA,:,IBL)   ,VFTRI0(1:IPROMA,:,IBL)    ,VFTRI1(1:IPROMA,:,IBL)    ,VFSWDK_SAVE(1:IPROMA,:,IBL)&!KPP
!     & , UONUC    ,VONUC    ,USTRCNU   ,VSTRNUC               &!KPP
     & , UONU0(1:IPROMA,:,IBL)    ,VONU0(1:IPROMA,:,IBL)    ,TONU0(1:IPROMA,:,IBL)     ,SONU0(1:IPROMA,:,IBL)                 &!KPP
! - INPUT AT T+1, AND/OR ATMOSPHERIC FORCING
     & , UNLEV1(1:IPROMA,:,IBL) , VNLEV1(1:IPROMA,:,IBL) , TNLEV1(1:IPROMA,:,IBL) , QNLEV1(1:IPROMA,:,IBL) , CNLEV1(1:IPROMA,:,IBL) &
     & , FSSRD(1:IPROMA,IBL)  , FSTRD(1:IPROMA,IBL) &
     & , FCRF(1:IPROMA,IBL)   , FCSF(1:IPROMA,IBL)   , FLSRF(1:IPROMA,IBL)  , FLSSF(1:IPROMA,IBL) &
! - OUTPUT .
     & , ZEVAPTIU(1:IPROMA,:,IBL)&  
     &  ,ZU10M(1:IPROMA,IBL)  ,ZV10M(1:IPROMA,IBL)   ,ZT2M(1:IPROMA,IBL)    ,ZD2M(1:IPROMA,IBL)  &
     &  ,ZQ2M(1:IPROMA,IBL)   ,ZMEAN(1:IPROMA,IBL)   ,ZGUST(1:IPROMA,IBL)   ,ZZIDLWV(1:IPROMA,IBL)   ,ZBLH(1:IPROMA,IBL)  &
     & , ZDIFTQ(1:IPROMA,:,IBL) , ZDIFTS(1:IPROMA,:,IBL) &
     & , ZFRSO(1:IPROMA,:,IBL) &
     & , ZFRTH(1:IPROMA,:,IBL) &
     & , ZSTRTU(1:IPROMA,:,IBL) , ZSTRTV(1:IPROMA,:,IBL) &
     & , ZAN(1:IPROMA,IBL), ZAG(1:IPROMA,IBL), ZRD(1:IPROMA,IBL), ZRSOIL_STR(1:IPROMA,IBL), ZRECO(1:IPROMA,IBL), ZCO2FLUX(1:IPROMA,IBL),ZCH4FLUX(1:IPROMA,IBL) &
     & , ZLAI(1:IPROMA,IBL),LAINU0(1:IPROMA,1,IBL),LAINU0(1:IPROMA,2,IBL), ZBIOM(1:IPROMA,IBL), ZBLOSS(1:IPROMA,IBL), ZBGAIN(1:IPROMA,IBL), &
           & ZBIOMSTR(1:IPROMA,IBL), ZBIOMSTR2(1:IPROMA,IBL) &
     & , VDALB(1:IPROMA,IBL) &
     & , ZFTG12(1:IPROMA,IBL) , ZFWEV(1:IPROMA,IBL)  , ZFWSB(1:IPROMA,IBL)  , ZFWG12(1:IPROMA,IBL) , ZFWMLT(1:IPROMA,IBL) , VDZ0F(1:IPROMA,IBL)  , &
           & VDZ0H(1:IPROMA,IBL) &
     & , ZFWROD(1:IPROMA,IBL) , ZFWRO1(1:IPROMA,IBL) , ZFTLHEV(1:IPROMA,IBL), ZFTLHSB(1:IPROMA,IBL) &
     & , ZVDIS(1:IPROMA,IBL) &
     & , ZDIFM(1:IPROMA,:,IBL)  , ZDIFT(1:IPROMA,:,IBL)  , ZDIFS(1:IPROMA,:,IBL), ZOTKE(1:IPROMA,:,IBL) &             !KPP/TKE
     & , ZSNSE1(1:IPROMA,:,IBL) , ZASNE1(1:IPROMA,IBL) , ZRSNE1(1:IPROMA,:,IBL) , ZTSNE1(1:IPROMA,:,IBL),ZWSNE1(1:IPROMA,:,IBL) &
     & , ZTSAE1(1:IPROMA,:,IBL) &
     & , ZWLE1(1:IPROMA,IBL)  , ZTLE1(1:IPROMA,IBL)  , ZWSAE1(1:IPROMA,:,IBL) &
     & , ZTILE1(1:IPROMA,:,IBL) &
     & , ZTLICENE1(1:IPROMA,IBL),ZTLMNWNE1(1:IPROMA,IBL),ZTLWMLNE1(1:IPROMA,IBL)&          ! FLAKE 
     & , ZTLBOTNE1(1:IPROMA,IBL),ZTLSFNE1(1:IPROMA,IBL),ZHLICENE1(1:IPROMA,IBL),ZHLMLNE1(1:IPROMA,IBL) & ! FLAKE 
     & , ZUOE1(1:IPROMA,:,IBL)  , ZVOE1(1:IPROMA,:,IBL)  , ZTOE1(1:IPROMA,:,IBL)  , ZSOE1(1:IPROMA,:,IBL) &            !KPP
     & , ZLAIE1(1:IPROMA,:,IBL), ZBSTRE1(1:IPROMA,:,IBL), ZBSTR2E1(1:IPROMA,:,IBL) &
     & , ZDHTLS(1:IPROMA,:,:,IBL),ZDHTSS(1:IPROMA,:,:,IBL),ZDHTTS(1:IPROMA,:,:,IBL),ZDHTIS(1:IPROMA,:,:,IBL),ZDHIIS(1:IPROMA,:,IBL), &
           & ZDHSSS(1:IPROMA,:,:,IBL),ZDHWLS(1:IPROMA,:,:,IBL),ZDHRESS(1:IPROMA,:,:,IBL) &
     & , ZDHCO2S(1:IPROMA,:,:,IBL),ZDHBIOS(1:IPROMA,:,:,IBL),ZDHVEGS(1:IPROMA,:,:,IBL))

!*           UPDATE DIAGNOSTICS
!     ------------------------------------------------------------------

  CALL UPDDIAG( &
   & 1,IPROMA,IPROMA,IFLEV,NCSS,NCSNEC,NTILES,NVHILO,&   
   & NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
   & NDHVTTS,NDHFTTS,NDHVSSS,NDHFSSS, &
   & NDHVIIS,NDHFIIS,NDHVWLS,NDHFWLS, &
   & NDHVRESS,NDHFRESS, &
   & NDHVCO2S,NDHFCO2S,NDHVBIOS,NDHFBIOS, &
   & NDHVVEGS,NDHFVEGS, & 
   & TDT,IST,IEND, IPROMA, IBL, &
   & ZEVAPTIU(1:IPROMA,:,IBL),&
   & ZAN(1:IPROMA,IBL),ZAG(1:IPROMA,IBL),ZRD(1:IPROMA,IBL),ZRSOIL_STR(1:IPROMA,IBL),ZRECO(1:IPROMA,IBL),ZCO2FLUX(1:IPROMA,IBL),ZCH4FLUX(1:IPROMA,IBL), &
   & ZLAI(1:IPROMA,IBL),ZBIOM(1:IPROMA,IBL),ZBLOSS(1:IPROMA,IBL),ZBGAIN(1:IPROMA,IBL),ZBIOMSTR(1:IPROMA,IBL),ZBIOMSTR2(1:IPROMA,IBL), &
   & TNLEV1(1:IPROMA,:,IBL),QNLEV1(1:IPROMA,:,IBL),UNLEV1(1:IPROMA,:,IBL),VNLEV1(1:IPROMA,:,IBL),PNLP1(1:IPROMA,IBL),&
   & ZFRSO(1:IPROMA,:,IBL),FSSRD(1:IPROMA,IBL),ZFRTH(1:IPROMA,:,IBL),FSTRD(1:IPROMA,IBL),VDALB(1:IPROMA,IBL),ZFTLHEV(1:IPROMA,IBL),ZFTLHSB(1:IPROMA,IBL), &
   & ZDIFTQ(1:IPROMA,:,IBL),ZDIFTS(1:IPROMA,:,IBL),ZSTRTU(1:IPROMA,:,IBL),ZSTRTV(1:IPROMA,:,IBL),ZWSAE1(1:IPROMA,:,IBL),ZSNSE1(1:IPROMA,:,IBL), &
       & ZWLE1(1:IPROMA,IBL), &
   & FCRF(1:IPROMA,IBL)    ,FCSF(1:IPROMA,IBL)   ,FLSRF(1:IPROMA,IBL),FLSSF(1:IPROMA,IBL), ZFWRO1(1:IPROMA,IBL),ZFWROD(1:IPROMA,IBL),ZFWMLT(1:IPROMA,IBL),&
   & ZDHTLS(1:IPROMA,:,:,IBL),ZDHTSS(1:IPROMA,:,:,IBL),ZDHTTS(1:IPROMA,:,:,IBL),ZDHSSS(1:IPROMA,:,:,IBL),ZDHIIS(1:IPROMA,:,IBL),ZDHWLS(1:IPROMA,:,:,IBL), &
       & ZDHRESS(1:IPROMA,:,:,IBL),&
   & ZT2M(1:IPROMA,IBL),ZD2M(1:IPROMA,IBL),ZDHCO2S(1:IPROMA,:,:,IBL),ZDHBIOS(1:IPROMA,:,:,IBL),ZDHVEGS(1:IPROMA,:,:,IBL))
 

!*       3.  COMPUTATION OF T+DT VALUES FOR SURFACE VARIABLES.
!            -------------------------------------------------
! WARM START FIX
  IF (NSTEP == 0) THEN 
!    GP1(IST:IEND, MRSNNU:MTSNNU+NCSNEC-1)  = RSNNU0(IST:IEND, 1:NCSNEC) 
!    GP1(IST:IEND, MTSNNU:MTSNNU+NCSNEC-1 ) = TSNNU0(IST:IEND, 1:NCSNEC)
!    GP1(IST:IEND, MFSNNU:MTSNNU+NCSNEC-1)  = FSNNU0(IST:IEND, 1:NCSNEC) 
!    GP1(IST:IEND, MWSNNU:MWSNNU+NCSNEC-1)  = WSNNU0(IST:IEND, 1:NCSNEC) 
    GP1(:, MRSNNU:MRSNNU+NCSNEC-1,IBL)  = RSNNU0(:, 1:NCSNEC, IBL) 
    GP1(:, MTSNNU:MTSNNU+NCSNEC-1,IBL ) = TSNNU0(:, 1:NCSNEC, IBL)
    GP1(:, MFSNNU:MFSNNU+NCSNEC-1,IBL)  = FSNNU0(:, 1:NCSNEC, IBL) 
    GP1(:, MWSNNU:MWSNNU+NCSNEC-1,IBL)  = WSNNU0(:, 1:NCSNEC, IBL) 
  END IF


  GP1(:,1:NGPP,IBL)=GP1(:,1:NGPP,IBL)+ &
       &                TDT*ZGPE(:,1:NGPP,IBL)
!*       4.  SWAPPING OF SURFACE VARIABLES.
!            ------------------------------

  GP0(:,1:NGPP,IBL)=GP1(:,1:NGPP,IBL)

!*       5.   ACCUMULATE 1D DIAGNOSTIC TENDENCIES.
!             ------------------------------------

  DO J=1,N2DDI
    GDI1S(IST:IEND,J,2)=GDI1S(IST:IEND,J,2)+TSTEP*GDI1S(IST:IEND,J,1)
  ENDDO

!*       6.   AVERAGE AUXILIARY DIAGNOSTICS
!             ------------------------------------

  DO J=1,N2DDIAUX
    GDIAUX1S(IST:IEND,J,2)=GDIAUX1S(IST:IEND,J,2)+&
     &TSTEP*GDIAUX1S(IST:IEND,J,1)
  ENDDO

ENDDO !IST LOOP
!$OMP END PARALLEL DO 


!     ------------------------------------------------------------------

DEALLOCATE (ZGPE)
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPG1S',1,ZHOOK_HANDLE)
RETURN
END SUBROUTINE CPG1S
