SUBROUTINE CPG1S
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE YOMDPHY  ,  ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, &
      &                NVHILO, NGPP, NPOI, NLEV, NBLOCKS
USE YOMCDH1S ,  ONLY : NLEVI, NDHFCO2S , &
      &                NDHVSSS, NDHFSSS, NDHVIIS, NDHFIIS, &
      &                NDHVWLS, NDHFWLS, NDHVRESS, NDHFRESS, &
      &                NDHVTTS, NDHFTTS, NDHVTIS, NDHFTIS, &
      &                NDHVTLS, NDHFTLS, NDHVTSS, NDHFTSS, &
      &                NDHVCO2S, NDHFCO2S, &
      &                NDHVBIOS, NDHFBIOS, NDHVBVOCS, NDHVVEGS, NDHFVEGS
USE YOMDYN1S ,  ONLY : NSTEP, TDT, TSTEP
USE YOMGPD1S ,  ONLY : VFSST, VFALUVI, VFALUVV, VFALUVG,&
      &                VFALNII, VFALNIV, VFALNIG, VFALUVP, VFALUVD, &
      &                VFALNIP, VFALNID, VFZ0F, VFZ0H, VFAVGPAR
USE YOMGF1S  ,  ONLY : PNLP0, PNLP1, RALT, RZUV
USE YOMGP1S0 ,  ONLY : GP0, TONU0, RSNNU0, TSNNU0, FSNNU0, WSNNU0, LAINU0
USE YOMGP1S1 ,  ONLY : GP1, LAINU1
USE PTRGP1S  ,  ONLY : MFSNNU, MRSNNU, MTSNNU, MWSNNU
USE YOMLOG1S,   ONLY : IDBGS1
USE YOMCT01S ,  ONLY : NSTART
USE YOMCST   ,  ONLY : RG, RSIGMA, RDAY
USE YOERIP   ,  ONLY : RCODECM, RSIDECM, RCOVSRM, RSIVSRM
USE YOERAD   ,  ONLY : NSW, NTSW, NLWEMISS
USE YOERDI1S ,  ONLY : REMISS
USE YOMRIP   ,  ONLY : RSTATI, NSSSSS
USE YOMDIM1S ,  ONLY : NPROMA
USE YOEPHY   ,  ONLY : LERADS, LESICE, LESURF, LEVDIF, LEWARMSTART, &
      &                LESNICE, NALBEDOSCHEME, NCWS, LBVOC_EMIS
USE YOMGDI1S ,  ONLY : GDI1S   , N2DDI ,&
      &                GDIAUX1S, N2DDIAUX

USE YOMLUN1S, ONLY : NULOUT
USE YOMLOG1S, ONLY : LSEMISS
USE YOMSURF_SSDP_MOD, ONLY : NSSDP2D, NSSDP3D

USE ECLAND_ATMO_TYPE_MOD,       ONLY: ATMO_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY: CLIMATE_TYPE
USE ECLAND_DDH_TYPE_MOD,        ONLY: DDH_SURF_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY: FLUX_TYPE
USE ECLAND_GEMS_TYPE_MOD,       ONLY: GEMS_LOCAL_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY: INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY: SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY: SURF_AND_MORE_LOCAL_TYPE
USE SURFBC_LAYER_MOD,           ONLY: SURFBC_LAYER_PARALLEL
USE SURFRAD_LAYER_MOD,          ONLY: SURFRAD_LAYER_PARALLEL
USE SURFTSTP_LAYER_MOD,         ONLY: SURFTSTP_LAYER_PARALLEL
USE VDFMAIN1S_LAYER_MOD,        ONLY: VDFMAIN1S_LAYER_PARALLEL

USE OMP_LIB, ONLY: OMP_GET_MAX_THREADS


#ifdef DOC
#endif

USE PARKIND1  ,ONLY : JPIM  ,JPRB,    JPRD, JPIB
USE YOMHOOK   ,ONLY : LHOOK ,DR_HOOK, JPHOOK
IMPLICIT NONE


CHARACTER*1 :: CDCONF
INTEGER(KIND=JPIM) :: IST, IEND, IFLEV, IBL, NTHREADS
INTEGER(KIND=JPIM) :: JL, J, KIDIA, KFDIA
INTEGER(KIND=JPIM) :: KLON, KLEVS, KTILES, KVTYPES, KLEV, KSTART, KSTEP, KTRAC
INTEGER(KIND=JPIM) :: KLEVSN, KLEVI, KLEVO, KDHVTLS, KDHFTLS, KDHVTSS, KDHFTSS
INTEGER(KIND=JPIM) :: KDHVTTS, KDHFTTS, KDHVTIS, KDHFTIS, KDHVSSS, KDHFSSS
INTEGER(KIND=JPIM) :: KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS, KDHVRESS, KDHFRESS
INTEGER(KIND=JPIM) :: KDHVCO2S, KDHFCO2S, KDHVBIOS, KDHFBIOS, KDHVBVOCS
INTEGER(KIND=JPIM) :: KDHVVEGS, KDHFVEGS, JPDIAG, KULOUT
INTEGER(KIND=JPIM) :: IMON(12), IYY, IMM, IDD, IINC, ISEC0, IYMD, IHM
INTEGER(KIND=JPIM) :: JK, JTILE, JVT
REAL(KIND=JPRB) :: PTSPHY
REAL(KIND=JPRB) :: ZFAC(NPROMA)
REAL(KIND=JPRD) :: ZJUL
LOGICAL :: LDEBUGPRINT, LNEMOLIMALB

TYPE(GEMS_LOCAL_TYPE)           :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           :: LLKEYS
TYPE(AUX_TYPE)                  :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       :: PAUXL
TYPE(CLIMATE_TYPE)              :: PCLIM
TYPE(DDH_SURF_TYPE)             :: PDDHS
TYPE(AUX_DIAG_TYPE)             :: PDIAG
TYPE(FLUX_TYPE)                 :: PFLUX
TYPE(INTERNAL_TYPE)             :: PINTER
TYPE(SURF_AND_MORE_TYPE)        :: PSURF, ZSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  :: PSURFL
TYPE(ATMO_TYPE)                 :: STATE

INTEGER(KIND=JPIM) :: IDD, IMM, IYY, IINC, ISEC0, IYMD, IHM, IMON(12), JK, KULOUT

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE, ZHOOK_HANDLE_CALLPAR
#include "surfws.h"
#include "surfrad.h"
#include "updcal.intfb.h"
#include "upddiag.intfb.h"
#include "fcttim.h"
IF (LHOOK) CALL DR_HOOK('CPG1S',0,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

CALL GEMSL%INIT(NPROMA, NBLOCKS, NTRAC, NDHVBVOCS, PERSISTENT=.TRUE.)
CALL LLKEYS%INIT(NPROMA, NBLOCKS, PERSISTENT=.TRUE.)
CALL PAUX%INIT(NPROMA, NLEV, NBLOCKS, PERSISTENT=.TRUE.)
CALL PAUXL%INIT(NPROMA, NBLOCKS)
CALL PCLIM%INIT()
CALL PDDHS%INIT(NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO, PERSISTENT=.TRUE.)
CALL PDIAG%INIT(NPROMA, NBLOCKS, PERSISTENT=.TRUE.)
CALL PFLUX%INIT(NPROMA, NLEV, NCSS, NBLOCKS, PERSISTENT=.TRUE.)
CALL PINTER%INIT()
CALL PSURF%INIT(NPROMA, NGPP, NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS, PERSISTENT=.TRUE.)
CALL PSURFL%INIT(NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS, NVHILO, PERSISTENT=.TRUE.)
CALL STATE%INIT(NPROMA, NLEV, NBLOCKS, PERSISTENT=.TRUE.)

  ASSOCIATE(LEOCML=>YSURF%YOCEAN_ML%LEOCML,RTT=>YSURF%YCST%RTT)

!*       1.    INITIAL COMPUTATIONS.
!              ---------------------

!     TIME STEP

!*       1.1  INITIALIZING SURFACE VARIABLES AT T-DT (FIRST TIMESTEP).
!             --------------------------------------------------------

! --- original setting without openMP
!IST=1
!IEND=NPOI
!KFDIA=NPOI
! ---
IFLEV=NLEV
!$OMP PARALLEL
!$OMP SINGLE
NTHREADS=OMP_GET_MAX_THREADS()
!$OMP END SINGLE
!$OMP END PARALLEL

IF ( IDBGS1 > 1 ) THEN
  WRITE(NULOUT,*) 'CPG1S:',NPROMA,NPOI,NTHREADS
ENDIF

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, CDCONF, ZSURF, &
!$OMP  & KLON, KLEVS, KTILES, KVTYPES, KLEV, KSTART, KSTEP, KTRAC, KLEVSN, KLEVI, KLEVO, &
!$OMP  & KDHVTLS, KDHFTLS, KDHVTSS, KDHFTSS, KDHVTTS, KDHFTTS, KDHVTIS, KDHFTIS, &
!$OMP  & KDHVSSS, KDHFSSS, KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS, KDHVRESS, KDHFRESS, &
!$OMP  & KDHVCO2S, KDHFCO2S, KDHVBIOS, KDHFBIOS, KDHVBVOCS, KDHVVEGS, KDHFVEGS, &
!$OMP  & JPDIAG, KULOUT, IMON, IYY, IMM, IDD, IINC, ISEC0, IYMD, IHM, JK, JTILE, JVT, &
!$OMP  & PTSPHY, ZFAC, ZJUL, LDEBUGPRINT, LNEMOLIMALB, ZHOOK_HANDLE_CALLPAR) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PDIAG, PAUXL, PAUX, PFLUX, STATE, PINTER, GEMSL, LLKEYS, PDDHS) &
!$OMP SHARED(GP0,GP1,GDI1S,GDIAUX1S)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA=1
  KFDIA = IEND-IST+1

  ! Update block views
  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL GEMSL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)

  GP1(KIDIA:KFDIA,1:NGPP,IBL)=GP0(KIDIA:KFDIA,1:NGPP,IBL)

!     STAFF FOR CALLPAR1S

  STATE%PGEOM1(KIDIA:KFDIA,1:NLEV)=RG*RALT
  PAUX%PMU0M(KIDIA:KFDIA)=MIN(1._JPRB, MAX( RSIDECM*PAUX%PGEMU(KIDIA:KFDIA) &
     & -RCODECM*RCOVSRM*SQRT(1._JPRB-PAUX%PGEMU(KIDIA:KFDIA)**2)*COS(PAUX%GELAM(KIDIA:KFDIA)) &
     & +RCODECM*RSIVSRM*SQRT(1._JPRB-PAUX%PGEMU(KIDIA:KFDIA)**2)*SIN(PAUX%GELAM(KIDIA:KFDIA)) &
     & ,0._JPRB) )
  STATE%PAPRS(KIDIA:KFDIA,IFLEV  )=PNLP0(KIDIA:KFDIA,IBL)
  STATE%PAPRS(KIDIA:KFDIA,IFLEV-1)=PNLP0(KIDIA:KFDIA,IBL)-RALT*0.0065_JPRB

  IF(LEOCML) THEN
! replace SST with the top layer temp. of the ocean mixed layer (~ 1m depth)
    VFSST(KIDIA:KFDIA,IBL) = TONU0(KIDIA:KFDIA,1,IBL) + RTT
  ENDIF

!! init
  GEMSL%PCFLX(KIDIA:KFDIA,:) = 0._JPRB

  ZSURF%PUSTRC(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PVSTRC(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%GSP%PUOC(KIDIA:KFDIA,:)=0.0_JPRB
  ZSURF%GSP%PVOC(KIDIA:KFDIA,:)=0.0_JPRB
  ZSURF%GSP%PSST(KIDIA:KFDIA)=VFSST(KIDIA:KFDIA,IBL)
  PSURFL%PLAILI(KIDIA:KFDIA)=LAINU0(KIDIA:KFDIA,1,IBL)
  PSURFL%PLAIHI(KIDIA:KFDIA)=LAINU0(KIDIA:KFDIA,2,IBL)

  IF (NALBEDOSCHEME == 2) THEN
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,1) = VFALUVI(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,2) = VFALUVV(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,3) = VFALUVG(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,4) = VFALNII(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,5) = VFALNIV(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,6) = VFALNIG(KIDIA:KFDIA,IBL)
  ELSE
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,1) = VFALUVP(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,2) = VFALUVD(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,3) = VFALNIP(KIDIA:KFDIA,IBL)
    ZSURF%GSD%ZALCOEFF(KIDIA:KFDIA,4) = VFALNID(KIDIA:KFDIA,IBL)
  ENDIF
!*       1.1   FIRST TIME-STEP
  IF (NSTEP.EQ.NSTART) THEN
    GEMSL%PZ0M(KIDIA:KFDIA)=MAX(0.001_JPRB ,VFZ0F(KIDIA:KFDIA,IBL))
    GEMSL%PZ0H(KIDIA:KFDIA)=MAX(0.0001_JPRB,VFZ0H(KIDIA:KFDIA,IBL))
  ENDIF

!* Initialize dummy AVGPAR array, fill with zero if no BVOC emissions
  IF ( LBVOC_EMIS ) THEN
        ZSURF%GSD%ZAVGPARC(KIDIA:KFDIA) = VFAVGPAR(KIDIA:KFDIA,IBL) ! W/m2
  ELSE
        ZSURF%GSD%ZAVGPARC(KIDIA:KFDIA) = 0._JPRB
  ENDIF

!*      2.   CALL PHYSICS.
!            -------------
  CDCONF='F'
  KLON=NPROMA
  KLEVS=NCSS
  KTILES=NTILES
  KVTYPES=NVHILO
  KLEV=IFLEV
  KSTART=NSTART
  KSTEP=NSTEP
  KTRAC=NTRAC
  KLEVI=NLEVI
  KLEVO=NCOM
  KLEVSN=NCSNEC
  KDHVTLS=NDHVTLS
  KDHFTLS=NDHFTLS
  KDHVTSS=NDHVTSS
  KDHFTSS=NDHFTSS
  KDHVTTS=NDHVTTS
  KDHFTTS=NDHFTTS
  KDHVTIS=NDHVTIS
  KDHFTIS=NDHFTIS
  KDHVSSS=NDHVSSS
  KDHFSSS=NDHFSSS
  KDHVIIS=NDHVIIS
  KDHFIIS=NDHFIIS
  KDHVWLS=NDHVWLS
  KDHFWLS=NDHFWLS
  KDHVRESS=NDHVRESS
  KDHFRESS=NDHFRESS
  KDHVCO2S=NDHVCO2S
  KDHFCO2S=NDHFCO2S
  KDHVBIOS=NDHVBIOS
  KDHFBIOS=NDHFBIOS
  KDHVBVOCS=NDHVBVOCS
  KDHVVEGS=NDHVVEGS
  KDHFVEGS=NDHFVEGS
  PTSPHY=TDT
  JPDIAG=12
  KULOUT=-1_JPIM
!    ------------------------------------------------------------------

!*         1.     INITIAL COMPUTATIONS.
!                 ---------------------

!* Interpolate wind to correct height
!IF(RALT.NE.RZUV) THEN
IF(RALT .NE. RZUV .AND. KSTEP .NE. KSTART ) THEN
    ZFAC(KIDIA:KFDIA)=LOG(RALT/GEMSL%PZ0M(KIDIA:KFDIA))/LOG(RZUV/GEMSL%PZ0M(KIDIA:KFDIA))
    STATE%PU(KIDIA:KFDIA)  = ZFAC(KIDIA:KFDIA)* STATE%PU(KIDIA:KFDIA)
    STATE%PV(KIDIA:KFDIA)  = ZFAC(KIDIA:KFDIA)* STATE%PV(KIDIA:KFDIA)
    STATE%PU1(KIDIA:KFDIA) = ZFAC(KIDIA:KFDIA)*STATE%PU1(KIDIA:KFDIA)
    STATE%PV1(KIDIA:KFDIA) = ZFAC(KIDIA:KFDIA)*STATE%PV1(KIDIA:KFDIA)
ENDIF


!*      1.2  TENDENCIES OF FORCINGS

 ZSURF%ZTE(KIDIA:KFDIA)=(STATE%PT1(KIDIA:KFDIA)-STATE%PT(KIDIA:KFDIA))/PTSPHY
 ZSURF%ZQE(KIDIA:KFDIA)=(STATE%PQ1(KIDIA:KFDIA)-STATE%PQ(KIDIA:KFDIA))/PTSPHY
ZSURF%ZVOM(KIDIA:KFDIA)=(STATE%PU1(KIDIA:KFDIA)-STATE%PU(KIDIA:KFDIA))/PTSPHY
ZSURF%ZVOL(KIDIA:KFDIA)=(STATE%PV1(KIDIA:KFDIA)-STATE%PV(KIDIA:KFDIA))/PTSPHY
IF(KTRAC .GT. 0 ) THEN
  ZSURF%ZTENC(KIDIA:KFDIA,1:KTRAC)= &
    &   (GEMSL%PC1(KIDIA:KFDIA,1:KTRAC)-GEMSL%PC(KIDIA:KFDIA,1:KTRAC))/PTSPHY
ENDIF


PSURFL%ZCSN(KIDIA:KFDIA)=0.0_JPRB
ENDDO !IST LOOP
!$OMP END DO
!$OMP END PARALLEL

CALL SURFBC_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS, ON_GPU=.TRUE.)

CALL DATTIM(ZJUL, IYMD, IHM)
IDD=NDD(IYMD)
IMM=NMM(IYMD)
IYY=NCCAA(IYMD)
IINC=0
ISEC0=MOD(NSSSSS+NINT(RSTATI,JPIB),NINT(RDAY))
KULOUT=-1_JPIM
CALL UPDCAL(IDD, IMM, IYY, IINC, IDD, IMM, IYY, IMON, KULOUT)

CALL SURFRAD_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, ON_GPU=.TRUE.)

CALL VDFMAIN1S_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS, ON_GPU=.TRUE.)

CALL SURFTSTP_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS, ON_GPU=.TRUE.)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, CDCONF, ZSURF, &
!$OMP  & KLON, KLEVS, KTILES, KVTYPES, KLEV, KSTART, KSTEP, KTRAC, KLEVSN, KLEVI, KLEVO, &
!$OMP  & KDHVTLS, KDHFTLS, KDHVTSS, KDHFTSS, KDHVTTS, KDHFTTS, KDHVTIS, KDHFTIS, &
!$OMP  & KDHVSSS, KDHFSSS, KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS, KDHVRESS, KDHFRESS, &
!$OMP  & KDHVCO2S, KDHFCO2S, KDHVBIOS, KDHFBIOS, KDHVBVOCS, KDHVVEGS, KDHFVEGS, &
!$OMP  & JPDIAG, KULOUT, IMON, IYY, IMM, IDD, IINC, ISEC0, IYMD, IHM, JK, JTILE, JVT, &
!$OMP  & PTSPHY, ZFAC, ZJUL, LDEBUGPRINT, LNEMOLIMALB, ZHOOK_HANDLE_CALLPAR) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PDIAG, PAUXL, PAUX, PFLUX, STATE, PINTER, GEMSL, LLKEYS, PDDHS) &
!$OMP SHARED(GP0,GP1,GDI1S,GDIAUX1S)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA=1
  KFDIA = IEND-IST+1

  ! Update block views
  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL GEMSL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)

  CDCONF='F'
  KLON=NPROMA
  KLEVS=NCSS
  KTILES=NTILES
  KVTYPES=NVHILO
  KLEV=IFLEV
  KSTART=NSTART
  KSTEP=NSTEP
  KTRAC=NTRAC
  KLEVI=NLEVI
  KLEVO=NCOM
  KLEVSN=NCSNEC
  KDHVTLS=NDHVTLS
  KDHFTLS=NDHFTLS
  KDHVTSS=NDHVTSS
  KDHFTSS=NDHFTSS
  KDHVTTS=NDHVTTS
  KDHFTTS=NDHFTTS
  KDHVTIS=NDHVTIS
  KDHFTIS=NDHFTIS
  KDHVSSS=NDHVSSS
  KDHFSSS=NDHFSSS
  KDHVIIS=NDHVIIS
  KDHFIIS=NDHFIIS
  KDHVWLS=NDHVWLS
  KDHFWLS=NDHFWLS
  KDHVRESS=NDHVRESS
  KDHFRESS=NDHFRESS
  KDHVCO2S=NDHVCO2S
  KDHFCO2S=NDHFCO2S
  KDHVBIOS=NDHVBIOS
  KDHFBIOS=NDHFBIOS
  KDHVBVOCS=NDHVBVOCS
  KDHVVEGS=NDHVVEGS
  KDHFVEGS=NDHFVEGS
  PTSPHY=TDT
  JPDIAG=12
  KULOUT=-1_JPIM

!*              5.     END OF E.C.M.W.F. PHYSICS
!                      -------------------------
!* CTESSEL >
!*           UPDATE DIAGNOSTICS
!     ------------------------------------------------------------------

  CALL UPDDIAG( &
   & IBL=IBL, &
   & KIDIA=1, KFDIA=KFDIA, KLON=NPROMA, KLEV=IFLEV, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES,  &
   & PTSPHY=TDT, &
   & PPSURF=PNLP1, &
   & PSURF=ZSURF, PSURFL=PSURFL, PCLIM=PCLIM, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX, &
   & PDIAG=PDIAG, STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)

!*       3.  COMPUTATION OF T+DT VALUES FOR SURFACE VARIABLES.
!            -------------------------------------------------
! WARM START FIX
  IF (NSTEP == 0) THEN
    GP1(KIDIA:KFDIA, MRSNNU:MRSNNU+NCSNEC-1,IBL) = RSNNU0(KIDIA:KFDIA, 1:NCSNEC, IBL)
    GP1(KIDIA:KFDIA, MTSNNU:MTSNNU+NCSNEC-1,IBL) = TSNNU0(KIDIA:KFDIA, 1:NCSNEC, IBL)
    GP1(KIDIA:KFDIA, MFSNNU:MFSNNU+NCSNEC-1,IBL) = FSNNU0(KIDIA:KFDIA, 1:NCSNEC, IBL)
    GP1(KIDIA:KFDIA, MWSNNU:MWSNNU+NCSNEC-1,IBL) = WSNNU0(KIDIA:KFDIA, 1:NCSNEC, IBL)
  END IF

  GP1(KIDIA:KFDIA,1:NGPP,IBL)=GP1(KIDIA:KFDIA,1:NGPP,IBL) + TDT*ZSURF%ZGPE_STACK(KIDIA:KFDIA,1:NGPP)
!*       4.  SWAPPING OF SURFACE VARIABLES.
!            ------------------------------

  GP0(KIDIA:KFDIA,1:NGPP,IBL)=GP1(KIDIA:KFDIA,1:NGPP,IBL)

!*       5.   ACCUMULATE 1D DIAGNOSTIC TENDENCIES.
!             ------------------------------------

  DO J=1,N2DDI
    GDI1S(KIDIA:KFDIA,J,2,IBL)=GDI1S(KIDIA:KFDIA,J,2,IBL)+TSTEP*GDI1S(KIDIA:KFDIA,J,1,IBL)
  ENDDO

!*       6.   AVERAGE AUXILIARY DIAGNOSTICS
!             ------------------------------------

  DO J=1,N2DDIAUX
    GDIAUX1S(KIDIA:KFDIA,J,2,IBL)=GDIAUX1S(KIDIA:KFDIA,J,2,IBL)+TSTEP*GDIAUX1S(KIDIA:KFDIA,J,1,IBL)
  ENDDO

ENDDO !IST LOOP
!$OMP END DO
!$OMP END PARALLEL

!     ------------------------------------------------------------------
CALL GEMSL%FINAL
CALL LLKEYS%FINAL
CALL PAUX%FINAL
CALL PAUXL%FINAL
CALL PCLIM%FINAL
CALL PFLUX%FINAL
CALL PDDHS%FINAL
CALL PDIAG%FINAL
CALL PINTER%FINAL
CALL PSURF%FINAL
CALL PSURFL%FINAL
CALL STATE%FINAL
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CPG1S',1,ZHOOK_HANDLE)
END SUBROUTINE CPG1S
