MODULE ECLAND_ATMO_TYPE_MOD

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMGF1S , ONLY: UNLEV0   ,VNLEV0   ,TNLEV0   ,QNLEV0   ,&
     &              PNLP0    ,UNLEV1   ,VNLEV1   ,TNLEV1   ,QNLEV1
USE FIELD_MODULE, ONLY: FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE ATMO_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PGEOM1 => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PGEOM1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PAPRS  => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PAPRS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU => NULL(),PV => NULL(),PT => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU1=> NULL(),PV1=> NULL(),PT1=> NULL() ! GMV fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ  => NULL() ! GFL fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ1 => NULL() ! GFL fields

CONTAINS
  PROCEDURE :: INIT  => ATMO_TYPE_INIT
  PROCEDURE :: FINAL => ATMO_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => ATMO_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => ATMO_TYPE_SYNC_HOST
END TYPE ATMO_TYPE

CONTAINS

  SUBROUTINE ATMO_TYPE_INIT(SELF,NPROMA,NLEV,NBLOCKS) 
    CLASS(ATMO_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NLEV,NBLOCKS

    SELF%PU =>UNLEV0
    SELF%PV =>VNLEV0
    SELF%PT =>TNLEV0
    SELF%PQ =>QNLEV0
    SELF%PU1=>UNLEV1
    SELF%PV1=>VNLEV1
    SELF%PT1=>TNLEV1
    SELF%PQ1=>QNLEV1

    CALL FIELD_NEW(SELF%F_PAPRS, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PGEOM1, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
  END SUBROUTINE ATMO_TYPE_INIT

  SUBROUTINE ATMO_TYPE_FINAL(SELF)
    CLASS(ATMO_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PAPRS)
    CALL FIELD_DELETE(SELF%F_PGEOM1)

    NULLIFY(SELF%PU)
    NULLIFY(SELF%PV)
    NULLIFY(SELF%PT)
    NULLIFY(SELF%PQ)
    NULLIFY(SELF%PU1)
    NULLIFY(SELF%PV1)
    NULLIFY(SELF%PT1)
    NULLIFY(SELF%PQ1)
    NULLIFY(SELF%PAPRS)
    NULLIFY(SELF%PGEOM1)
  END SUBROUTINE ATMO_TYPE_FINAL

  SUBROUTINE ATMO_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(ATMO_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PAPRS))  SELF%PAPRS  => SELF%F_PAPRS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PGEOM1)) SELF%PGEOM1 => SELF%F_PGEOM1%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE ATMO_TYPE_UPDATE_VIEW

  SUBROUTINE ATMO_TYPE_SYNC_HOST(SELF)
    CLASS(ATMO_TYPE) :: SELF
    CALL SELF%F_PAPRS%SYNC_HOST_RDWR()
    CALL SELF%F_PGEOM1%SYNC_HOST_RDWR()
  END SUBROUTINE ATMO_TYPE_SYNC_HOST

END MODULE ECLAND_ATMO_TYPE_MOD
