MODULE ECLAND_INTERNAL_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGPD1S, ONLY : VFDO, VFHO, VFLDEPTH, GPD_SDP2, GPD_SDP3

IMPLICIT NONE

TYPE INTERNAL_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PDO
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PHO
  REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: PLDEPTH
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PSSDP2 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PSSDP3
CONTAINS
  PROCEDURE :: INIT => INTERNAL_TYPE_INIT
  PROCEDURE :: FINAL => INTERNAL_TYPE_FINAL
END TYPE INTERNAL_TYPE

CONTAINS

 SUBROUTINE INTERNAL_TYPE_INIT(SELF)
    CLASS(INTERNAL_TYPE) :: SELF
    SELF%PDO=>VFDO
    SELF%PHO=>VFHO
    SELF%PLDEPTH=>VFLDEPTH
    SELF%PSSDP2 => GPD_SDP2(:,:,:)
    SELF%PSSDP3 => GPD_SDP3(:,:,:,:)

 END SUBROUTINE INTERNAL_TYPE_INIT

 SUBROUTINE INTERNAL_TYPE_FINAL(SELF)
    CLASS(INTERNAL_TYPE) :: SELF
 END SUBROUTINE INTERNAL_TYPE_FINAL

END MODULE ECLAND_INTERNAL_TYPE_MOD
