MODULE ECLAND_INTERNAL_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGPD1S, ONLY : VFDO, VFHO, VFLDEPTH, GPD_SDP2, GPD_SDP3

IMPLICIT NONE

TYPE INTERNAL_TYPE

  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PSSDP2  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PSSDP3  => NULL()
CONTAINS
  PROCEDURE :: INIT  => INTERNAL_TYPE_INIT
  PROCEDURE :: FINAL => INTERNAL_TYPE_FINAL
END TYPE INTERNAL_TYPE

CONTAINS

 SUBROUTINE INTERNAL_TYPE_INIT(SELF)
    CLASS(INTERNAL_TYPE) :: SELF

    SELF%PSSDP2 => GPD_SDP2
    SELF%PSSDP3 => GPD_SDP3
 END SUBROUTINE INTERNAL_TYPE_INIT

 SUBROUTINE INTERNAL_TYPE_FINAL(SELF)
    CLASS(INTERNAL_TYPE) :: SELF

    NULLIFY(SELF%PSSDP2) 
    NULLIFY(SELF%PSSDP3) 
 END SUBROUTINE INTERNAL_TYPE_FINAL

END MODULE ECLAND_INTERNAL_TYPE_MOD
