MODULE ECLAND_CLIMATE_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGPD1S , ONLY : VFCLAKEF, VFTVL, VFTVH, VDALB, &
                      VFSOTY  , VFCVL, VFCVH, VFCUR, &
                      VFITM   , VFCI , VFZO ,VFCO2TYP, VFLDEPTH 
                       
IMPLICIT NONE

TYPE CLIMATE_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCLAKE   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTVL     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTVH     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PALB     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PSOTY    => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCVL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCVH     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCUR     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLSM     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCI      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PZO      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCO2TYP  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLDEPTH  => NULL()
CONTAINS
  PROCEDURE :: INIT  => CLIMATE_TYPE_INIT
  PROCEDURE :: FINAL => CLIMATE_TYPE_FINAL
END TYPE CLIMATE_TYPE

CONTAINS

 SUBROUTINE CLIMATE_TYPE_INIT(SELF)
    CLASS(CLIMATE_TYPE) :: SELF

    SELF%PCLAKE =>VFCLAKEF
    SELF%PTVL   =>VFTVL
    SELF%PTVH   =>VFTVH
    SELF%PALB   =>VDALB
    SELF%PSOTY  =>VFSOTY
    SELF%PCVL   =>VFCVL
    SELF%PCVH   =>VFCVH
    SELF%PCUR   =>VFCUR
    SELF%PLSM   =>VFITM
    SELF%PCI    =>VFCI
    SELF%PZO    =>VFZO
    SELF%PCO2TYP=>VFCO2TYP
    SELF%PLDEPTH=>VFLDEPTH
 END SUBROUTINE CLIMATE_TYPE_INIT

 SUBROUTINE CLIMATE_TYPE_FINAL(SELF)
    CLASS(CLIMATE_TYPE) :: SELF

    NULLIFY(SELF%PCLAKE)
    NULLIFY(SELF%PTVL)
    NULLIFY(SELF%PTVH)
    NULLIFY(SELF%PALB)
    NULLIFY(SELF%PSOTY)
    NULLIFY(SELF%PCVL)
    NULLIFY(SELF%PCVH)
    NULLIFY(SELF%PCUR)
    NULLIFY(SELF%PLSM)
    NULLIFY(SELF%PCI)
    NULLIFY(SELF%PZO)
    NULLIFY(SELF%PCO2TYP)
    NULLIFY(SELF%PLDEPTH)
 END SUBROUTINE CLIMATE_TYPE_FINAL

END MODULE ECLAND_CLIMATE_TYPE_MOD
