MODULE ECLAND_INTERNAL_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
!USE FIELD_MODULE
!USE FIELD_FACTORY_MODULE
!USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY
USE YOMGPD1S , ONLY : VFDO, VFHO, VFLDEPTH, GPD_SDP2, GPD_SDP3

IMPLICIT NONE

TYPE INTERNAL_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PDO
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PHO
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PLDEPTH
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSSDP2 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PSSDP3



!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_PCAPE, F_PPDEPL, F_PCBASE, F_PCBASEA, F_PCTOPC, F_P0DEGL, F_PM10DEGL, F_PVISIH, F_PVDISCU, F_PVDIS, &
!  CLASS(FIELD_3RB), POINTER :: F_PCONVIND, F_PZTWETB, F_PQSAT, F_PZTENQ, F_PMFUDE_RATE, F_PMFDDE_RATE, F_PKH_VDF, &
!   & F_PCOVPTOT, F_PMFU, F_PMFD, F_ZLUDE, F_ZLU, F_ZLRAIN, F_PKM_VDF, F_ZRI, F_ZCAPE, F_PCIN
!  CLASS (FIELD_4RB), POINTER :: F_ZLUDELI, F_ZSNDE, F_PRSUD
!  CLASS (FIELD_2IM), POINTER :: F_ITYPE, F_ICBOT, F_ICTOP, F_IPBLTYPE, F_ICBOT_LIG, F_ICTOP_LIG
!
CONTAINS
  PROCEDURE :: INIT => INTERNAL_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => INTERNAL_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => INTERNAL_TYPE_FINAL
END TYPE INTERNAL_TYPE




CONTAINS
!
 SUBROUTINE INTERNAL_TYPE_INIT(SELF)
    CLASS(INTERNAL_TYPE) :: SELF
    SELF%PDO=>VFDO
    SELF%PHO=>VFHO
    SELF%PLDEPTH=>VFLDEPTH
    SELF%PSSDP2 => GPD_SDP2(:,:,:)
    SELF%PSSDP3 => GPD_SDP3(:,:,:,:)

!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_PCAPE      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!
 END SUBROUTINE INTERNAL_TYPE_INIT
!
!  SUBROUTINE INTERNAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(INTERNAL_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%PCAPE => SELF%F_PCAPE%GET_VIEW(BLOCK_INDEX)
!        
!  END SUBROUTINE INTERNAL_TYPE_UPDATE_VIEW
!
  SUBROUTINE INTERNAL_TYPE_FINAL(SELF)
    CLASS(INTERNAL_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_PCAPE)
  END SUBROUTINE INTERNAL_TYPE_FINAL
!
!
END MODULE ECLAND_INTERNAL_TYPE_MOD
