MODULE ECLAND_SURF_LOCAL_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMCDH1S ,                 ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS
USE YOMGP1S0 ,                 ONLY : WRENU0, FSNNU0, RSNNU0, WSNNU0
USE YOMGPD1S , ONLY :  VDANDAYVT,VDANFMVT


USE PTRGP1S  , ONLY : MTSLNU  ,MQLINU  ,MFSNNU,         &
     &                MTSNNU  ,MASNNU  ,MWSNNU, MRSNNU, &
     &                MTRENU  ,MWRENU  ,MTILNU,         &
     &                MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &                MHLICENU,MHLMLNU ,                &           ! FLAKE
     &                MUONU   ,MVONU   ,MTONU   ,MSONU, &           !KPP
     &                MLAINU  ,MBSTRNU ,MBSTR2NU

IMPLICIT NONE

PRIVATE


TYPE, PUBLIC :: SURF_AND_MORE_LOCAL_TYPE
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PLAILI  => NULL() !ZLAILI  ! Arrays for interactive LAI (CITESSEL option)
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PLAIHI  => NULL() !ZLAIHI  ! Arrays for interactive LAI (CITESSEL option)
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZLAIL   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZLAIH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PWL     => NULL() !ZWLM1M
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PZIDLWV => NULL()  
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PSNS    => NULL() !ZSNM1M  ! KLON,KLEVSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PRSN    => NULL()!ZRSNM1M ! KLON,KLEVSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PWSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZTHKICE => NULL()! sea ice
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZWLMX   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZCSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZCVT    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZLAIVT  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZKH     => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZEXDIAG => NULL()
   ! Longwave surface spectral emissivity in two or more bands,
   ! dimensioned (KLON,NLWEMISS); note that ZEMIR and ZEMIW point to
   ! the first two columns of this matrix:
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZSPECTRALEMISS => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZEVAPSNW => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZFRTI    => NULL()! KLON,KTILES
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBTI   => NULL()! KLON,KTILES
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZFRSOTI  => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PSLRFLTI => NULL()! ZAHFTRTI
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBD    => NULL()! KLON,NTSW
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBP    => NULL()! KLON,NTSW
   !  CTESSEL: Carbon model
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PANDAYVT => NULL() !ZANDAYVT
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PANFMVT  => NULL()  !ZANFMVT

CONTAINS
  PROCEDURE :: INIT  => SURF_AND_MORE_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_LOCAL_TYPE_FINAL
END TYPE SURF_AND_MORE_LOCAL_TYPE

TYPE, PUBLIC :: DDH_SURF_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTLS   => NULL() ! Diagnostic array for tiles (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTSS   => NULL() ! Diagnostic array for snow T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTTS   => NULL() ! Diagnostic array for soil T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTIS   => NULL() ! Diagnostic array for ice T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHCO2S  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHBVOCS => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHBIOS  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHVEGS  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHSSS   => NULL() ! Diagnostic array for snow mass (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PDHIIS   => NULL() ! Diagnostic array for interception layer (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHWLS   => NULL() ! Diagnostic array for soil water (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: PDHFSS   => NULL()

CONTAINS
  PROCEDURE :: INIT  => DDH_SURF_TYPE_INIT
  PROCEDURE :: FINAL => DDH_SURF_TYPE_FINAL
END TYPE DDH_SURF_TYPE

CONTAINS

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT(SELF,NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NBLOCKS, NTSW,NTILES, NLWEMISS,NVHILO 

    SELF%PWL=>WRENU0
    SELF%PSNS=>FSNNU0
    SELF%PRSN=>RSNNU0
    SELF%PWSN=>WSNNU0
    SELF%PANDAYVT=>VDANDAYVT
    SELF%PANFMVT=>VDANFMVT
    ALLOCATE(SELF%PLAIHI(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PLAILI(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAIL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAIH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PZIDLWV(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZTHKICE(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZWLMX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCSN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCVT(NPROMA,NVHILO,NBLOCKS))
    ALLOCATE(SELF%ZLAIVT(NPROMA,NVHILO,NBLOCKS))
    ALLOCATE(SELF%ZKH(NPROMA,NLEV,NBLOCKS))
    ALLOCATE(SELF%ZEXDIAG(NPROMA,12,NBLOCKS))
    ALLOCATE(SELF%ZSPECTRALEMISS(NPROMA,NLWEMISS,NBLOCKS))
    ALLOCATE(SELF%ZEVAPSNW(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZFRTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%ZALBTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%ZFRSOTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%PSLRFLTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%ZALBD(NPROMA,NTSW,NBLOCKS))
    ALLOCATE(SELF%ZALBP(NPROMA,NTSW,NBLOCKS))
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF

    NULLIFY(SELF%PWL)
    NULLIFY(SELF%PSNS)
    NULLIFY(SELF%PRSN)
    NULLIFY(SELF%PWSN)
    NULLIFY(SELF%PANDAYVT)
    NULLIFY(SELF%PANFMVT)

    DEALLOCATE(SELF%PLAIHI)
    DEALLOCATE(SELF%PLAILI)
    DEALLOCATE(SELF%ZLAIL)
    DEALLOCATE(SELF%ZLAIH)
    DEALLOCATE(SELF%PZIDLWV)
    DEALLOCATE(SELF%ZTHKICE)
    DEALLOCATE(SELF%ZWLMX)
    DEALLOCATE(SELF%ZCSN)
    DEALLOCATE(SELF%ZCVT)
    DEALLOCATE(SELF%ZLAIVT)
    DEALLOCATE(SELF%ZKH)
    DEALLOCATE(SELF%ZEXDIAG)
    DEALLOCATE(SELF%ZSPECTRALEMISS)
    DEALLOCATE(SELF%ZEVAPSNW)
    DEALLOCATE(SELF%ZFRTI)
    DEALLOCATE(SELF%ZALBTI)
    DEALLOCATE(SELF%ZFRSOTI)
    DEALLOCATE(SELF%PSLRFLTI)
    DEALLOCATE(SELF%ZALBD)
    DEALLOCATE(SELF%ZALBP)

    NULLIFY(SELF%PLAIHI)
    NULLIFY(SELF%PLAILI)
    NULLIFY(SELF%ZLAIL)
    NULLIFY(SELF%ZLAIH)
    NULLIFY(SELF%PZIDLWV)
    NULLIFY(SELF%ZTHKICE)
    NULLIFY(SELF%ZWLMX)
    NULLIFY(SELF%ZCSN)
    NULLIFY(SELF%ZCVT)
    NULLIFY(SELF%ZLAIVT)
    NULLIFY(SELF%ZKH)
    NULLIFY(SELF%ZEXDIAG)
    NULLIFY(SELF%ZSPECTRALEMISS)
    NULLIFY(SELF%ZEVAPSNW)
    NULLIFY(SELF%ZFRTI)
    NULLIFY(SELF%ZALBTI)
    NULLIFY(SELF%ZFRSOTI)
    NULLIFY(SELF%PSLRFLTI)
    NULLIFY(SELF%ZALBD)
    NULLIFY(SELF%ZALBP)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL

  SUBROUTINE DDH_SURF_TYPE_INIT(SELF, NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO

    ALLOCATE( SELF%PDHTLS(NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS))
    ALLOCATE( SELF%PDHTSS(NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS))
    ALLOCATE( SELF%PDHSSS(NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS))
    ALLOCATE( SELF%PDHTTS(NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS))
    ALLOCATE( SELF%PDHWLS(NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS))
    ALLOCATE( SELF%PDHTIS(NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS))
    ALLOCATE( SELF%PDHIIS(NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS))
    ALLOCATE( SELF%PDHCO2S(NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS))
    ALLOCATE( SELF%PDHBIOS(NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS))
    ALLOCATE( SELF%PDHBVOCS(NPROMA,NVHILO,NDHVBVOCS,NBLOCKS))
    ALLOCATE( SELF%PDHVEGS(NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS))

    SELF%PDHTTS(1:NPROMA,1:NCSS,1:NDHVTTS+NDHFTTS,1:NBLOCKS)=0._JPRB
    SELF%PDHVEGS(1:NPROMA,1:NVHILO,1:NDHVVEGS+NDHFVEGS,1:NBLOCKS)=0._JPRB
  END SUBROUTINE DDH_SURF_TYPE_INIT

  SUBROUTINE DDH_SURF_TYPE_FINAL(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF

    DEALLOCATE( SELF%PDHTLS)
    DEALLOCATE( SELF%PDHTSS)
    DEALLOCATE( SELF%PDHSSS)
    DEALLOCATE( SELF%PDHTTS)
    DEALLOCATE( SELF%PDHWLS)
    DEALLOCATE( SELF%PDHTIS)
    DEALLOCATE( SELF%PDHIIS)
    DEALLOCATE( SELF%PDHCO2S)
    DEALLOCATE( SELF%PDHBIOS)
    DEALLOCATE( SELF%PDHBVOCS)
    DEALLOCATE( SELF%PDHVEGS)

    NULLIFY( SELF%PDHTLS)
    NULLIFY( SELF%PDHTSS)
    NULLIFY( SELF%PDHSSS)
    NULLIFY( SELF%PDHTTS)
    NULLIFY( SELF%PDHWLS)
    NULLIFY( SELF%PDHTIS)
    NULLIFY( SELF%PDHIIS)
    NULLIFY( SELF%PDHCO2S)
    NULLIFY( SELF%PDHBIOS)
    NULLIFY( SELF%PDHBVOCS)
    NULLIFY( SELF%PDHVEGS)
  END SUBROUTINE DDH_SURF_TYPE_FINAL

END MODULE ECLAND_SURF_LOCAL_TYPE_MOD
