MODULE ECLAND_SURFACE_TYPE_MOD

USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMGP1S0 ,                 ONLY : WRENU0, FSNNU0, RSNNU0, WSNNU0
USE YOMGF1S  ,                 ONLY : FSSRD, FSTRD
USE YOMCDH1S ,                 ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS

USE YOMGPD1S , ONLY : VFISOP_EP, &
     & VFFWET   , VFAVGPAR,VFSDOR   ,VFCIL,VDIEWSSTL,VDINSSSTL,VDISSHFTL,VDIETL   ,VDTSKTL,&
     & VFCLAKEF   ,VFALBF   ,VFCVL    ,VFCVH    ,VFCUR    ,VFTVL    ,VFTVH    , &
     & VFCO2TYP, VFLAIL   ,VFLAIH   ,VFSOTY   ,VFCI     , VFITM    ,VFZO     , &
     & VFHO     ,VFHO_INV ,VFDO     ,VFOCDEPTH, &
     & VFADVT ,VFADVS  ,VFTRI0   ,VFTRI1   ,VFSWDK_SAVE, VDALB,&
     & VDRESPBSTR,VDRESPBSTR2,VDBIOMASS_LAST,VDBLOSSVT,VDBGAINVT, VDANDAYVT,VDANFMVT 

USE YOMGP1S0 , ONLY : BSTRNU0,BSTR2NU0,ASNNU0   ,TSNNU0,TSLNU0   ,TRENU0   ,QLINU0   ,&
     & TILNU0,TLICENU0,TLMNWNU0,TLWMLNU0,TLBOTNU0,TLSFNU0,HLICENU0,HLMLNU0 ,&
     & UONU0, VONU0, TONU0, SONU0

USE PTRGP1S  , ONLY : MTSLNU  ,MQLINU  ,MFSNNU,         &
     &                MTSNNU  ,MASNNU  ,MWSNNU, MRSNNU, &
     &                MTRENU  ,MWRENU  ,MTILNU,         &
     &                MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &                MHLICENU,MHLMLNU ,                &           ! FLAKE
     &                MUONU   ,MVONU   ,MTONU   ,MSONU, &           !KPP
     &                MLAINU  ,MBSTRNU ,MBSTR2NU

USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2IM, FIELD_3IM
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: SURFACE_PROGNOSTIC 

  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PHLICE => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLICE => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTL    => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLSF  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLMNW => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLWML => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PSST   => NULL() 
  CLASS(FIELD_2RB), POINTER :: F_PSST   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUO0   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUOC   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PUOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVO0   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVOC   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PVOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: ZWS1   => NULL() 
  CLASS(FIELD_2RB), POINTER :: F_ZWS1   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLBOT => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PASN   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSN   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PWSA   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSA   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTIA   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PHLML  => NULL() 

CONTAINS
  PROCEDURE :: UPDATE_VIEW => SURFACE_PROGNOSTIC_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => SURFACE_PROGNOSTIC_SYNC_HOST

END TYPE SURFACE_PROGNOSTIC 

TYPE, PUBLIC :: SURFACE_DIAGNOSTIC

  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCLAKE   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTVL     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTVH     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PALB     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PSOTY    => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCVL     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCVH     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCUR     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLSM     => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCI      => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PZO      => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: POCDEPTH => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PHO_INV  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PEVAPTIU => NULL() 
  CLASS(FIELD_3RB), POINTER :: F_PEVAPTIU => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU10M    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PU10M    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PV10M    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PV10M    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PT2M     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PT2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PD2M     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PD2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ2M     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PQ2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PALBF    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PALBICEF => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PALBICEF => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLAILC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLAIHC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PCO2TYP  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: ZALCOEFF => NULL()
  CLASS(FIELD_3RB), POINTER :: F_ZALCOEFF => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PADVT    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PADVS    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTRI0    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTRI1    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: ZAVGPARC => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZAVGPARC => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PTAUOCX  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTAUOCX  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PTAUOCY  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTAUOCY  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: POTKE    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_POTKE    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSWDK_SAVE => NULL()

CONTAINS
  PROCEDURE :: UPDATE_VIEW => SURFACE_DIAGNOSTIC_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => SURFACE_DIAGNOSTIC_SYNC_HOST

END TYPE SURFACE_DIAGNOSTIC

TYPE, PUBLIC :: SURF_AND_MORE_TYPE

   REAL(KIND=JPRB),DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZGPE => NULL()
   CLASS(FIELD_3RB), POINTER :: F_ZGPE => NULL()

   TYPE(SURFACE_PROGNOSTIC) :: GSP
   TYPE(SURFACE_DIAGNOSTIC) :: GSD
  ! T star tiles
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PUSTRTI => NULL()  ! E-W (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PVSTRTI => NULL() ! N-S (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PAHFSTI => NULL() ! (INSTANTANEOUS) SURFACE SENSIBLE HEAT FLUX FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PEVAPTI => NULL() ! (INSTANTANEOUS) EVAPORATION FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTSKTI  => NULL() ! SKIN TEMPERATURE FOR EACH TILE
  ! other 
   REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: ZEMIS   => NULL() !PEMIS      ! MODEL SURFACE LONGWAVE EMISSIVITY.
   CLASS(FIELD_2RB), POINTER :: F_ZEMIS   => NULL()
  !  Tendencies from surface scheme
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PSNSE1  => NULL() ! OF MULTI-LAYER SNOW MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PRSNE1  => NULL() ! OF MULTI-LAYER SNOW DENSITY
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTSNE1  => NULL() ! OF MULTI-LAYER SNOW TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PWSNE1  => NULL() ! OF MULTI-LAYER SNOW LIQUID WATER MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER :: PASNE1  => NULL() ! OF SNOW ALBEDO : only the top layer is used
   REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER :: PWLE1   => NULL() ! OF SKIN RESERVOIR WATER CONTENT
   REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER :: PTLE1   => NULL() ! OF SKIN TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PLAIE1  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PBSTRE1 => NULL() 
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PBSTR2E1 => NULL() 
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTSAE1  => NULL() ! OF MULTI-LAYER SOIL TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PWSAE1  => NULL() ! OF MULTI-LAYER SOIL WETNESS
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTIAE1  => NULL() ! OF MULTI-LAYER SEA ICE TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PUOE1   => NULL() ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PVOE1   => NULL() ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTOE1   => NULL() ! TEMPERATURE TENDENCY OF OCEAN MIXED LAYER MODEL  K/S
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PSOE1   => NULL() ! SALINITY TENDENCY OF OCEAN MIXED LAYER MODEL  psu/S
   REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: PSDOR   => NULL() !PHSTD    ! STANDARD DEVIATION OF SUBGRID OROGRAPHY
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ITVH    => NULL() 
  CLASS(FIELD_2IM), POINTER :: F_ITVH    => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ITVL    => NULL()
  CLASS(FIELD_2IM), POINTER :: F_ITVL    => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ICO2TYP => NULL()
  CLASS(FIELD_2IM), POINTER :: F_ICO2TYP => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ISOTY   => NULL()! to store vegetation indices and soil type index
  CLASS(FIELD_2IM), POINTER :: F_ISOTY   => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), POINTER :: IVEG    => NULL()
  CLASS(FIELD_3IM), POINTER :: F_IVEG    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCVL    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCVL    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCVH    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCVH    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCUR    => NULL()  ! to store vegetation covers
  CLASS(FIELD_2RB), POINTER :: F_ZCUR    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PCIL    => NULL()  ! to store land-ice fraction
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PPHIOC           => NULL() 
  CLASS(FIELD_2RB), POINTER :: F_PPHIOC  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PRESPBSTR        => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PRESPBSTR2       => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBLOSSVT         => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBGAINVT         => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBIOMASS_LAST    => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBIOMASSTR_LAST  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBIOMASSTR2_LAST => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PRSOIL_STR       => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PRSOIL_STR => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PCO2FLUX => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCO2FLUX => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PCH4FLUX => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCH4FLUX => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PUSTOKES => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PUSTOKES => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PVSTOKES => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PVSTOKES => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PWSEMEAN => NULL()!PEMEAN
  CLASS(FIELD_2RB), POINTER :: F_PWSEMEAN => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PWSFMEAN => NULL()!PFMEAN
  CLASS(FIELD_2RB), POINTER :: F_PWSFMEAN => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PDIFM    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDIFM   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PDIFT    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDIFT   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PDIFS    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDIFS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PUSTRC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PUSTRC  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PVSTRC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PVSTRC  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PRECO    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PRECO   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PAN      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PAN     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PAG      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PAG     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PRD      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PRD     => NULL()
  REAL(KIND=JPRB), DIMENSION(:),        POINTER :: PCO2TYP  => NULL()         ! to store co2 photosynthesis type for low vegetation cover
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PLAIL    => NULL()    ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PLAIH    => NULL()    ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PLAI     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PLAI    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBIOM    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBIOM   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBLOSS   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBLOSS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBGAIN   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBGAIN  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBIOMSTR => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBIOMSTR => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBIOMSTR2=> NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBIOMSTR2 => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAILP   => NULL() !PLAILP, PLAIHP   ! to store variable LAI previous time
  CLASS(FIELD_2RB), POINTER :: F_ZLAILP  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAIHP   => NULL()!PLAILP, PLAIHP   ! to store variable LAI previous time
  CLASS(FIELD_2RB), POINTER :: F_ZLAIHP  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAIL    => NULL()  ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAIH    => NULL()   ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCHAR    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCHAR   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCHARHQ  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCHARHQ => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZTE      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZTE     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZQE      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZQE     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZVOM     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZVOM    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZVOL     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZVOL    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: ZTENC    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_ZTENC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZUCURR   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZUCURR  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZVCURR   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZVCURR  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZAVGPAR  => NULL() !PAVGPAR          ! Average PAR for BVOC emis module
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PISOP_EP => NULL()        ! Isoprene emission potential
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PFWET    => NULL()        ! to store wetland fraction
  REAL(KIND=JPRB), DIMENSION(:)  ,      POINTER :: PEVAPMU  => NULL()  ! potential evaporation
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLICEE1 => NULL()      ! tendency of lake ice temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLMNWE1 => NULL()      ! tendency of lake totat layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLWMLE1 => NULL()      ! tendency of lake mixed layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLBOTE1 => NULL()      ! tendency of lake bottom layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLSFE1  => NULL()      ! tendency of lake shape factor - 
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PHLICEE1 => NULL()      ! tendency of lake ice depth m
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PHLMLE1  => NULL()      ! tendency of lake mixed layer depth m/s
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PSRSOD   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PSRTHD   => NULL()

CONTAINS
  PROCEDURE :: INIT  => SURF_AND_MORE_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => SURF_AND_MORE_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => SURF_AND_MORE_TYPE_SYNC_HOST

END TYPE SURF_AND_MORE_TYPE

TYPE, PUBLIC :: SURF_AND_MORE_LOCAL_TYPE
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PLAILI  => NULL() !ZLAILI  ! Arrays for interactive LAI (CITESSEL option)
    CLASS(FIELD_2RB), POINTER :: F_PLAILI  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PLAIHI  => NULL() !ZLAIHI  ! Arrays for interactive LAI (CITESSEL option)
    CLASS(FIELD_2RB), POINTER :: F_PLAIHI  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZLAIL   => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZLAIL   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZLAIH   => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZLAIH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PWL     => NULL() !ZWLM1M
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PZIDLWV => NULL()  
    CLASS(FIELD_2RB), POINTER :: F_PZIDLWV => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PSNS    => NULL() !ZSNM1M  ! KLON,KLEVSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PRSN    => NULL()!ZRSNM1M ! KLON,KLEVSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PWSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZTHKICE => NULL()! sea ice
    CLASS(FIELD_2RB), POINTER :: F_ZTHKICE => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZWLMX   => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZWLMX   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZCSN    => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZCSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZCVT    => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZCVT    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZLAIVT  => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZLAIVT  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZKH     => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZKH     => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZEXDIAG => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZEXDIAG => NULL()
   ! Longwave surface spectral emissivity in two or more bands,
   ! dimensioned (KLON,NLWEMISS); note that ZEMIR and ZEMIW point to
   ! the first two columns of this matrix:
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZSPECTRALEMISS => NULL()
     CLASS(FIELD_3RB), POINTER :: F_ZSPECTRALEMISS => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZEVAPSNW => NULL()
     CLASS(FIELD_2RB), POINTER :: F_ZEVAPSNW => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZFRTI    => NULL()! KLON,KTILES
     CLASS(FIELD_3RB), POINTER :: F_ZFRTI    => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBTI   => NULL()! KLON,KTILES
     CLASS(FIELD_3RB), POINTER :: F_ZALBTI   => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZFRSOTI  => NULL()
     CLASS(FIELD_3RB), POINTER :: F_ZFRSOTI  => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PSLRFLTI => NULL()! ZAHFTRTI
     CLASS(FIELD_3RB), POINTER :: F_PSLRFLTI => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBD    => NULL()! KLON,NTSW
     CLASS(FIELD_3RB), POINTER :: F_ZALBD    => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBP    => NULL()! KLON,NTSW
     CLASS(FIELD_3RB), POINTER :: F_ZALBP    => NULL()
   !  CTESSEL: Carbon model
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PANDAYVT => NULL() !ZANDAYVT
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PANFMVT  => NULL()  !ZANFMVT

CONTAINS
  PROCEDURE :: INIT  => SURF_AND_MORE_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_LOCAL_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => SURF_AND_MORE_LOCAL_TYPE_SYNC_HOST
END TYPE SURF_AND_MORE_LOCAL_TYPE

TYPE, PUBLIC :: DDH_SURF_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTLS   => NULL() ! Diagnostic array for tiles (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTLS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTSS   => NULL() ! Diagnostic array for snow T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTTS   => NULL() ! Diagnostic array for soil T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTTS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTIS   => NULL() ! Diagnostic array for ice T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTIS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHCO2S  => NULL() 
  CLASS(FIELD_4RB), POINTER :: F_PDHCO2S  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHBVOCS => NULL() 
  CLASS(FIELD_4RB), POINTER :: F_PDHBVOCS => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHBIOS  => NULL() 
  CLASS(FIELD_4RB), POINTER :: F_PDHBIOS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHVEGS  => NULL() 
  CLASS(FIELD_4RB), POINTER :: F_PDHVEGS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHSSS   => NULL() ! Diagnostic array for snow mass (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHSSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PDHIIS   => NULL() ! Diagnostic array for interception layer (see module yomcdh)
  CLASS(FIELD_3RB), POINTER :: F_PDHIIS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHWLS   => NULL() ! Diagnostic array for soil water (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHWLS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: PDHFSS   => NULL()

CONTAINS
  PROCEDURE :: INIT  => DDH_SURF_TYPE_INIT
  PROCEDURE :: FINAL => DDH_SURF_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => DDH_SURF_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => DDH_SURF_TYPE_SYNC_HOST
END TYPE DDH_SURF_TYPE

CONTAINS

  SUBROUTINE SURF_AND_MORE_TYPE_INIT(SELF, NPROMA, NGPP,  NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NGPP, NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES,  NBLOCKS 

    SELF%PISOP_EP=>VFISOP_EP
    SELF%PFWET=>VFFWET
    SELF%ZAVGPAR=>VFAVGPAR
    SELF%PSDOR=>VFSDOR
    SELF%PCIL=>VFCIL
    SELF%PUSTRTI=>VDIEWSSTL
    SELF%PVSTRTI=>VDINSSSTL
    SELF%PAHFSTI=>VDISSHFTL
    SELF%PEVAPTI=>VDIETL
    SELF%PTSKTI=>VDTSKTL
    SELF%PRESPBSTR=>VDRESPBSTR
    SELF%PRESPBSTR2=>VDRESPBSTR2
    SELF%PBIOMASS_LAST=>VDBIOMASS_LAST
    SELF%PBIOMASSTR_LAST=>BSTRNU0
    SELF%PBIOMASSTR2_LAST=>BSTR2NU0
    SELF%PBLOSSVT=>VDBLOSSVT
    SELF%PBGAINVT=>VDBGAINVT
    SELF%GSP%PASN=>ASNNU0
    SELF%GSP%PTSN=>TSNNU0
    SELF%GSP%PTSA=>TSLNU0
    SELF%GSP%PTL=>TRENU0
    SELF%GSP%PWSA=>QLINU0
    SELF%GSP%PTIA=>TILNU0
    SELF%GSP%PTLICE=>TLICENU0
    SELF%GSP%PTLMNW=>TLMNWNU0
    SELF%GSP%PTLWML=>TLWMLNU0
    SELF%GSP%PTLBOT=>TLBOTNU0
    SELF%GSP%PTLSF=>TLSFNU0
    SELF%GSP%PHLICE=>HLICENU0
    SELF%GSP%PHLML=>HLMLNU0
    SELF%GSP%PUO0=>UONU0
    SELF%GSP%PVO0=>VONU0
    SELF%GSP%PTO0=>TONU0
    SELF%GSP%PSO0=>SONU0
    SELF%GSD%PCLAKE=>VFCLAKEF
    SELF%GSD%PALBF=>VFALBF
    SELF%GSD%PCVL=>VFCVL
    SELF%GSD%PCVH=>VFCVH
    SELF%GSD%PCUR=>VFCUR
    SELF%GSD%PTVL=>VFTVL
    SELF%GSD%PCO2TYP=>VFCO2TYP
    SELF%GSD%PTVH=>VFTVH
    SELF%GSD%PLAILC=>VFLAIL
    SELF%GSD%PLAIHC=>VFLAIH
    SELF%GSD%PSOTY=>VFSOTY
    SELF%GSD%PCI=>VFCI
    SELF%GSD%PLSM=>VFITM
    SELF%GSD%PZO=>VFZO
    SELF%GSD%PHO_INV=>VFHO_INV
    SELF%GSD%POCDEPTH=>VFOCDEPTH
    SELF%GSD%PADVT=>VFADVT
    SELF%GSD%PADVS=>VFADVS
    SELF%GSD%PTRI0=>VFTRI0
    SELF%GSD%PTRI1=>VFTRI1
    SELF%GSD%PSWDK_SAVE=>VFSWDK_SAVE
    SELF%GSD%PALB=>VDALB
    SELF%PSRSOD=>FSSRD 
    SELF%PSRTHD=>FSTRD


    CALL FIELD_NEW(SELF%F_PUSTRC, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PVSTRC, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCVL, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCVH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCUR, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PAN, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PAG, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PRD, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PRSOIL_STR, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PRECO, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PCO2FLUX, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PCH4FLUX, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PLAI, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZEMIS, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAILP, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIHP, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCHAR, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCHARHQ, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZUCURR, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZVCURR, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PUSTOKES, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PVSTOKES, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PTAUOCX, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PTAUOCY, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PPHIOC, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PWSEMEAN, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PWSFMEAN, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PBIOM, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PBLOSS, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PBGAIN, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PBIOMSTR, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PBIOMSTR2, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDIFM, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT=.TRUE.)     !KPP
    CALL FIELD_NEW(SELF%F_PDIFT, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT=.TRUE.)     !KPP
    CALL FIELD_NEW(SELF%F_PDIFS, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT=.TRUE.)

    CALL FIELD_NEW(SELF%F_ZTE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZQE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZVOM, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZVOL, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZTENC, UBOUNDS=[NPROMA,NTRAC,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ITVL, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ITVH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ISOTY, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ICO2TYP, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_IVEG, UBOUNDS=[NPROMA,NVHILO,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSP%F_PUOC, UBOUNDS=[NPROMA,NCOM+1,NBLOCKS], PERSISTENT=.TRUE.)                  !KPP
    CALL FIELD_NEW(SELF%GSP%F_PVOC, UBOUNDS=[NPROMA,NCOM+1,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSP%F_PSST, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSP%F_ZWS1, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PEVAPTIU, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PU10M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PV10M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PT2M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PD2M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PQ2M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_POTKE, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_ZALCOEFF, UBOUNDS=[NPROMA,6,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_PALBICEF, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%GSD%F_ZAVGPARC, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)

    CALL FIELD_NEW(SELF%F_ZGPE, UBOUNDS=[NPROMA,NGPP,NBLOCKS], PERSISTENT=.TRUE.)

    SELF%PSNSE1 => SELF%ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:)
    SELF%PTSNE1 => SELF%ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:)
    SELF%PWSNE1 => SELF%ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:)
    SELF%PRSNE1 => SELF%ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:)
    SELF%PASNE1 => SELF%ZGPE(:,MASNNU,:)
    SELF%PTLE1  => SELF%ZGPE(:,MTRENU,:)
    SELF%PWLE1  => SELF%ZGPE(:,MWRENU,:)
    SELF%PTIAE1 => SELF%ZGPE(:,MTILNU:MTILNU+NCSS-1,:)
    SELF%PWSAE1 => SELF%ZGPE(:,MQLINU:MQLINU+NCSS-1,:)
    SELF%PTSAE1 => SELF%ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)
    
    SELF%PTLICEE1 => SELF%ZGPE(:,MTLICENU,:)
    SELF%PTLMNWE1 => SELF%ZGPE(:,MTLMNWNU,:)
    SELF%PTLWMLE1 => SELF%ZGPE(:,MTLWMLNU,:)
    SELF%PTLBOTE1 => SELF%ZGPE(:,MTLBOTNU,:)
    SELF%PTLSFE1  => SELF%ZGPE(:,MTLSFNU,:)
    SELF%PHLICEE1 => SELF%ZGPE(:,MHLICENU,:)
    SELF%PHLMLE1  => SELF%ZGPE(:,MHLMLNU,:)
    
    SELF%PUOE1 => SELF%ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  !KPP
    SELF%PVOE1 => SELF%ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  !KPP
    SELF%PTOE1 => SELF%ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  !KPP
    SELF%PSOE1 => SELF%ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  !KPP
    
    SELF%PLAIE1 => SELF%ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)
    SELF%PBSTRE1 => SELF%ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)
    SELF%PBSTR2E1 => SELF%ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:)

  END SUBROUTINE SURF_AND_MORE_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_TYPE) :: SELF

    NULLIFY(SELF%PISOP_EP)
    NULLIFY(SELF%PFWET)
    NULLIFY(SELF%ZAVGPAR)
    NULLIFY(SELF%PSDOR)
    NULLIFY(SELF%PCIL)
    NULLIFY(SELF%PUSTRTI)
    NULLIFY(SELF%PVSTRTI)
    NULLIFY(SELF%PAHFSTI)
    NULLIFY(SELF%PEVAPTI)
    NULLIFY(SELF%PTSKTI)
    NULLIFY(SELF%PRESPBSTR)
    NULLIFY(SELF%PRESPBSTR2)
    NULLIFY(SELF%PBIOMASS_LAST)
    NULLIFY(SELF%PBIOMASSTR_LAST)
    NULLIFY(SELF%PBIOMASSTR2_LAST)
    NULLIFY(SELF%PBLOSSVT)
    NULLIFY(SELF%PBGAINVT)
    NULLIFY(SELF%GSP%PASN)
    NULLIFY(SELF%GSP%PTSN)
    NULLIFY(SELF%GSP%PTSA)
    NULLIFY(SELF%GSP%PTL)
    NULLIFY(SELF%GSP%PWSA)
    NULLIFY(SELF%GSP%PTIA)
    NULLIFY(SELF%GSP%PTLICE)
    NULLIFY(SELF%GSP%PTLMNW)
    NULLIFY(SELF%GSP%PTLWML)
    NULLIFY(SELF%GSP%PTLBOT)
    NULLIFY(SELF%GSP%PTLSF)
    NULLIFY(SELF%GSP%PHLICE)
    NULLIFY(SELF%GSP%PHLML)
    NULLIFY(SELF%GSP%PUO0)
    NULLIFY(SELF%GSP%PVO0)
    NULLIFY(SELF%GSP%PTO0)
    NULLIFY(SELF%GSP%PSO0)
    NULLIFY(SELF%GSD%PCLAKE)
    NULLIFY(SELF%GSD%PALBF)
    NULLIFY(SELF%GSD%PCVL)
    NULLIFY(SELF%GSD%PCVH)
    NULLIFY(SELF%GSD%PCUR)
    NULLIFY(SELF%GSD%PTVL)
    NULLIFY(SELF%GSD%PCO2TYP)
    NULLIFY(SELF%GSD%PTVH)
    NULLIFY(SELF%GSD%PLAILC)
    NULLIFY(SELF%GSD%PLAIHC)
    NULLIFY(SELF%GSD%PSOTY)
    NULLIFY(SELF%GSD%PCI)
    NULLIFY(SELF%GSD%PLSM)
    NULLIFY(SELF%GSD%PZO)
    NULLIFY(SELF%GSD%PHO_INV)
    NULLIFY(SELF%GSD%POCDEPTH)
    NULLIFY(SELF%GSD%PADVT)
    NULLIFY(SELF%GSD%PADVS)
    NULLIFY(SELF%GSD%PTRI0)
    NULLIFY(SELF%GSD%PTRI1)
    NULLIFY(SELF%GSD%PSWDK_SAVE)
    NULLIFY(SELF%GSD%PALB)
    NULLIFY(SELF%PSRSOD)
    NULLIFY(SELF%PSRTHD)
    NULLIFY(SELF%PSNSE1)
    NULLIFY(SELF%PTSNE1)
    NULLIFY(SELF%PWSNE1)
    NULLIFY(SELF%PRSNE1)
    NULLIFY(SELF%PASNE1)
    NULLIFY(SELF%PTLE1 )
    NULLIFY(SELF%PWLE1 )
    NULLIFY(SELF%PTIAE1)
    NULLIFY(SELF%PWSAE1)
    NULLIFY(SELF%PTSAE1)
    NULLIFY(SELF%PTLICEE1)
    NULLIFY(SELF%PTLMNWE1)
    NULLIFY(SELF%PTLWMLE1)
    NULLIFY(SELF%PTLBOTE1)
    NULLIFY(SELF%PTLSFE1 )
    NULLIFY(SELF%PHLICEE1)
    NULLIFY(SELF%PHLMLE1 )
    NULLIFY(SELF%PUOE1)
    NULLIFY(SELF%PVOE1)
    NULLIFY(SELF%PTOE1)
    NULLIFY(SELF%PSOE1)
    NULLIFY(SELF%PLAIE1)
    NULLIFY(SELF%PBSTRE1)
    NULLIFY(SELF%PBSTR2E1)

    CALL FIELD_DELETE(SELF%F_PUSTRC)
    CALL FIELD_DELETE(SELF%F_PVSTRC)
    CALL FIELD_DELETE(SELF%F_ZCVL)
    CALL FIELD_DELETE(SELF%F_ZCVH)
    CALL FIELD_DELETE(SELF%F_ZCUR)
    CALL FIELD_DELETE(SELF%F_PAN)
    CALL FIELD_DELETE(SELF%F_PAG)
    CALL FIELD_DELETE(SELF%F_PRD)
    CALL FIELD_DELETE(SELF%F_PRSOIL_STR)
    CALL FIELD_DELETE(SELF%F_PRECO)
    CALL FIELD_DELETE(SELF%F_PCO2FLUX)
    CALL FIELD_DELETE(SELF%F_PCH4FLUX)
    CALL FIELD_DELETE(SELF%F_PLAI)
    CALL FIELD_DELETE(SELF%F_ZEMIS)
    CALL FIELD_DELETE(SELF%F_ZLAILP)
    CALL FIELD_DELETE(SELF%F_ZLAIHP)
    CALL FIELD_DELETE(SELF%F_ZCHAR)
    CALL FIELD_DELETE(SELF%F_ZCHARHQ)
    CALL FIELD_DELETE(SELF%F_ZUCURR)
    CALL FIELD_DELETE(SELF%F_ZVCURR)
    CALL FIELD_DELETE(SELF%F_PUSTOKES)
    CALL FIELD_DELETE(SELF%F_PVSTOKES)
    CALL FIELD_DELETE(SELF%GSD%F_PTAUOCX)
    CALL FIELD_DELETE(SELF%GSD%F_PTAUOCY)
    CALL FIELD_DELETE(SELF%F_PPHIOC)
    CALL FIELD_DELETE(SELF%F_PWSEMEAN)
    CALL FIELD_DELETE(SELF%F_PWSFMEAN)
    CALL FIELD_DELETE(SELF%F_PBIOM)
    CALL FIELD_DELETE(SELF%F_PBLOSS)
    CALL FIELD_DELETE(SELF%F_PBGAIN)
    CALL FIELD_DELETE(SELF%F_PBIOMSTR)
    CALL FIELD_DELETE(SELF%F_PBIOMSTR2)
    CALL FIELD_DELETE(SELF%F_PDIFM)
    CALL FIELD_DELETE(SELF%F_PDIFT)
    CALL FIELD_DELETE(SELF%F_PDIFS)
    CALL FIELD_DELETE(SELF%F_ZTE)
    CALL FIELD_DELETE(SELF%F_ZQE)
    CALL FIELD_DELETE(SELF%F_ZVOM)
    CALL FIELD_DELETE(SELF%F_ZVOL)
    CALL FIELD_DELETE(SELF%F_ZTENC)
    CALL FIELD_DELETE(SELF%F_ITVL)
    CALL FIELD_DELETE(SELF%F_ITVH)
    CALL FIELD_DELETE(SELF%F_ISOTY)
    CALL FIELD_DELETE(SELF%F_ICO2TYP)
    CALL FIELD_DELETE(SELF%F_IVEG)
    CALL FIELD_DELETE(SELF%GSP%F_PUOC)
    CALL FIELD_DELETE(SELF%GSP%F_PVOC)
    CALL FIELD_DELETE(SELF%GSP%F_PSST)
    CALL FIELD_DELETE(SELF%GSP%F_ZWS1)
    CALL FIELD_DELETE(SELF%GSD%F_PEVAPTIU)
    CALL FIELD_DELETE(SELF%GSD%F_PU10M)
    CALL FIELD_DELETE(SELF%GSD%F_PV10M)
    CALL FIELD_DELETE(SELF%GSD%F_PT2M)
    CALL FIELD_DELETE(SELF%GSD%F_PD2M)
    CALL FIELD_DELETE(SELF%GSD%F_PQ2M)
    CALL FIELD_DELETE(SELF%GSD%F_POTKE)
    CALL FIELD_DELETE(SELF%GSD%F_ZALCOEFF)
    CALL FIELD_DELETE(SELF%GSD%F_PALBICEF)
    CALL FIELD_DELETE(SELF%GSD%F_ZAVGPARC)
    CALL FIELD_DELETE(SELF%F_ZGPE)

    NULLIFY(SELF%PUSTRC)
    NULLIFY(SELF%PVSTRC)
    NULLIFY(SELF%ZCVL)
    NULLIFY(SELF%ZCVH)
    NULLIFY(SELF%ZCUR)
    NULLIFY(SELF%PAN)
    NULLIFY(SELF%PAG)
    NULLIFY(SELF%PRD)
    NULLIFY(SELF%PRSOIL_STR)
    NULLIFY(SELF%PRECO)
    NULLIFY(SELF%PCO2FLUX)
    NULLIFY(SELF%PCH4FLUX)
    NULLIFY(SELF%PLAI)
    NULLIFY(SELF%ZEMIS)
    NULLIFY(SELF%ZLAILP)
    NULLIFY(SELF%ZLAIHP)
    NULLIFY(SELF%ZCHAR)
    NULLIFY(SELF%ZCHARHQ)
    NULLIFY(SELF%ZUCURR)
    NULLIFY(SELF%ZVCURR)
    NULLIFY(SELF%PUSTOKES)
    NULLIFY(SELF%PVSTOKES)
    NULLIFY(SELF%GSD%PTAUOCX)
    NULLIFY(SELF%GSD%PTAUOCY)
    NULLIFY(SELF%PPHIOC)
    NULLIFY(SELF%PWSEMEAN)
    NULLIFY(SELF%PWSFMEAN)
    NULLIFY(SELF%PBIOM)
    NULLIFY(SELF%PBLOSS)
    NULLIFY(SELF%PBGAIN)
    NULLIFY(SELF%PBIOMSTR)
    NULLIFY(SELF%PBIOMSTR2)
    NULLIFY(SELF%PDIFM)
    NULLIFY(SELF%PDIFT)
    NULLIFY(SELF%PDIFS)
    NULLIFY(SELF%ZTE)
    NULLIFY(SELF%ZQE)
    NULLIFY(SELF%ZVOM)
    NULLIFY(SELF%ZVOL)
    NULLIFY(SELF%ZTENC)
    NULLIFY(SELF%ITVL)
    NULLIFY(SELF%ITVH)
    NULLIFY(SELF%ISOTY)
    NULLIFY(SELF%ICO2TYP)
    NULLIFY(SELF%IVEG)
    NULLIFY(SELF%GSP%PUOC)
    NULLIFY(SELF%GSP%PVOC)
    NULLIFY(SELF%GSP%PSST)
    NULLIFY(SELF%GSP%ZWS1)
    NULLIFY(SELF%GSD%PEVAPTIU)
    NULLIFY(SELF%GSD%PU10M)
    NULLIFY(SELF%GSD%PV10M)
    NULLIFY(SELF%GSD%PT2M)
    NULLIFY(SELF%GSD%PD2M)
    NULLIFY(SELF%GSD%PQ2M)
    NULLIFY(SELF%GSD%POTKE)
    NULLIFY(SELF%GSD%ZALCOEFF)
    NULLIFY(SELF%GSD%PALBICEF)
    NULLIFY(SELF%GSD%ZAVGPARC)
    NULLIFY(SELF%ZGPE)
  END SUBROUTINE SURF_AND_MORE_TYPE_FINAL

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT(SELF,NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NBLOCKS, NTSW,NTILES, NLWEMISS,NVHILO 

    SELF%PWL=>WRENU0
    SELF%PSNS=>FSNNU0
    SELF%PRSN=>RSNNU0
    SELF%PWSN=>WSNNU0
    SELF%PANDAYVT=>VDANDAYVT
    SELF%PANFMVT=>VDANFMVT
    CALL FIELD_NEW(SELF%F_PLAIHI, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PLAILI, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIL, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PZIDLWV, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZTHKICE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZWLMX, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCSN, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCVT, UBOUNDS=[NPROMA,NVHILO,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIVT, UBOUNDS=[NPROMA,NVHILO,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZKH, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZEXDIAG, UBOUNDS=[NPROMA,12,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZSPECTRALEMISS, UBOUNDS=[NPROMA,NLWEMISS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZEVAPSNW, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZFRTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZALBTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZFRSOTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PSLRFLTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZALBD, UBOUNDS=[NPROMA,NTSW,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZALBP, UBOUNDS=[NPROMA,NTSW,NBLOCKS], PERSISTENT=.TRUE.)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF

    NULLIFY(SELF%PWL)
    NULLIFY(SELF%PSNS)
    NULLIFY(SELF%PRSN)
    NULLIFY(SELF%PWSN)
    NULLIFY(SELF%PANDAYVT)
    NULLIFY(SELF%PANFMVT)

    CALL FIELD_DELETE(SELF%F_PLAIHI)
    CALL FIELD_DELETE(SELF%F_PLAILI)
    CALL FIELD_DELETE(SELF%F_ZLAIL)
    CALL FIELD_DELETE(SELF%F_ZLAIH)
    CALL FIELD_DELETE(SELF%F_PZIDLWV)
    CALL FIELD_DELETE(SELF%F_ZTHKICE)
    CALL FIELD_DELETE(SELF%F_ZWLMX)
    CALL FIELD_DELETE(SELF%F_ZCSN)
    CALL FIELD_DELETE(SELF%F_ZCVT)
    CALL FIELD_DELETE(SELF%F_ZLAIVT)
    CALL FIELD_DELETE(SELF%F_ZKH)
    CALL FIELD_DELETE(SELF%F_ZEXDIAG)
    CALL FIELD_DELETE(SELF%F_ZSPECTRALEMISS)
    CALL FIELD_DELETE(SELF%F_ZEVAPSNW)
    CALL FIELD_DELETE(SELF%F_ZFRTI)
    CALL FIELD_DELETE(SELF%F_ZALBTI)
    CALL FIELD_DELETE(SELF%F_ZFRSOTI)
    CALL FIELD_DELETE(SELF%F_PSLRFLTI)
    CALL FIELD_DELETE(SELF%F_ZALBD)
    CALL FIELD_DELETE(SELF%F_ZALBP)

    NULLIFY(SELF%PLAIHI)
    NULLIFY(SELF%PLAILI)
    NULLIFY(SELF%ZLAIL)
    NULLIFY(SELF%ZLAIH)
    NULLIFY(SELF%PZIDLWV)
    NULLIFY(SELF%ZTHKICE)
    NULLIFY(SELF%ZWLMX)
    NULLIFY(SELF%ZCSN)
    NULLIFY(SELF%ZCVT)
    NULLIFY(SELF%ZLAIVT)
    NULLIFY(SELF%ZKH)
    NULLIFY(SELF%ZEXDIAG)
    NULLIFY(SELF%ZSPECTRALEMISS)
    NULLIFY(SELF%ZEVAPSNW)
    NULLIFY(SELF%ZFRTI)
    NULLIFY(SELF%ZALBTI)
    NULLIFY(SELF%ZFRSOTI)
    NULLIFY(SELF%PSLRFLTI)
    NULLIFY(SELF%ZALBD)
    NULLIFY(SELF%ZALBP)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL

  SUBROUTINE DDH_SURF_TYPE_INIT(SELF, NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO

    CALL FIELD_NEW(SELF%F_PDHTLS, UBOUNDS=[NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTSS, UBOUNDS=[NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHSSS, UBOUNDS=[NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTTS, UBOUNDS=[NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHWLS, UBOUNDS=[NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTIS, UBOUNDS=[NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHIIS, UBOUNDS=[NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHCO2S, UBOUNDS=[NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHBIOS, UBOUNDS=[NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHBVOCS, UBOUNDS=[NPROMA,NVHILO,NDHVBVOCS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHVEGS, UBOUNDS=[NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS], PERSISTENT=.TRUE.)

    SELF%PDHTTS(1:NPROMA,1:NCSS,1:NDHVTTS+NDHFTTS,1:NBLOCKS)=0._JPRB
    SELF%PDHVEGS(1:NPROMA,1:NVHILO,1:NDHVVEGS+NDHFVEGS,1:NBLOCKS)=0._JPRB
  END SUBROUTINE DDH_SURF_TYPE_INIT

  SUBROUTINE DDH_SURF_TYPE_FINAL(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PDHTLS)
    CALL FIELD_DELETE(SELF%F_PDHTSS)
    CALL FIELD_DELETE(SELF%F_PDHSSS)
    CALL FIELD_DELETE(SELF%F_PDHTTS)
    CALL FIELD_DELETE(SELF%F_PDHWLS)
    CALL FIELD_DELETE(SELF%F_PDHTIS)
    CALL FIELD_DELETE(SELF%F_PDHIIS)
    CALL FIELD_DELETE(SELF%F_PDHCO2S)
    CALL FIELD_DELETE(SELF%F_PDHBIOS)
    CALL FIELD_DELETE(SELF%F_PDHBVOCS)
    CALL FIELD_DELETE(SELF%F_PDHVEGS)

    NULLIFY( SELF%PDHTLS)
    NULLIFY( SELF%PDHTSS)
    NULLIFY( SELF%PDHSSS)
    NULLIFY( SELF%PDHTTS)
    NULLIFY( SELF%PDHWLS)
    NULLIFY( SELF%PDHTIS)
    NULLIFY( SELF%PDHIIS)
    NULLIFY( SELF%PDHCO2S)
    NULLIFY( SELF%PDHBIOS)
    NULLIFY( SELF%PDHBVOCS)
    NULLIFY( SELF%PDHVEGS)
  END SUBROUTINE DDH_SURF_TYPE_FINAL

  SUBROUTINE SURFACE_PROGNOSTIC_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURFACE_PROGNOSTIC) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PSST)) SELF%PSST => SELF%F_PSST%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUOC)) SELF%PUOC => SELF%F_PUOC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVOC)) SELF%PVOC => SELF%F_PVOC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZWS1)) SELF%ZWS1 => SELF%F_ZWS1%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_PROGNOSTIC_UPDATE_VIEW

  SUBROUTINE SURFACE_PROGNOSTIC_SYNC_HOST(SELF)
    CLASS(SURFACE_PROGNOSTIC) :: SELF
    CALL SELF%F_PSST%SYNC_HOST_RDWR()
    CALL SELF%F_PUOC%SYNC_HOST_RDWR()
    CALL SELF%F_PVOC%SYNC_HOST_RDWR()
    CALL SELF%F_ZWS1%SYNC_HOST_RDWR()
  END SUBROUTINE SURFACE_PROGNOSTIC_SYNC_HOST

  SUBROUTINE SURFACE_DIAGNOSTIC_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURFACE_DIAGNOSTIC) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PEVAPTIU))  SELF%PEVAPTIU  => SELF%F_PEVAPTIU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PU10M))     SELF%PU10M     => SELF%F_PU10M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PV10M))     SELF%PV10M     => SELF%F_PV10M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PT2M))      SELF%PT2M      => SELF%F_PT2M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PD2M))      SELF%PD2M      => SELF%F_PD2M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PQ2M))      SELF%PQ2M      => SELF%F_PQ2M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PALBICEF))  SELF%PALBICEF  => SELF%F_PALBICEF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALCOEFF))  SELF%ZALCOEFF  => SELF%F_ZALCOEFF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZAVGPARC))  SELF%ZAVGPARC  => SELF%F_ZAVGPARC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTAUOCX))   SELF%PTAUOCX   => SELF%F_PTAUOCX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTAUOCY))   SELF%PTAUOCY   => SELF%F_PTAUOCY%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_POTKE))     SELF%POTKE     => SELF%F_POTKE%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_DIAGNOSTIC_UPDATE_VIEW

  SUBROUTINE SURFACE_DIAGNOSTIC_SYNC_HOST(SELF)
    CLASS(SURFACE_DIAGNOSTIC) :: SELF
    CALL SELF%F_PEVAPTIU%SYNC_HOST_RDWR()
    CALL SELF%F_PU10M%SYNC_HOST_RDWR()
    CALL SELF%F_PV10M%SYNC_HOST_RDWR()
    CALL SELF%F_PT2M%SYNC_HOST_RDWR()
    CALL SELF%F_PD2M%SYNC_HOST_RDWR()
    CALL SELF%F_PQ2M%SYNC_HOST_RDWR()
    CALL SELF%F_PALBICEF%SYNC_HOST_RDWR()
    CALL SELF%F_ZALCOEFF%SYNC_HOST_RDWR()
    CALL SELF%F_ZAVGPARC%SYNC_HOST_RDWR()
    CALL SELF%F_PTAUOCX%SYNC_HOST_RDWR()
    CALL SELF%F_PTAUOCY%SYNC_HOST_RDWR()
    CALL SELF%F_POTKE%SYNC_HOST_RDWR()
  END SUBROUTINE SURFACE_DIAGNOSTIC_SYNC_HOST

  SUBROUTINE SURF_AND_MORE_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_ZGPE))      SELF%ZGPE      => SELF%F_ZGPE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZEMIS))     SELF%ZEMIS     => SELF%F_ZEMIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ITVH))      SELF%ITVH      => SELF%F_ITVH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ITVL))      SELF%ITVL      => SELF%F_ITVL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ICO2TYP))   SELF%ICO2TYP   => SELF%F_ICO2TYP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ISOTY))     SELF%ISOTY     => SELF%F_ISOTY%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_IVEG))      SELF%IVEG      => SELF%F_IVEG%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCVL))      SELF%ZCVL      => SELF%F_ZCVL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCVH))      SELF%ZCVH      => SELF%F_ZCVH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCUR))      SELF%ZCUR      => SELF%F_ZCUR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PPHIOC))    SELF%PPHIOC    => SELF%F_PPHIOC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRSOIL_STR)) SELF%PRSOIL_STR => SELF%F_PRSOIL_STR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCO2FLUX))  SELF%PCO2FLUX  => SELF%F_PCO2FLUX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCH4FLUX))  SELF%PCH4FLUX  => SELF%F_PCH4FLUX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUSTOKES))  SELF%PUSTOKES  => SELF%F_PUSTOKES%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVSTOKES))  SELF%PVSTOKES  => SELF%F_PVSTOKES%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSEMEAN))  SELF%PWSEMEAN  => SELF%F_PWSEMEAN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSFMEAN))  SELF%PWSFMEAN  => SELF%F_PWSFMEAN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFM))     SELF%PDIFM     => SELF%F_PDIFM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFT))     SELF%PDIFT     => SELF%F_PDIFT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFS))     SELF%PDIFS     => SELF%F_PDIFS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUSTRC))    SELF%PUSTRC    => SELF%F_PUSTRC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVSTRC))    SELF%PVSTRC    => SELF%F_PVSTRC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRECO))     SELF%PRECO     => SELF%F_PRECO%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAN))       SELF%PAN       => SELF%F_PAN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAG))       SELF%PAG       => SELF%F_PAG%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRD))       SELF%PRD       => SELF%F_PRD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAI))      SELF%PLAI      => SELF%F_PLAI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOM))     SELF%PBIOM     => SELF%F_PBIOM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBLOSS))    SELF%PBLOSS    => SELF%F_PBLOSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBGAIN))    SELF%PBGAIN    => SELF%F_PBGAIN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMSTR))  SELF%PBIOMSTR  => SELF%F_PBIOMSTR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMSTR2)) SELF%PBIOMSTR2 => SELF%F_PBIOMSTR2%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAILP))    SELF%ZLAILP    => SELF%F_ZLAILP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIHP))    SELF%ZLAIHP    => SELF%F_ZLAIHP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCHAR))     SELF%ZCHAR     => SELF%F_ZCHAR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCHARHQ))   SELF%ZCHARHQ   => SELF%F_ZCHARHQ%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZTE))       SELF%ZTE       => SELF%F_ZTE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZQE))       SELF%ZQE       => SELF%F_ZQE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZVOM))      SELF%ZVOM      => SELF%F_ZVOM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZVOL))      SELF%ZVOL      => SELF%F_ZVOL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZTENC))     SELF%ZTENC     => SELF%F_ZTENC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZUCURR))    SELF%ZUCURR    => SELF%F_ZUCURR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZVCURR))    SELF%ZVCURR    => SELF%F_ZVCURR%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURF_AND_MORE_TYPE_UPDATE_VIEW

  SUBROUTINE SURF_AND_MORE_TYPE_SYNC_HOST(SELF)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    CALL SELF%F_ZGPE%SYNC_HOST_RDWR()
    CALL SELF%F_ZEMIS%SYNC_HOST_RDWR()
    CALL SELF%F_ITVH%SYNC_HOST_RDWR()
    CALL SELF%F_ITVL%SYNC_HOST_RDWR()
    CALL SELF%F_ICO2TYP%SYNC_HOST_RDWR()
    CALL SELF%F_ISOTY%SYNC_HOST_RDWR()
    CALL SELF%F_IVEG%SYNC_HOST_RDWR()
    CALL SELF%F_ZCVL%SYNC_HOST_RDWR()
    CALL SELF%F_ZCVH%SYNC_HOST_RDWR()
    CALL SELF%F_ZCUR%SYNC_HOST_RDWR()
    CALL SELF%F_PPHIOC%SYNC_HOST_RDWR()
    CALL SELF%F_PRSOIL_STR%SYNC_HOST_RDWR()
    CALL SELF%F_PCO2FLUX%SYNC_HOST_RDWR()
    CALL SELF%F_PCH4FLUX%SYNC_HOST_RDWR()
    CALL SELF%F_PUSTOKES%SYNC_HOST_RDWR()
    CALL SELF%F_PVSTOKES%SYNC_HOST_RDWR()
    CALL SELF%F_PWSEMEAN%SYNC_HOST_RDWR()
    CALL SELF%F_PWSFMEAN%SYNC_HOST_RDWR()
    CALL SELF%F_PDIFM%SYNC_HOST_RDWR()
    CALL SELF%F_PDIFT%SYNC_HOST_RDWR()
    CALL SELF%F_PDIFS%SYNC_HOST_RDWR()
    CALL SELF%F_PUSTRC%SYNC_HOST_RDWR()
    CALL SELF%F_PVSTRC%SYNC_HOST_RDWR()
    CALL SELF%F_PRECO%SYNC_HOST_RDWR()
    CALL SELF%F_PAN%SYNC_HOST_RDWR()
    CALL SELF%F_PAG%SYNC_HOST_RDWR()
    CALL SELF%F_PRD%SYNC_HOST_RDWR()
    CALL SELF%F_PLAI%SYNC_HOST_RDWR()
    CALL SELF%F_PBIOM%SYNC_HOST_RDWR()
    CALL SELF%F_PBLOSS%SYNC_HOST_RDWR()
    CALL SELF%F_PBGAIN%SYNC_HOST_RDWR()
    CALL SELF%F_PBIOMSTR%SYNC_HOST_RDWR()
    CALL SELF%F_PBIOMSTR2%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAILP%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIHP%SYNC_HOST_RDWR()
    CALL SELF%F_ZCHAR%SYNC_HOST_RDWR()
    CALL SELF%F_ZCHARHQ%SYNC_HOST_RDWR()
    CALL SELF%F_ZTE%SYNC_HOST_RDWR()
    CALL SELF%F_ZQE%SYNC_HOST_RDWR()
    CALL SELF%F_ZVOM%SYNC_HOST_RDWR()
    CALL SELF%F_ZVOL%SYNC_HOST_RDWR()
    CALL SELF%F_ZTENC%SYNC_HOST_RDWR()
    CALL SELF%F_ZUCURR%SYNC_HOST_RDWR()
    CALL SELF%F_ZVCURR%SYNC_HOST_RDWR()
  END SUBROUTINE SURF_AND_MORE_TYPE_SYNC_HOST

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PLAILI))        SELF%PLAILI        => SELF%F_PLAILI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAIHI))        SELF%PLAIHI        => SELF%F_PLAIHI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIL))         SELF%ZLAIL         => SELF%F_ZLAIL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIH))         SELF%ZLAIH         => SELF%F_ZLAIH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PZIDLWV))       SELF%PZIDLWV       => SELF%F_PZIDLWV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZTHKICE))       SELF%ZTHKICE       => SELF%F_ZTHKICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZWLMX))         SELF%ZWLMX         => SELF%F_ZWLMX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCSN))          SELF%ZCSN          => SELF%F_ZCSN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCVT))          SELF%ZCVT          => SELF%F_ZCVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIVT))        SELF%ZLAIVT        => SELF%F_ZLAIVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZKH))           SELF%ZKH           => SELF%F_ZKH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZEXDIAG))       SELF%ZEXDIAG       => SELF%F_ZEXDIAG%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZSPECTRALEMISS)) SELF%ZSPECTRALEMISS => SELF%F_ZSPECTRALEMISS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZEVAPSNW))      SELF%ZEVAPSNW      => SELF%F_ZEVAPSNW%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZFRTI))         SELF%ZFRTI         => SELF%F_ZFRTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALBTI))        SELF%ZALBTI        => SELF%F_ZALBTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZFRSOTI))       SELF%ZFRSOTI       => SELF%F_ZFRSOTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSLRFLTI))      SELF%PSLRFLTI      => SELF%F_PSLRFLTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALBD))         SELF%ZALBD         => SELF%F_ZALBD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALBP))         SELF%ZALBP         => SELF%F_ZALBP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_SYNC_HOST(SELF)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    CALL SELF%F_PLAILI%SYNC_HOST_RDWR()
    CALL SELF%F_PLAIHI%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIL%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIH%SYNC_HOST_RDWR()
    CALL SELF%F_PZIDLWV%SYNC_HOST_RDWR()
    CALL SELF%F_ZTHKICE%SYNC_HOST_RDWR()
    CALL SELF%F_ZWLMX%SYNC_HOST_RDWR()
    CALL SELF%F_ZCSN%SYNC_HOST_RDWR()
    CALL SELF%F_ZCVT%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIVT%SYNC_HOST_RDWR()
    CALL SELF%F_ZKH%SYNC_HOST_RDWR()
    CALL SELF%F_ZEXDIAG%SYNC_HOST_RDWR()
    CALL SELF%F_ZSPECTRALEMISS%SYNC_HOST_RDWR()
    CALL SELF%F_ZEVAPSNW%SYNC_HOST_RDWR()
    CALL SELF%F_ZFRTI%SYNC_HOST_RDWR()
    CALL SELF%F_ZALBTI%SYNC_HOST_RDWR()
    CALL SELF%F_ZFRSOTI%SYNC_HOST_RDWR()
    CALL SELF%F_PSLRFLTI%SYNC_HOST_RDWR()
    CALL SELF%F_ZALBD%SYNC_HOST_RDWR()
    CALL SELF%F_ZALBP%SYNC_HOST_RDWR()
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_SYNC_HOST

  SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PDHTLS))   SELF%PDHTLS   => SELF%F_PDHTLS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTSS))   SELF%PDHTSS   => SELF%F_PDHTSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTTS))   SELF%PDHTTS   => SELF%F_PDHTTS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTIS))   SELF%PDHTIS   => SELF%F_PDHTIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHCO2S))  SELF%PDHCO2S  => SELF%F_PDHCO2S%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHBVOCS)) SELF%PDHBVOCS => SELF%F_PDHBVOCS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHBIOS))  SELF%PDHBIOS  => SELF%F_PDHBIOS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHVEGS))  SELF%PDHVEGS  => SELF%F_PDHVEGS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHSSS))   SELF%PDHSSS   => SELF%F_PDHSSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHIIS))   SELF%PDHIIS   => SELF%F_PDHIIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHWLS))   SELF%PDHWLS   => SELF%F_PDHWLS%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW

  SUBROUTINE DDH_SURF_TYPE_SYNC_HOST(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF
    CALL SELF%F_PDHTLS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHTSS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHTTS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHTIS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHCO2S%SYNC_HOST_RDWR()
    CALL SELF%F_PDHBVOCS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHBIOS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHVEGS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHSSS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHIIS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHWLS%SYNC_HOST_RDWR()
  END SUBROUTINE DDH_SURF_TYPE_SYNC_HOST

END MODULE ECLAND_SURFACE_TYPE_MOD
