MODULE ECLAND_AUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGC1S  , ONLY : GEMU     ,GELAM    ,GELAT
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_2LM
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE AUX_TYPE
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: GELAT  => NULL() ! PLAT ! PGELAT  
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: GELAM  => NULL() ! PGELAM
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PMU0M  => NULL() ! PMU0 ! local cosine of instantaneous (mean) solar zenith angle
   CLASS(FIELD_2RB), POINTER :: F_PMU0M  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PGEMU  => NULL() ! sine of latitude 

CONTAINS
  PROCEDURE :: INIT  => AUX_TYPE_INIT
  PROCEDURE :: FINAL => AUX_TYPE_FINAL
END TYPE AUX_TYPE

TYPE KEYS_LOCAL_TYPE
  LOGICAL, DIMENSION(:,:), POINTER  :: LLLAND, LLSICE, LLLICE, LLNH  
  CLASS(FIELD_2LM), POINTER :: F_LLLAND => NULL()
  CLASS(FIELD_2LM), POINTER :: F_LLSICE => NULL()
  CLASS(FIELD_2LM), POINTER :: F_LLLICE => NULL()
  CLASS(FIELD_2LM), POINTER :: F_LLNH   => NULL()
  LOGICAL, DIMENSION(:,:), POINTER  :: LLLAKE, LLOCN_KPP
  CLASS(FIELD_2LM), POINTER :: F_LLLAKE   => NULL()
  CLASS(FIELD_2LM), POINTER :: F_LLOCN_KPP => NULL()
CONTAINS
  PROCEDURE :: INIT => KEYS_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => KEYS_LOCAL_TYPE_FINAL
END TYPE KEYS_LOCAL_TYPE

CONTAINS

  SUBROUTINE AUX_TYPE_INIT(SELF,NPROMA,NLEV,NBLOCKS)
    CLASS(AUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NLEV,NBLOCKS

    SELF%PGEMU => GEMU 
    SELF%GELAT => GELAT
    SELF%GELAM => GELAM

    CALL FIELD_NEW(SELF%F_PMU0M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
  END SUBROUTINE AUX_TYPE_INIT

  SUBROUTINE AUX_TYPE_FINAL(SELF)
     CLASS(AUX_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PMU0M)

     NULLIFY(SELF%PGEMU)
     NULLIFY(SELF%GELAT)
     NULLIFY(SELF%GELAM)
     NULLIFY(SELF%PMU0M)
  END SUBROUTINE AUX_TYPE_FINAL

  SUBROUTINE KEYS_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS) 
    CLASS(KEYS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS

    CALL FIELD_NEW(SELF%F_LLLAND, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_LLSICE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_LLNH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_LLLICE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_LLLAKE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_LLOCN_KPP, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
  END SUBROUTINE KEYS_LOCAL_TYPE_INIT

  SUBROUTINE KEYS_LOCAL_TYPE_FINAL(SELF)
    CLASS(KEYS_LOCAL_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_LLLAND)
    CALL FIELD_DELETE(SELF%F_LLSICE)
    CALL FIELD_DELETE(SELF%F_LLNH)
    CALL FIELD_DELETE(SELF%F_LLLICE)
    CALL FIELD_DELETE(SELF%F_LLLAKE)
    CALL FIELD_DELETE(SELF%F_LLOCN_KPP)

    NULLIFY(SELF%LLLAND)
    NULLIFY(SELF%LLSICE)
    NULLIFY(SELF%LLNH)
    NULLIFY(SELF%LLLICE)
    NULLIFY(SELF%LLLAKE)
    NULLIFY(SELF%LLOCN_KPP)
  END SUBROUTINE KEYS_LOCAL_TYPE_FINAL

END MODULE ECLAND_AUX_TYPE_MOD
