MODULE ECLAND_FLUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGF1S, ONLY : FCRF,FCSF,FLSRF,FLSSF
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE FLUX_TYPE
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PDIFTQ  => NULL() ! TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
    CLASS(FIELD_3RB), POINTER :: F_PDIFTQ  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PDIFTS  => NULL() ! TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
    CLASS(FIELD_3RB), POINTER :: F_PDIFTS  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFPLCL  => NULL() ! CONVECTIVE PRECIPITATION AS RAIN.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFPLCN  => NULL() ! CONVECTIVE PRECIPITATION AS SNOW.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFPLSL  => NULL() ! STRATIFORM PRECIPITATION AS RAIN.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFPLSN  => NULL() ! STRATIFORM PRECIPITATION AS SNOW.
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PFRSO   => NULL()  ! SHORTWAVE RADIATIVE FLUX.
    CLASS(FIELD_3RB), POINTER :: F_PFRSO   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PFRTH   => NULL()  ! LONGWAVE RADIATIVE FLUX.
    CLASS(FIELD_3RB), POINTER :: F_PFRTH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: ZFRTH   => NULL()  ! LONGWAVE RADIATIVE FLUX.
    CLASS(FIELD_2RB), POINTER :: F_ZFRTH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSTRTU  => NULL()  ! TURBULENT FLUX OF MOMENTUM (U and V)
    CLASS(FIELD_3RB), POINTER :: F_PSTRTU  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSTRTV  => NULL()  ! TURBULENT FLUX OF MOMENTUM (U and V)
    CLASS(FIELD_3RB), POINTER :: F_PSTRTV  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFTG12  => NULL()  !PTSDFL ! HEAT FLUX FROM LAYER 1 TO 2  ! NOT USED
    CLASS(FIELD_2RB), POINTER :: F_PFTG12  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFWG12  => NULL()  !PWFSD ! WATER FLUX FROM LAYER 1 TO 2  ! NOT USED
    CLASS(FIELD_2RB), POINTER :: F_PFWG12  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFWEV   => NULL()  ! SURFACE WATER VAPOUR FLUX (EVAPORATION)
    CLASS(FIELD_2RB), POINTER :: F_PFWEV   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFWSB   => NULL()  ! SURFACE WATER VAPOUR FLUX (SUBLIMATION)
    CLASS(FIELD_2RB), POINTER :: F_PFWSB   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFWMLT  => NULL()  !PFMLT ! WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
    CLASS(FIELD_2RB), POINTER :: F_PFWMLT  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFWROD  => NULL() ! RUN-OFF FLUX AT DEEPER LAYERS (2-4)
    CLASS(FIELD_2RB), POINTER :: F_PFWROD  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFWRO1  => NULL() ! RUN-OFF FLUX AT LAYER 1
    CLASS(FIELD_2RB), POINTER :: F_PFWRO1  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFTLHEV => NULL()! SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
    CLASS(FIELD_2RB), POINTER :: F_PFTLHEV => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PFTLHSB => NULL()! SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
    CLASS(FIELD_2RB), POINTER :: F_PFTLHSB => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: ZENES   => NULL()  !PENES         !  ???
    CLASS(FIELD_3RB), POINTER :: F_ZENES   => NULL()

CONTAINS
  PROCEDURE :: INIT => FLUX_TYPE_INIT
  PROCEDURE :: FINAL => FLUX_TYPE_FINAL
END TYPE FLUX_TYPE

CONTAINS

  SUBROUTINE FLUX_TYPE_INIT(SELF, NPROMA, NLEV,  NCSS, NBLOCKS)
    CLASS(FLUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NCSS, NBLOCKS

    SELF%PFPLCL=>FCRF
    SELF%PFPLCN=>FCSF
    SELF%PFPLSL=>FLSRF
    SELF%PFPLSN=>FLSSF

    CALL FIELD_NEW(SELF%F_ZENES, UBOUNDS=[NPROMA,NCSS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDIFTQ, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDIFTS, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFRSO, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFRTH, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZFRTH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PSTRTU, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PSTRTV, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFTG12, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWEV, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWSB, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWG12, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWMLT, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWROD, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWRO1, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFTLHEV, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFTLHSB, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)

  END SUBROUTINE FLUX_TYPE_INIT

  SUBROUTINE FLUX_TYPE_FINAL(SELF)
    CLASS(FLUX_TYPE) :: SELF

    NULLIFY(SELF%PFPLCL)
    NULLIFY(SELF%PFPLCN)
    NULLIFY(SELF%PFPLSL)
    NULLIFY(SELF%PFPLSN)


    CALL FIELD_DELETE(SELF%F_ZENES)
    CALL FIELD_DELETE(SELF%F_PDIFTQ)
    CALL FIELD_DELETE(SELF%F_PDIFTS)
    CALL FIELD_DELETE(SELF%F_PFRSO)
    CALL FIELD_DELETE(SELF%F_PFRTH)
    CALL FIELD_DELETE(SELF%F_ZFRTH)
    CALL FIELD_DELETE(SELF%F_PSTRTU)
    CALL FIELD_DELETE(SELF%F_PSTRTV)
    CALL FIELD_DELETE(SELF%F_PFTG12)
    CALL FIELD_DELETE(SELF%F_PFWEV)
    CALL FIELD_DELETE(SELF%F_PFWSB)
    CALL FIELD_DELETE(SELF%F_PFWG12)
    CALL FIELD_DELETE(SELF%F_PFWMLT)
    CALL FIELD_DELETE(SELF%F_PFWROD)
    CALL FIELD_DELETE(SELF%F_PFWRO1)
    CALL FIELD_DELETE(SELF%F_PFTLHEV)
    CALL FIELD_DELETE(SELF%F_PFTLHSB)

    NULLIFY(SELF%ZENES)
    NULLIFY(SELF%PDIFTQ)
    NULLIFY(SELF%PDIFTS)
    NULLIFY(SELF%PFRSO)
    NULLIFY(SELF%PFRTH)
    NULLIFY(SELF%ZFRTH)
    NULLIFY(SELF%PSTRTU)
    NULLIFY(SELF%PSTRTV)
    NULLIFY(SELF%PFTG12)
    NULLIFY(SELF%PFWEV)
    NULLIFY(SELF%PFWSB)
    NULLIFY(SELF%PFWG12)
    NULLIFY(SELF%PFWMLT)
    NULLIFY(SELF%PFWROD)
    NULLIFY(SELF%PFWRO1)
    NULLIFY(SELF%PFTLHEV)
    NULLIFY(SELF%PFTLHSB)
  END SUBROUTINE FLUX_TYPE_FINAL

END MODULE ECLAND_FLUX_TYPE_MOD
