MODULE ECLAND_SURFACE_TYPE_MOD

USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMGP1S0 ,                 ONLY : WRENU0, FSNNU0, RSNNU0, WSNNU0
USE YOMGF1S  ,                 ONLY : FSSRD, FSTRD
USE YOMCDH1S ,                 ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS

USE YOMGPD1S , ONLY : VFISOP_EP, &
     & VFFWET   , VFAVGPAR,VFSDOR   ,VFCIL,VDIEWSSTL,VDINSSSTL,VDISSHFTL,VDIETL   ,VDTSKTL,&
     & VFCLAKEF   ,VFALBF   ,VFCVL    ,VFCVH    ,VFCUR    ,VFTVL    ,VFTVH    , &
     & VFCO2TYP, VFLAIL   ,VFLAIH   ,VFSOTY   ,VFCI     , VFITM    ,VFZO     , &
     & VFHO     ,VFHO_INV ,VFDO     ,VFOCDEPTH, &
     & VFADVT ,VFADVS  ,VFTRI0   ,VFTRI1   ,VFSWDK_SAVE, VDALB,&
     & VDRESPBSTR,VDRESPBSTR2,VDBIOMASS_LAST,VDBLOSSVT,VDBGAINVT, VDANDAYVT,VDANFMVT 

USE YOMGP1S0 , ONLY : BSTRNU0,BSTR2NU0,ASNNU0   ,TSNNU0,TSLNU0   ,TRENU0   ,QLINU0   ,&
     & TILNU0,TLICENU0,TLMNWNU0,TLWMLNU0,TLBOTNU0,TLSFNU0,HLICENU0,HLMLNU0 ,&
     & UONU0, VONU0, TONU0, SONU0

USE PTRGP1S  , ONLY : MTSLNU  ,MQLINU  ,MFSNNU,         &
     &                MTSNNU  ,MASNNU  ,MWSNNU, MRSNNU, &
     &                MTRENU  ,MWRENU  ,MTILNU,         &
     &                MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &                MHLICENU,MHLMLNU ,                &           ! FLAKE
     &                MUONU   ,MVONU   ,MTONU   ,MSONU, &           !KPP
     &                MLAINU  ,MBSTRNU ,MBSTR2NU

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: SURFACE_PROGNOSTIC 

  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PHLICE => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLICE => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTL    => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLSF  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLMNW => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLWML => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PSST   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUO0   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVO0   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: ZWS1   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLBOT => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PASN   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSN   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PWSA   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSA   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTIA   => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PHLML  => NULL() 

END TYPE SURFACE_PROGNOSTIC 

TYPE, PUBLIC :: SURFACE_DIAGNOSTIC

  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PDO      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PHO      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: POCDEPTH => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PHO_INV  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PEVAPTIU => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU10M    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PV10M    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PT2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PD2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PALBF    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PALBICEF => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLAILC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PLAIHC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: ZALCOEFF => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PADVT    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PADVS    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTRI0    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTRI1    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: ZAVGPARC => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PTAUOCX  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PTAUOCY  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: POTKE    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSWDK_SAVE => NULL()

END TYPE SURFACE_DIAGNOSTIC

TYPE, PUBLIC :: SURF_AND_MORE_TYPE

   REAL(KIND=JPRB),DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZGPE => NULL()

   TYPE(SURFACE_PROGNOSTIC) :: GSP
   TYPE(SURFACE_DIAGNOSTIC) :: GSD
  ! T star tiles
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PUSTRTI => NULL()  ! E-W (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PVSTRTI => NULL() ! N-S (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PAHFSTI => NULL() ! (INSTANTANEOUS) SURFACE SENSIBLE HEAT FLUX FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PEVAPTI => NULL() ! (INSTANTANEOUS) EVAPORATION FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTSKTI  => NULL() ! SKIN TEMPERATURE FOR EACH TILE
  ! other 
   REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: ZEMIS   => NULL() !PEMIS      ! MODEL SURFACE LONGWAVE EMISSIVITY.
  !  Tendencies from surface scheme
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PSNSE1  => NULL() ! OF MULTI-LAYER SNOW MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PRSNE1  => NULL() ! OF MULTI-LAYER SNOW DENSITY
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTSNE1  => NULL() ! OF MULTI-LAYER SNOW TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PWSNE1  => NULL() ! OF MULTI-LAYER SNOW LIQUID WATER MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER :: PASNE1  => NULL() ! OF SNOW ALBEDO : only the top layer is used
   REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER :: PWLE1   => NULL() ! OF SKIN RESERVOIR WATER CONTENT
   REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER :: PTLE1   => NULL() ! OF SKIN TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PLAIE1  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PBSTRE1 => NULL() 
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PBSTR2E1 => NULL() 
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTSAE1  => NULL() ! OF MULTI-LAYER SOIL TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PWSAE1  => NULL() ! OF MULTI-LAYER SOIL WETNESS
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTIAE1  => NULL() ! OF MULTI-LAYER SEA ICE TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PUOE1   => NULL() ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PVOE1   => NULL() ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PTOE1   => NULL() ! TEMPERATURE TENDENCY OF OCEAN MIXED LAYER MODEL  K/S
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PSOE1   => NULL() ! SALINITY TENDENCY OF OCEAN MIXED LAYER MODEL  psu/S
   REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: PSDOR   => NULL() !PHSTD    ! STANDARD DEVIATION OF SUBGRID OROGRAPHY
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ITVH    => NULL() 
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ITVL    => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ICO2TYP => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:),   POINTER :: ISOTY   => NULL()! to store vegetation indices and soil type index
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), POINTER :: IVEG    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCVL    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCVH    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCUR    => NULL()  ! to store vegetation covers
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PCIL    => NULL()  ! to store land-ice fraction
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PPHIOC           => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PRESPBSTR        => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PRESPBSTR2       => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBLOSSVT         => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBGAINVT         => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBIOMASS_LAST    => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBIOMASSTR_LAST  => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PBIOMASSTR2_LAST => NULL() 
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PRSOIL_STR       => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PCO2FLUX => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PCH4FLUX => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PUSTOKES => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PVSTOKES => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PWSEMEAN => NULL()!PEMEAN
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PWSFMEAN => NULL()!PFMEAN
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PDIFM    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PDIFT    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: PDIFS    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PUSTRC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PVSTRC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PRECO    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PAN      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PAG      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PRD      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PLAIL    => NULL()    ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PLAIH    => NULL()    ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PLAI     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBIOM    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBLOSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBGAIN   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBIOMSTR => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PBIOMSTR2=> NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAILP   => NULL() !PLAILP, PLAIHP   ! to store variable LAI previous time
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAIHP   => NULL()!PLAILP, PLAIHP   ! to store variable LAI previous time
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAIL    => NULL()  ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZLAIH    => NULL()   ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCHAR    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZCHARHQ  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZTE      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZQE      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZVOM     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZVOL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:),    POINTER :: ZTENC    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZUCURR   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZVCURR   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: ZAVGPAR  => NULL() !PAVGPAR          ! Average PAR for BVOC emis module
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PISOP_EP => NULL()        ! Isoprene emission potential
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PFWET    => NULL()        ! to store wetland fraction
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLICEE1 => NULL()      ! tendency of lake ice temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLMNWE1 => NULL()      ! tendency of lake totat layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLWMLE1 => NULL()      ! tendency of lake mixed layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLBOTE1 => NULL()      ! tendency of lake bottom layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PTLSFE1  => NULL()      ! tendency of lake shape factor - 
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PHLICEE1 => NULL()      ! tendency of lake ice depth m
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PHLMLE1  => NULL()      ! tendency of lake mixed layer depth m/s
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PSRSOD   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),      POINTER :: PSRTHD   => NULL()

CONTAINS
  PROCEDURE :: INIT  => SURF_AND_MORE_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_TYPE_FINAL

END TYPE SURF_AND_MORE_TYPE


CONTAINS

  SUBROUTINE SURF_AND_MORE_TYPE_INIT(SELF, NPROMA, NGPP,  NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NGPP, NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES,  NBLOCKS 

    SELF%PISOP_EP=>VFISOP_EP
    SELF%PFWET=>VFFWET
    SELF%ZAVGPAR=>VFAVGPAR
    SELF%PSDOR=>VFSDOR
    SELF%PCIL=>VFCIL
    SELF%PUSTRTI=>VDIEWSSTL
    SELF%PVSTRTI=>VDINSSSTL
    SELF%PAHFSTI=>VDISSHFTL
    SELF%PEVAPTI=>VDIETL
    SELF%PTSKTI=>VDTSKTL
    SELF%PRESPBSTR=>VDRESPBSTR
    SELF%PRESPBSTR2=>VDRESPBSTR2
    SELF%PBIOMASS_LAST=>VDBIOMASS_LAST
    SELF%PBIOMASSTR_LAST=>BSTRNU0
    SELF%PBIOMASSTR2_LAST=>BSTR2NU0
    SELF%PBLOSSVT=>VDBLOSSVT
    SELF%PBGAINVT=>VDBGAINVT
    SELF%GSP%PASN=>ASNNU0
    SELF%GSP%PTSN=>TSNNU0
    SELF%GSP%PTSA=>TSLNU0
    SELF%GSP%PTL=>TRENU0
    SELF%GSP%PWSA=>QLINU0
    SELF%GSP%PTIA=>TILNU0
    SELF%GSP%PTLICE=>TLICENU0
    SELF%GSP%PTLMNW=>TLMNWNU0
    SELF%GSP%PTLWML=>TLWMLNU0
    SELF%GSP%PTLBOT=>TLBOTNU0
    SELF%GSP%PTLSF=>TLSFNU0
    SELF%GSP%PHLICE=>HLICENU0
    SELF%GSP%PHLML=>HLMLNU0
    SELF%GSP%PUO0=>UONU0
    SELF%GSP%PVO0=>VONU0
    SELF%GSP%PTO0=>TONU0
    SELF%GSP%PSO0=>SONU0
    SELF%GSD%PHO=>VFHO
    SELF%GSD%PDO=>VFDO
    SELF%GSD%PLAILC=>VFLAIL
    SELF%GSD%PLAIHC=>VFLAIH
    SELF%GSD%PALBF=>VFALBF
    SELF%GSD%PHO_INV=>VFHO_INV
    SELF%GSD%POCDEPTH=>VFOCDEPTH
    SELF%GSD%PADVT=>VFADVT
    SELF%GSD%PADVS=>VFADVS
    SELF%GSD%PTRI0=>VFTRI0
    SELF%GSD%PTRI1=>VFTRI1
    SELF%GSD%PSWDK_SAVE=>VFSWDK_SAVE
    SELF%PSRSOD=>FSSRD 
    SELF%PSRTHD=>FSTRD


    ALLOCATE(SELF%PUSTRC(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PVSTRC(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCVL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCVH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCUR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PAN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PAG(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PRD(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PRSOIL_STR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PRECO(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PCO2FLUX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PCH4FLUX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PLAI(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZEMIS(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAILP(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAIHP(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCHAR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCHARHQ(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZUCURR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZVCURR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PUSTOKES(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PVSTOKES(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PTAUOCX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PTAUOCY(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PPHIOC(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PWSEMEAN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PWSFMEAN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBIOM(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBLOSS(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBGAIN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBIOMSTR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBIOMSTR2(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PDIFM(NPROMA,0:NCOM,NBLOCKS))     !KPP
    ALLOCATE(SELF%PDIFT(NPROMA,0:NCOM,NBLOCKS) )    !KPP
    ALLOCATE(SELF%PDIFS(NPROMA,0:NCOM,NBLOCKS))

    
    ALLOCATE(SELF%ZTE(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZQE(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZVOM(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZVOL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZTENC(NPROMA,NTRAC,NBLOCKS))
    ALLOCATE(SELF%ITVL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ITVH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ISOTY(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ICO2TYP(NPROMA,NBLOCKS))
    ALLOCATE(SELF%IVEG(NPROMA,NVHILO,NBLOCKS))
    ALLOCATE(SELF%GSP%PUOC(NPROMA,1:NCOM+1,NBLOCKS))                  !KPP
    ALLOCATE(SELF%GSP%PVOC(NPROMA,1:NCOM+1,NBLOCKS))
    ALLOCATE(SELF%GSP%PSST(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSP%ZWS1(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PEVAPTIU(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%GSD%PU10M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PV10M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PT2M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PD2M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PQ2M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%POTKE(NPROMA,0:NCOM,NBLOCKS))
    ALLOCATE(SELF%GSD%ZALCOEFF(NPROMA,6,NBLOCKS))
    ALLOCATE(SELF%GSD%PALBICEF(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%ZAVGPARC(NPROMA,NBLOCKS))

    ALLOCATE (SELF%ZGPE(NPROMA,NGPP,NBLOCKS))

    SELF%PSNSE1 => SELF%ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:)
    SELF%PTSNE1 => SELF%ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:)
    SELF%PWSNE1 => SELF%ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:)
    SELF%PRSNE1 => SELF%ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:)
    SELF%PASNE1 => SELF%ZGPE(:,MASNNU,:)
    SELF%PTLE1  => SELF%ZGPE(:,MTRENU,:)
    SELF%PWLE1  => SELF%ZGPE(:,MWRENU,:)
    SELF%PTIAE1 => SELF%ZGPE(:,MTILNU:MTILNU+NCSS-1,:)
    SELF%PWSAE1 => SELF%ZGPE(:,MQLINU:MQLINU+NCSS-1,:)
    SELF%PTSAE1 => SELF%ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)
    
    SELF%PTLICEE1 => SELF%ZGPE(:,MTLICENU,:)
    SELF%PTLMNWE1 => SELF%ZGPE(:,MTLMNWNU,:)
    SELF%PTLWMLE1 => SELF%ZGPE(:,MTLWMLNU,:)
    SELF%PTLBOTE1 => SELF%ZGPE(:,MTLBOTNU,:)
    SELF%PTLSFE1  => SELF%ZGPE(:,MTLSFNU,:)
    SELF%PHLICEE1 => SELF%ZGPE(:,MHLICENU,:)
    SELF%PHLMLE1  => SELF%ZGPE(:,MHLMLNU,:)
    
    SELF%PUOE1 => SELF%ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  !KPP
    SELF%PVOE1 => SELF%ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  !KPP
    SELF%PTOE1 => SELF%ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  !KPP
    SELF%PSOE1 => SELF%ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  !KPP
    
    SELF%PLAIE1 => SELF%ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)
    SELF%PBSTRE1 => SELF%ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)
    SELF%PBSTR2E1 => SELF%ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:)

  END SUBROUTINE SURF_AND_MORE_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_TYPE) :: SELF

    NULLIFY(SELF%PISOP_EP)
    NULLIFY(SELF%PFWET)
    NULLIFY(SELF%ZAVGPAR)
    NULLIFY(SELF%PSDOR)
    NULLIFY(SELF%PCIL)
    NULLIFY(SELF%PUSTRTI)
    NULLIFY(SELF%PVSTRTI)
    NULLIFY(SELF%PAHFSTI)
    NULLIFY(SELF%PEVAPTI)
    NULLIFY(SELF%PTSKTI)
    NULLIFY(SELF%PRESPBSTR)
    NULLIFY(SELF%PRESPBSTR2)
    NULLIFY(SELF%PBIOMASS_LAST)
    NULLIFY(SELF%PBIOMASSTR_LAST)
    NULLIFY(SELF%PBIOMASSTR2_LAST)
    NULLIFY(SELF%PBLOSSVT)
    NULLIFY(SELF%PBGAINVT)
    NULLIFY(SELF%GSP%PASN)
    NULLIFY(SELF%GSP%PTSN)
    NULLIFY(SELF%GSP%PTSA)
    NULLIFY(SELF%GSP%PTL)
    NULLIFY(SELF%GSP%PWSA)
    NULLIFY(SELF%GSP%PTIA)
    NULLIFY(SELF%GSP%PTLICE)
    NULLIFY(SELF%GSP%PTLMNW)
    NULLIFY(SELF%GSP%PTLWML)
    NULLIFY(SELF%GSP%PTLBOT)
    NULLIFY(SELF%GSP%PTLSF)
    NULLIFY(SELF%GSP%PHLICE)
    NULLIFY(SELF%GSP%PHLML)
    NULLIFY(SELF%GSP%PUO0)
    NULLIFY(SELF%GSP%PVO0)
    NULLIFY(SELF%GSP%PTO0)
    NULLIFY(SELF%GSP%PSO0)
    NULLIFY(SELF%GSD%PALBF)
    NULLIFY(SELF%GSD%PLAILC)
    NULLIFY(SELF%GSD%PLAIHC)
    NULLIFY(SELF%GSD%PHO_INV)
    NULLIFY(SELF%GSD%POCDEPTH)
    NULLIFY(SELF%GSD%PADVT)
    NULLIFY(SELF%GSD%PADVS)
    NULLIFY(SELF%GSD%PTRI0)
    NULLIFY(SELF%GSD%PTRI1)
    NULLIFY(SELF%GSD%PHO)
    NULLIFY(SELF%GSD%PDO)
    NULLIFY(SELF%GSD%PSWDK_SAVE)
    NULLIFY(SELF%PSRSOD)
    NULLIFY(SELF%PSRTHD)
    NULLIFY(SELF%PSNSE1)
    NULLIFY(SELF%PTSNE1)
    NULLIFY(SELF%PWSNE1)
    NULLIFY(SELF%PRSNE1)
    NULLIFY(SELF%PASNE1)
    NULLIFY(SELF%PTLE1 )
    NULLIFY(SELF%PWLE1 )
    NULLIFY(SELF%PTIAE1)
    NULLIFY(SELF%PWSAE1)
    NULLIFY(SELF%PTSAE1)
    NULLIFY(SELF%PTLICEE1)
    NULLIFY(SELF%PTLMNWE1)
    NULLIFY(SELF%PTLWMLE1)
    NULLIFY(SELF%PTLBOTE1)
    NULLIFY(SELF%PTLSFE1 )
    NULLIFY(SELF%PHLICEE1)
    NULLIFY(SELF%PHLMLE1 )
    NULLIFY(SELF%PUOE1)
    NULLIFY(SELF%PVOE1)
    NULLIFY(SELF%PTOE1)
    NULLIFY(SELF%PSOE1)
    NULLIFY(SELF%PLAIE1)
    NULLIFY(SELF%PBSTRE1)
    NULLIFY(SELF%PBSTR2E1)

    DEALLOCATE(SELF%PUSTRC)
    DEALLOCATE(SELF%PVSTRC)
    DEALLOCATE(SELF%ZCVL)
    DEALLOCATE(SELF%ZCVH)
    DEALLOCATE(SELF%ZCUR)
    DEALLOCATE(SELF%PAN)
    DEALLOCATE(SELF%PAG)
    DEALLOCATE(SELF%PRD)
    DEALLOCATE(SELF%PRSOIL_STR)
    DEALLOCATE(SELF%PRECO)
    DEALLOCATE(SELF%PCO2FLUX)
    DEALLOCATE(SELF%PCH4FLUX)
    DEALLOCATE(SELF%PLAI)
    DEALLOCATE(SELF%ZEMIS)
    DEALLOCATE(SELF%ZLAILP)
    DEALLOCATE(SELF%ZLAIHP)
    DEALLOCATE(SELF%ZCHAR)
    DEALLOCATE(SELF%ZCHARHQ)
    DEALLOCATE(SELF%ZUCURR)
    DEALLOCATE(SELF%ZVCURR)
    DEALLOCATE(SELF%PUSTOKES)
    DEALLOCATE(SELF%PVSTOKES)
    DEALLOCATE(SELF%GSD%PTAUOCX)
    DEALLOCATE(SELF%GSD%PTAUOCY)
    DEALLOCATE(SELF%PPHIOC)
    DEALLOCATE(SELF%PWSEMEAN)
    DEALLOCATE(SELF%PWSFMEAN)
    DEALLOCATE(SELF%PBIOM)
    DEALLOCATE(SELF%PBLOSS)
    DEALLOCATE(SELF%PBGAIN)
    DEALLOCATE(SELF%PBIOMSTR)
    DEALLOCATE(SELF%PBIOMSTR2)
    DEALLOCATE(SELF%PDIFM)
    DEALLOCATE(SELF%PDIFT)
    DEALLOCATE(SELF%PDIFS)
    DEALLOCATE(SELF%ZTE)
    DEALLOCATE(SELF%ZQE)
    DEALLOCATE(SELF%ZVOM)
    DEALLOCATE(SELF%ZVOL)
    DEALLOCATE(SELF%ZTENC)
    DEALLOCATE(SELF%ITVL)
    DEALLOCATE(SELF%ITVH)
    DEALLOCATE(SELF%ISOTY)
    DEALLOCATE(SELF%ICO2TYP)
    DEALLOCATE(SELF%IVEG)
    DEALLOCATE(SELF%GSP%PUOC)
    DEALLOCATE(SELF%GSP%PVOC)
    DEALLOCATE(SELF%GSP%PSST)
    DEALLOCATE(SELF%GSP%ZWS1)
    DEALLOCATE(SELF%GSD%PEVAPTIU)
    DEALLOCATE(SELF%GSD%PU10M)
    DEALLOCATE(SELF%GSD%PV10M)
    DEALLOCATE(SELF%GSD%PT2M)
    DEALLOCATE(SELF%GSD%PD2M)
    DEALLOCATE(SELF%GSD%PQ2M)
    DEALLOCATE(SELF%GSD%POTKE)
    DEALLOCATE(SELF%GSD%ZALCOEFF)
    DEALLOCATE(SELF%GSD%PALBICEF)
    DEALLOCATE(SELF%GSD%ZAVGPARC)
    DEALLOCATE(SELF%ZGPE)

    NULLIFY(SELF%PUSTRC)
    NULLIFY(SELF%PVSTRC)
    NULLIFY(SELF%ZCVL)
    NULLIFY(SELF%ZCVH)
    NULLIFY(SELF%ZCUR)
    NULLIFY(SELF%PAN)
    NULLIFY(SELF%PAG)
    NULLIFY(SELF%PRD)
    NULLIFY(SELF%PRSOIL_STR)
    NULLIFY(SELF%PRECO)
    NULLIFY(SELF%PCO2FLUX)
    NULLIFY(SELF%PCH4FLUX)
    NULLIFY(SELF%PLAI)
    NULLIFY(SELF%ZEMIS)
    NULLIFY(SELF%ZLAILP)
    NULLIFY(SELF%ZLAIHP)
    NULLIFY(SELF%ZCHAR)
    NULLIFY(SELF%ZCHARHQ)
    NULLIFY(SELF%ZUCURR)
    NULLIFY(SELF%ZVCURR)
    NULLIFY(SELF%PUSTOKES)
    NULLIFY(SELF%PVSTOKES)
    NULLIFY(SELF%GSD%PTAUOCX)
    NULLIFY(SELF%GSD%PTAUOCY)
    NULLIFY(SELF%PPHIOC)
    NULLIFY(SELF%PWSEMEAN)
    NULLIFY(SELF%PWSFMEAN)
    NULLIFY(SELF%PBIOM)
    NULLIFY(SELF%PBLOSS)
    NULLIFY(SELF%PBGAIN)
    NULLIFY(SELF%PBIOMSTR)
    NULLIFY(SELF%PBIOMSTR2)
    NULLIFY(SELF%PDIFM)
    NULLIFY(SELF%PDIFT)
    NULLIFY(SELF%PDIFS)
    NULLIFY(SELF%ZTE)
    NULLIFY(SELF%ZQE)
    NULLIFY(SELF%ZVOM)
    NULLIFY(SELF%ZVOL)
    NULLIFY(SELF%ZTENC)
    NULLIFY(SELF%ITVL)
    NULLIFY(SELF%ITVH)
    NULLIFY(SELF%ISOTY)
    NULLIFY(SELF%ICO2TYP)
    NULLIFY(SELF%IVEG)
    NULLIFY(SELF%GSP%PUOC)
    NULLIFY(SELF%GSP%PVOC)
    NULLIFY(SELF%GSP%PSST)
    NULLIFY(SELF%GSP%ZWS1)
    NULLIFY(SELF%GSD%PEVAPTIU)
    NULLIFY(SELF%GSD%PU10M)
    NULLIFY(SELF%GSD%PV10M)
    NULLIFY(SELF%GSD%PT2M)
    NULLIFY(SELF%GSD%PD2M)
    NULLIFY(SELF%GSD%PQ2M)
    NULLIFY(SELF%GSD%POTKE)
    NULLIFY(SELF%GSD%ZALCOEFF)
    NULLIFY(SELF%GSD%PALBICEF)
    NULLIFY(SELF%GSD%ZAVGPARC)
    NULLIFY(SELF%ZGPE)
  END SUBROUTINE SURF_AND_MORE_TYPE_FINAL

END MODULE ECLAND_SURFACE_TYPE_MOD
