MODULE ECLAND_GEMS_TYPE_MOD

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMGF1S  , ONLY : CNLEV0, CNLEV1
USE YOMGPD1S , ONLY : VDZ0F, VDZ0H

IMPLICIT NONE

TYPE GEMS_LOCAL_TYPE
!-- basic GEMS fields
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PC! PC=ZCEN,ZTENC,ZTENC_SKF
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PC1!
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PCFLX !ZCFLX,ZDDVLC,ZCHEMDV,ZCFLXO
! - aerosols transport arrays
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PZ0M,PZ0H
! Online biogenic VOC emissions
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER::  PBVOCFLUX   !(KDIM%KLON,NEMIS_BVOC)
CONTAINS
   PROCEDURE :: INIT => GEMS_LOCAL_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => GEMS_LOCAL_TYPE_UPDATE_VIEW
   PROCEDURE :: FINAL => GEMS_LOCAL_TYPE_FINAL

END TYPE GEMS_LOCAL_TYPE

CONTAINS 

SUBROUTINE GEMS_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS,NTRAC,NDHVBVOCS) !, REGISTRY, VARIABLES, NLEV, PERSISTENT)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS,NTRAC,NDHVBVOCS
    SELF%PZ0M=>VDZ0F
    SELF%PZ0H=>VDZ0H
    ALLOCATE(SELF%PCFLX(NPROMA,NTRAC,NBLOCKS)) 
    ALLOCATE(SELF%PBVOCFLUX(NPROMA,NDHVBVOCS,NBLOCKS))
    SELF%PC=>CNLEV0
    SELF%PC1=>CNLEV1
END SUBROUTINE GEMS_LOCAL_TYPE_INIT

SUBROUTINE GEMS_LOCAL_TYPE_FINAL(SELF) !, REGISTRY, VARIABLES, NLEV, PERSISTENT)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    DEALLOCATE(SELF%PCFLX) 
    DEALLOCATE(SELF%PBVOCFLUX) 
END SUBROUTINE GEMS_LOCAL_TYPE_FINAL
END MODULE ECLAND_GEMS_TYPE_MOD

