MODULE ECLAND_GEMS_TYPE_MOD

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMGF1S  , ONLY : CNLEV0, CNLEV1
USE YOMGPD1S , ONLY : VDZ0F, VDZ0H

IMPLICIT NONE

TYPE GEMS_LOCAL_TYPE

!-- basic GEMS fields
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PC => NULL()! PC=ZCEN,ZTENC,ZTENC_SKF
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PC1 => NULL()!
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PCFLX => NULL() !ZCFLX,ZDDVLC,ZCHEMDV,ZCFLXO
! - aerosols transport arrays
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PZ0M => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PZ0H => NULL()
! Online biogenic VOC emissions
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER::  PBVOCFLUX => NULL()   !(KDIM%KLON,NEMIS_BVOC)

CONTAINS
   PROCEDURE :: INIT => GEMS_LOCAL_TYPE_INIT
   PROCEDURE :: FINAL => GEMS_LOCAL_TYPE_FINAL

END TYPE GEMS_LOCAL_TYPE

CONTAINS 

SUBROUTINE GEMS_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS,NTRAC,NDHVBVOCS)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS,NTRAC,NDHVBVOCS

    SELF%PZ0M=>VDZ0F
    SELF%PZ0H=>VDZ0H
    SELF%PC=>CNLEV0
    SELF%PC1=>CNLEV1

    ALLOCATE(SELF%PCFLX(NPROMA,NTRAC,NBLOCKS)) 
    ALLOCATE(SELF%PBVOCFLUX(NPROMA,NDHVBVOCS,NBLOCKS))
END SUBROUTINE GEMS_LOCAL_TYPE_INIT

SUBROUTINE GEMS_LOCAL_TYPE_FINAL(SELF)
    CLASS(GEMS_LOCAL_TYPE) :: SELF

    NULLIFY(SELF%PC)
    NULLIFY(SELF%PC1)
    NULLIFY(SELF%PZ0M)
    NULLIFY(SELF%PZ0H)

    DEALLOCATE(SELF%PCFLX) 
    DEALLOCATE(SELF%PBVOCFLUX) 
END SUBROUTINE GEMS_LOCAL_TYPE_FINAL

END MODULE ECLAND_GEMS_TYPE_MOD

