MODULE ECLAND_SURFACE_TYPE_MOD

USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMGP1S0 ,                 ONLY : WRENU0, FSNNU0, RSNNU0, WSNNU0
USE YOMGF1S  ,                 ONLY : FSSRD, FSTRD
USE YOMCDH1S ,                 ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS

USE YOMGPD1S , ONLY : VFISOP_EP, &
     & VFFWET   , VFAVGPAR,VFSDOR   ,VFCIL,VDIEWSSTL,VDINSSSTL,VDISSHFTL,VDIETL   ,VDTSKTL,&
     & VFCLAKEF   ,VFALBF   ,VFCVL    ,VFCVH    ,VFCUR    ,VFTVL    ,VFTVH    , &
     & VFCO2TYP, VFLAIL   ,VFLAIH   ,VFSOTY   ,VFCI     , VFITM    ,VFZO     , &
     & VFHO     ,VFHO_INV ,VFDO     ,VFOCDEPTH, &
     & VFADVT ,VFADVS  ,VFTRI0   ,VFTRI1   ,VFSWDK_SAVE, VDALB,&
     & VDRESPBSTR,VDRESPBSTR2,VDBIOMASS_LAST,VDBLOSSVT,VDBGAINVT, VDANDAYVT,VDANFMVT 

USE YOMGP1S0 , ONLY : BSTRNU0,BSTR2NU0,ASNNU0   ,TSNNU0,TSLNU0   ,TRENU0   ,QLINU0   ,&
     & TILNU0,TLICENU0,TLMNWNU0,TLWMLNU0,TLBOTNU0,TLSFNU0,HLICENU0,HLMLNU0 ,&
     & UONU0, VONU0, TONU0, SONU0

USE PTRGP1S  , ONLY : MTSLNU  ,MQLINU  ,MFSNNU,         &
     &                MTSNNU  ,MASNNU  ,MWSNNU, MRSNNU, &
     &                MTRENU  ,MWRENU  ,MTILNU,         &
     &                MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &                MHLICENU,MHLMLNU ,                &           ! FLAKE
     &                MUONU   ,MVONU   ,MTONU   ,MSONU, &           !KPP
     &                MLAINU  ,MBSTRNU ,MBSTR2NU

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: SURFACE_PROGNOSTIC 

  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PHLICE 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLICE 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTL 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLSF 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLMNW 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLWML 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PSST 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUO0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUOC
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVO0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVOC
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTO0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSO0 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: ZWS1 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PTLBOT 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PASN 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSN 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PWSA 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSA 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTIA 
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PHLML 

END TYPE SURFACE_PROGNOSTIC 

TYPE, PUBLIC :: SURFACE_DIAGNOSTIC

  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PCLAKE 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PTVL 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PTVH 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PALB 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PSOTY 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PCVL 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PCVH 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PCUR 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PLSM 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PCI 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PZO 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER:: POCDEPTH 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PHO_INV 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PEVAPTIU 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PU10M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PV10M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PT2M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PD2M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PQ2M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PALBF 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PALBICEF 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PLAILC 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PLAIHC 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: PCO2TYP 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: ZALCOEFF 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PADVT
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PADVS
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTRI0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTRI1 
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: ZAVGPARC 
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PTAUOCX,PTAUOCY 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: POTKE
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSWDK_SAVE 

END TYPE SURFACE_DIAGNOSTIC

TYPE, PUBLIC :: SURF_AND_MORE_TYPE

   REAL(KIND=JPRB),DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZGPE

   TYPE(SURFACE_PROGNOSTIC) :: GSP
   TYPE(SURFACE_DIAGNOSTIC) :: GSD
  ! T star tiles
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUSTRTI  ! E-W (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVSTRTI  ! N-S (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PAHFSTI  ! (INSTANTANEOUS) SURFACE SENSIBLE HEAT FLUX FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PEVAPTI  ! (INSTANTANEOUS) EVAPORATION FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSKTI   ! SKIN TEMPERATURE FOR EACH TILE
  ! other 
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  ZEMIS !PEMIS      ! MODEL SURFACE LONGWAVE EMISSIVITY.
  !  Tendencies from surface scheme
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSNSE1   ! OF MULTI-LAYER SNOW MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PRSNE1   ! OF MULTI-LAYER SNOW DENSITY
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSNE1   ! OF MULTI-LAYER SNOW TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PWSNE1   ! OF MULTI-LAYER SNOW LIQUID WATER MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PASNE1   ! OF SNOW ALBEDO : only the top layer is used
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PWLE1    ! OF SKIN RESERVOIR WATER CONTENT
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PTLE1    ! OF SKIN TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PLAIE1 
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PBSTRE1 
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PBSTR2E1 
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTSAE1   ! OF MULTI-LAYER SOIL TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PWSAE1   ! OF MULTI-LAYER SOIL WETNESS
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTIAE1   ! OF MULTI-LAYER SEA ICE TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PUOE1    ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PVOE1    ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PTOE1    ! TEMPERATURE TENDENCY OF OCEAN MIXED LAYER MODEL  K/S
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PSOE1    ! SALINITY TENDENCY OF OCEAN MIXED LAYER MODEL  psu/S
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PSDOR !PHSTD    ! STANDARD DEVIATION OF SUBGRID OROGRAPHY
  INTEGER(KIND=JPIM), DIMENSION(:,:), POINTER :: ITVH, ITVL, ICO2TYP, ISOTY ! to store vegetation indices and soil type index
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), POINTER :: IVEG
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZCVL, ZCVH, ZCUR       ! to store vegetation covers
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PCIL                   ! to store land-ice fraction
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PPHIOC
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: PRESPBSTR,PRESPBSTR2 
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: PBLOSSVT,PBGAINVT 
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: PBIOMASS_LAST 
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: PBIOMASSTR_LAST 
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: PBIOMASSTR2_LAST 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PRSOIL_STR,PCO2FLUX,PCH4FLUX
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PUSTOKES,PVSTOKES 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PWSEMEAN,PWSFMEAN !PEMEAN,PFMEAN
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: PDIFM,PDIFT,PDIFS
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PUSTRC,PVSTRC,PRECO 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PAN,PAG,PRD
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PLAIL, PLAIH     ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PLAI
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PBIOM,PBLOSS,PBGAIN 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PBIOMSTR,PBIOMSTR2
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZLAILP,ZLAIHP !PLAILP, PLAIHP   ! to store variable LAI previous time
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZLAIL, ZLAIH     ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZCHAR,ZCHARHQ 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZTE,ZQE,ZVOM,ZVOL 
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER :: ZTENC
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZUCURR,ZVCURR
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: ZAVGPAR !PAVGPAR          ! Average PAR for BVOC emis module
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PISOP_EP         ! Isoprene emission potential
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PFWET            ! to store wetland fraction
  REAL(KIND=JPRB), DIMENSION(:)  ,  POINTER :: PEVAPMU    ! potential evaporation
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PTLICEE1       ! tendency of lake ice temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PTLMNWE1       ! tendency of lake totat layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PTLWMLE1       ! tendency of lake mixed layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PTLBOTE1       ! tendency of lake bottom layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PTLSFE1        ! tendency of lake shape factor - 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PHLICEE1       ! tendency of lake ice depth m
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PHLMLE1        ! tendency of lake mixed layer depth m/s
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PSRSOD
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER :: PSRTHD

CONTAINS
  PROCEDURE :: INIT => SURF_AND_MORE_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_TYPE_FINAL

END TYPE SURF_AND_MORE_TYPE

TYPE, PUBLIC :: SURF_AND_MORE_LOCAL_TYPE
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PLAILI, PLAIHI !ZLAILI, ZLAIHI   ! Arrays for interactive LAI (CITESSEL option)
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZLAIL, ZLAIH
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PWL !ZWLM1M
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: PZIDLWV 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PSNS,PRSN !ZSNM1M, ZRSNM1M ! KLON,KLEVSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PWSN
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZTHKICE!, ZSNTICE  ! sea ice
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZWLMX
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZCSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZCVT 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZLAIVT 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZKH 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZEXDIAG
   ! Longwave surface spectral emissivity in two or more bands,
   ! dimensioned (KLON,NLWEMISS); note that ZEMIR and ZEMIW point to
   ! the first two columns of this matrix:
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZSPECTRALEMISS
     REAL(KIND=JPRB), DIMENSION(:,:),    POINTER  :: ZEVAPSNW
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZFRTI ,ZALBTI ! KLON,KTILES
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZFRSOTI
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PSLRFLTI !ZAHFTRTI
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: ZALBD ,ZALBP ! KLON,NTSW
   !  CTESSEL: Carbon model
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER  :: PANDAYVT, PANFMVT !ZANDAYVT, ZANFMVT

CONTAINS
  PROCEDURE :: INIT => SURF_AND_MORE_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_LOCAL_TYPE_FINAL
END TYPE SURF_AND_MORE_LOCAL_TYPE

TYPE, PUBLIC :: DDH_SURF_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTLS      ! Diagnostic array for tiles (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTSS      ! Diagnostic array for snow T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTTS      ! Diagnostic array for soil T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHTIS      ! Diagnostic array for ice T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHCO2S    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHBVOCS    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHBIOS    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHVEGS    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHSSS      ! Diagnostic array for snow mass (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER :: PDHIIS      ! Diagnostic array for interception layer (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: PDHWLS      ! Diagnostic array for soil water (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:),     POINTER :: PDHFSS

CONTAINS
  PROCEDURE :: INIT => DDH_SURF_TYPE_INIT
  PROCEDURE :: FINAL => DDH_SURF_TYPE_FINAL
END TYPE DDH_SURF_TYPE

CONTAINS

  SUBROUTINE SURF_AND_MORE_TYPE_INIT(SELF, NPROMA, NGPP,  NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NGPP, NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES,  NBLOCKS 

    SELF%PISOP_EP=>VFISOP_EP
    SELF%PFWET=>VFFWET
    SELF%ZAVGPAR=>VFAVGPAR
    SELF%PSDOR=>VFSDOR
    SELF%PCIL=>VFCIL
    SELF%PUSTRTI=>VDIEWSSTL
    SELF%PVSTRTI=>VDINSSSTL
    SELF%PAHFSTI=>VDISSHFTL
    SELF%PEVAPTI=>VDIETL
    SELF%PTSKTI=>VDTSKTL
    SELF%PRESPBSTR=>VDRESPBSTR
    SELF%PRESPBSTR2=>VDRESPBSTR2
    SELF%PBIOMASS_LAST=>VDBIOMASS_LAST
    SELF%PBIOMASSTR_LAST=>BSTRNU0
    SELF%PBIOMASSTR2_LAST=>BSTR2NU0
    SELF%PBLOSSVT=>VDBLOSSVT
    SELF%PBGAINVT=>VDBGAINVT
    SELF%GSP%PASN=>ASNNU0
    SELF%GSP%PTSN=>TSNNU0
    SELF%GSP%PTSA=>TSLNU0
    SELF%GSP%PTL=>TRENU0
    SELF%GSP%PWSA=>QLINU0
    SELF%GSP%PTIA=>TILNU0
    SELF%GSP%PTLICE=>TLICENU0
    SELF%GSP%PTLMNW=>TLMNWNU0
    SELF%GSP%PTLWML=>TLWMLNU0
    SELF%GSP%PTLBOT=>TLBOTNU0
    SELF%GSP%PTLSF=>TLSFNU0
    SELF%GSP%PHLICE=>HLICENU0
    SELF%GSP%PHLML=>HLMLNU0
    SELF%GSP%PUO0=>UONU0
    SELF%GSP%PVO0=>VONU0
    SELF%GSP%PTO0=>TONU0
    SELF%GSP%PSO0=>SONU0
    SELF%GSD%PCLAKE=>VFCLAKEF
    SELF%GSD%PALBF=>VFALBF
    SELF%GSD%PCVL=>VFCVL
    SELF%GSD%PCVH=>VFCVH
    SELF%GSD%PCUR=>VFCUR
    SELF%GSD%PTVL=>VFTVL
    SELF%GSD%PCO2TYP=>VFCO2TYP
    SELF%GSD%PTVH=>VFTVH
    SELF%GSD%PLAILC=>VFLAIL
    SELF%GSD%PLAIHC=>VFLAIH
    SELF%GSD%PSOTY=>VFSOTY
    SELF%GSD%PCI=>VFCI
    SELF%GSD%PLSM=>VFITM
    SELF%GSD%PZO=>VFZO
    SELF%GSD%PHO_INV=>VFHO_INV
    SELF%GSD%POCDEPTH=>VFOCDEPTH
    SELF%GSD%PADVT=>VFADVT
    SELF%GSD%PADVS=>VFADVS
    SELF%GSD%PTRI0=>VFTRI0
    SELF%GSD%PTRI1=>VFTRI1
    SELF%GSD%PSWDK_SAVE=>VFSWDK_SAVE
    SELF%GSD%PALB=>VDALB
    SELF%PSRSOD=>FSSRD 
    SELF%PSRTHD=>FSTRD
    ALLOCATE (SELF%ZGPE(NPROMA,NGPP,NBLOCKS))
    ALLOCATE(SELF%PUSTRC(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PVSTRC(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCVL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCVH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCUR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PAN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PAG(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PRD(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PRSOIL_STR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PRECO(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PCO2FLUX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PCH4FLUX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PLAI(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZEMIS(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAILP(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAIHP(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCHAR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCHARHQ(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZUCURR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZVCURR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PUSTOKES(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PVSTOKES(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PTAUOCX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PTAUOCY(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PPHIOC(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PWSEMEAN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PWSFMEAN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBIOM(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBLOSS(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBGAIN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBIOMSTR(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PBIOMSTR2(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PDIFM(NPROMA,0:NCOM,NBLOCKS))     !KPP
    ALLOCATE(SELF%PDIFT(NPROMA,0:NCOM,NBLOCKS) )    !KPP
    ALLOCATE(SELF%PDIFS(NPROMA,0:NCOM,NBLOCKS))

    SELF%PSNSE1 => SELF%ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:)
    SELF%PTSNE1 => SELF%ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:)
    SELF%PWSNE1 => SELF%ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:)
    SELF%PRSNE1 => SELF%ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:)
    SELF%PASNE1 => SELF%ZGPE(:,MASNNU,:)
    SELF%PTLE1  => SELF%ZGPE(:,MTRENU,:)
    SELF%PWLE1  => SELF%ZGPE(:,MWRENU,:)
    SELF%PTIAE1 => SELF%ZGPE(:,MTILNU:MTILNU+NCSS-1,:)
    SELF%PWSAE1 => SELF%ZGPE(:,MQLINU:MQLINU+NCSS-1,:)
    SELF%PTSAE1 => SELF%ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)
    
    SELF%PTLICEE1 => SELF%ZGPE(:,MTLICENU,:)
    SELF%PTLMNWE1 => SELF%ZGPE(:,MTLMNWNU,:)
    SELF%PTLWMLE1 => SELF%ZGPE(:,MTLWMLNU,:)
    SELF%PTLBOTE1 => SELF%ZGPE(:,MTLBOTNU,:)
    SELF%PTLSFE1  => SELF%ZGPE(:,MTLSFNU,:)
    SELF%PHLICEE1 => SELF%ZGPE(:,MHLICENU,:)
    SELF%PHLMLE1  => SELF%ZGPE(:,MHLMLNU,:)
    
    SELF%PUOE1 => SELF%ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  !KPP
    SELF%PVOE1 => SELF%ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  !KPP
    SELF%PTOE1 => SELF%ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  !KPP
    SELF%PSOE1 => SELF%ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  !KPP
    
    SELF%PLAIE1 => SELF%ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)
    SELF%PBSTRE1 => SELF%ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)
    SELF%PBSTR2E1 => SELF%ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:)
    
    ALLOCATE(SELF%ZTE(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZQE(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZVOM(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZVOL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZTENC(NPROMA,NTRAC,NBLOCKS))
    ALLOCATE(SELF%ITVL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ITVH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ISOTY(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ICO2TYP(NPROMA,NBLOCKS))
    ALLOCATE(SELF%IVEG(NPROMA,NVHILO,NBLOCKS))
    ALLOCATE(SELF%GSP%PUOC(NPROMA,1:NCOM+1,NBLOCKS))                  !KPP
    ALLOCATE(SELF%GSP%PVOC(NPROMA,1:NCOM+1,NBLOCKS))
    ALLOCATE(SELF%GSP%PSST(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSP%ZWS1(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PEVAPTIU(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%GSD%PU10M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PV10M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PT2M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PD2M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%PQ2M(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%POTKE(NPROMA,0:NCOM,NBLOCKS))
    ALLOCATE(SELF%GSD%ZALCOEFF(NPROMA,6,NBLOCKS))
    ALLOCATE(SELF%GSD%PALBICEF(NPROMA,NBLOCKS))
    ALLOCATE(SELF%GSD%ZAVGPARC(NPROMA,NBLOCKS))

  END SUBROUTINE SURF_AND_MORE_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_TYPE) :: SELF

    DEALLOCATE(SELF%PUSTRC)
    DEALLOCATE(SELF%PVSTRC)
    DEALLOCATE(SELF%ZCVL)
    DEALLOCATE(SELF%ZCVH)
    DEALLOCATE(SELF%ZCUR)
    DEALLOCATE(SELF%PAN)
    DEALLOCATE(SELF%PAG)
    DEALLOCATE(SELF%PRD)
    DEALLOCATE(SELF%PRSOIL_STR)
    DEALLOCATE(SELF%PRECO)
    DEALLOCATE(SELF%PCO2FLUX)
    DEALLOCATE(SELF%PCH4FLUX)
    DEALLOCATE(SELF%PLAI)
    DEALLOCATE(SELF%ZEMIS)
    DEALLOCATE(SELF%ZLAILP)
    DEALLOCATE(SELF%ZLAIHP)
    DEALLOCATE(SELF%ZCHAR)
    DEALLOCATE(SELF%ZCHARHQ)
    DEALLOCATE(SELF%ZUCURR)
    DEALLOCATE(SELF%ZVCURR)
    DEALLOCATE(SELF%PUSTOKES)
    DEALLOCATE(SELF%PVSTOKES)
    DEALLOCATE(SELF%GSD%PTAUOCX)
    DEALLOCATE(SELF%GSD%PTAUOCY)
    DEALLOCATE(SELF%PPHIOC)
    DEALLOCATE(SELF%PWSEMEAN)
    DEALLOCATE(SELF%PWSFMEAN)
    DEALLOCATE(SELF%PBIOM)
    DEALLOCATE(SELF%PBLOSS)
    DEALLOCATE(SELF%PBGAIN)
    DEALLOCATE(SELF%PBIOMSTR)
    DEALLOCATE(SELF%PBIOMSTR2)
    DEALLOCATE(SELF%PDIFM)
    DEALLOCATE(SELF%PDIFT)
    DEALLOCATE(SELF%PDIFS)
    DEALLOCATE(SELF%ZGPE)
    DEALLOCATE(SELF%ZTE)
    DEALLOCATE(SELF%ZQE)
    DEALLOCATE(SELF%ZVOM)
    DEALLOCATE(SELF%ZVOL)
    DEALLOCATE(SELF%ZTENC)
    DEALLOCATE(SELF%ITVL)
    DEALLOCATE(SELF%ITVH)
    DEALLOCATE(SELF%ISOTY)
    DEALLOCATE(SELF%ICO2TYP)
    DEALLOCATE(SELF%IVEG)
    DEALLOCATE(SELF%GSP%PUOC)
    DEALLOCATE(SELF%GSP%PVOC)
    DEALLOCATE(SELF%GSP%PSST)
    DEALLOCATE(SELF%GSP%ZWS1)
    DEALLOCATE(SELF%GSD%PEVAPTIU)
    DEALLOCATE(SELF%GSD%PU10M)
    DEALLOCATE(SELF%GSD%PV10M)
    DEALLOCATE(SELF%GSD%PT2M)
    DEALLOCATE(SELF%GSD%PD2M)
    DEALLOCATE(SELF%GSD%PQ2M)
    DEALLOCATE(SELF%GSD%POTKE)
    DEALLOCATE(SELF%GSD%ZALCOEFF)
    DEALLOCATE(SELF%GSD%PALBICEF)

  END SUBROUTINE SURF_AND_MORE_TYPE_FINAL

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT(SELF,NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NBLOCKS, NTSW,NTILES, NLWEMISS,NVHILO 

    SELF%PWL=>WRENU0
    SELF%PSNS=>FSNNU0
    SELF%PRSN=>RSNNU0
    SELF%PWSN=>WSNNU0
    SELF%PANDAYVT=>VDANDAYVT
    SELF%PANFMVT=>VDANFMVT
    ALLOCATE(SELF%PLAIHI(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PLAILI(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAIL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZLAIH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PZIDLWV(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZTHKICE(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZWLMX(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCSN(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCVT(NPROMA,NVHILO,NBLOCKS))
    ALLOCATE(SELF%ZLAIVT(NPROMA,NVHILO,NBLOCKS))
    ALLOCATE(SELF%ZKH(NPROMA,NLEV,NBLOCKS))
    ALLOCATE(SELF%ZEXDIAG(NPROMA,12,NBLOCKS))
    ALLOCATE(SELF%ZSPECTRALEMISS(NPROMA,NLWEMISS,NBLOCKS))
    ALLOCATE(SELF%ZEVAPSNW(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZFRTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%ZALBTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%ZFRSOTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%PSLRFLTI(NPROMA,NTILES,NBLOCKS))
    ALLOCATE(SELF%ZALBD(NPROMA,NTSW,NBLOCKS))
    ALLOCATE(SELF%ZALBP(NPROMA,NTSW,NBLOCKS))
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF

    DEALLOCATE(SELF%PLAIHI)
    DEALLOCATE(SELF%PLAILI)
    DEALLOCATE(SELF%ZLAIL)
    DEALLOCATE(SELF%ZLAIH)
    DEALLOCATE(SELF%PZIDLWV)
    DEALLOCATE(SELF%ZTHKICE)
    DEALLOCATE(SELF%ZWLMX)
    DEALLOCATE(SELF%ZCSN)
    DEALLOCATE(SELF%ZCVT)
    DEALLOCATE(SELF%ZLAIVT)
    DEALLOCATE(SELF%ZKH)
    DEALLOCATE(SELF%ZEXDIAG)
    DEALLOCATE(SELF%ZSPECTRALEMISS)
    DEALLOCATE(SELF%ZEVAPSNW)
    DEALLOCATE(SELF%ZFRTI)
    DEALLOCATE(SELF%ZALBTI)
    DEALLOCATE(SELF%ZFRSOTI)
    DEALLOCATE(SELF%PSLRFLTI)
    DEALLOCATE(SELF%ZALBD)
    DEALLOCATE(SELF%ZALBP)

  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL

  SUBROUTINE DDH_SURF_TYPE_INIT(SELF, NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO

    ALLOCATE( SELF%PDHTLS(NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS))
    ALLOCATE( SELF%PDHTSS(NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS))
    ALLOCATE( SELF%PDHSSS(NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS))
    ALLOCATE( SELF%PDHTTS(NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS))
    ALLOCATE( SELF%PDHWLS(NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS))
    ALLOCATE( SELF%PDHTIS(NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS))
    ALLOCATE( SELF%PDHIIS(NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS))
    ALLOCATE( SELF%PDHCO2S(NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS))
    ALLOCATE( SELF%PDHBIOS(NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS))
    ALLOCATE( SELF%PDHBVOCS(NPROMA,NVHILO,NDHVBVOCS,NBLOCKS))
    ALLOCATE( SELF%PDHVEGS(NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS))
    SELF%PDHTTS(:,:,:,:)=0._JPRB
    SELF%PDHVEGS(:,:,:,:)=0._JPRB

  END SUBROUTINE DDH_SURF_TYPE_INIT

  SUBROUTINE DDH_SURF_TYPE_FINAL(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF

    DEALLOCATE( SELF%PDHTLS)
    DEALLOCATE( SELF%PDHTSS)
    DEALLOCATE( SELF%PDHSSS)
    DEALLOCATE( SELF%PDHTTS)
    DEALLOCATE( SELF%PDHWLS)
    DEALLOCATE( SELF%PDHTIS)
    DEALLOCATE( SELF%PDHIIS)
    DEALLOCATE( SELF%PDHCO2S)
    DEALLOCATE( SELF%PDHBIOS)
    DEALLOCATE( SELF%PDHBVOCS)
    DEALLOCATE( SELF%PDHVEGS)

  END SUBROUTINE DDH_SURF_TYPE_FINAL

END MODULE ECLAND_SURFACE_TYPE_MOD
