MODULE ECLAND_GEMS_TYPE_MOD

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMGF1S  , ONLY : CNLEV0, CNLEV1
USE YOMGPD1S , ONLY : VDZ0F, VDZ0H
USE FIELD_MODULE, ONLY: FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE GEMS_LOCAL_TYPE

!-- basic GEMS fields
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PC => NULL()! PC=ZCEN,ZTENC,ZTENC_SKF
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PC1 => NULL()!
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PCFLX => NULL() !ZCFLX,ZDDVLC,ZCHEMDV,ZCFLXO
   CLASS(FIELD_3RB), POINTER :: F_PCFLX => NULL()
! - aerosols transport arrays
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PZ0M => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER :: PZ0H => NULL()
! Online biogenic VOC emissions
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER::  PBVOCFLUX => NULL()   !(KDIM%KLON,NEMIS_BVOC)
   CLASS(FIELD_3RB), POINTER :: F_PBVOCFLUX => NULL()

CONTAINS
   PROCEDURE :: INIT => GEMS_LOCAL_TYPE_INIT
   PROCEDURE :: FINAL => GEMS_LOCAL_TYPE_FINAL
   PROCEDURE :: UPDATE_VIEW => GEMS_LOCAL_TYPE_UPDATE_VIEW
   PROCEDURE :: SYNC_HOST   => GEMS_LOCAL_TYPE_SYNC_HOST

END TYPE GEMS_LOCAL_TYPE

CONTAINS 

SUBROUTINE GEMS_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS,NTRAC,NDHVBVOCS)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS,NTRAC,NDHVBVOCS

    SELF%PZ0M=>VDZ0F
    SELF%PZ0H=>VDZ0H
    SELF%PC=>CNLEV0
    SELF%PC1=>CNLEV1

    CALL FIELD_NEW(SELF%F_PCFLX, UBOUNDS=[NPROMA,NTRAC,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PBVOCFLUX, UBOUNDS=[NPROMA,NDHVBVOCS,NBLOCKS], PERSISTENT=.TRUE.)
END SUBROUTINE GEMS_LOCAL_TYPE_INIT

SUBROUTINE GEMS_LOCAL_TYPE_FINAL(SELF)
    CLASS(GEMS_LOCAL_TYPE) :: SELF

    NULLIFY(SELF%PC)
    NULLIFY(SELF%PC1)
    NULLIFY(SELF%PZ0M)
    NULLIFY(SELF%PZ0H)

    CALL FIELD_DELETE(SELF%F_PCFLX)
    CALL FIELD_DELETE(SELF%F_PBVOCFLUX)

    NULLIFY(SELF%PCFLX) 
    NULLIFY(SELF%PBVOCFLUX) 
END SUBROUTINE GEMS_LOCAL_TYPE_FINAL

SUBROUTINE GEMS_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PCFLX))     SELF%PCFLX     => SELF%F_PCFLX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBVOCFLUX)) SELF%PBVOCFLUX => SELF%F_PBVOCFLUX%GET_VIEW(BLOCK_INDEX)
END SUBROUTINE GEMS_LOCAL_TYPE_UPDATE_VIEW

SUBROUTINE GEMS_LOCAL_TYPE_SYNC_HOST(SELF)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    CALL SELF%F_PCFLX%SYNC_HOST_RDWR()
    CALL SELF%F_PBVOCFLUX%SYNC_HOST_RDWR()
END SUBROUTINE GEMS_LOCAL_TYPE_SYNC_HOST

END MODULE ECLAND_GEMS_TYPE_MOD

