
SUBROUTINE ECLAND_DRV_UNSPLIT_LAYER

USE YOMDPHY  ,  ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, &
      &                NVHILO, NGPP, NPOI, NLEV, NBLOCKS  
USE YOMCDH1S ,  ONLY : NLEVI, NDHFCO2S , &
      &                NDHVSSS, NDHFSSS, NDHVIIS, NDHFIIS, &
      &                NDHVWLS, NDHFWLS, NDHVRESS, NDHFRESS, &
      &                NDHVTTS, NDHFTTS, NDHVTIS, NDHFTIS, &
      &                NDHVTLS, NDHFTLS, NDHVTSS, NDHFTSS, &
      &                NDHVCO2S, NDHFCO2S, &
      &                NDHVBIOS, NDHFBIOS, NDHVBVOCS, NDHVVEGS, NDHFVEGS
USE YOMDYN1S ,  ONLY : NSTEP    ,TDT,TSTEP
USE YOMGPD1S ,  ONLY : VFSST, VFALUVI,  VFALUVV, VFALUVG,&
      &                VFALNII, VFALNIV, VFALNIG, VFALUVP, VFALUVD, &
      &                VFALNIP, VFALNID, VFZ0F, VFZ0H, VFAVGPAR
USE YOMGF1S  ,  ONLY : PNLP0, PNLP1, RALT
USE YOMGP1S0 ,  ONLY : GP0, TONU0, RSNNU0, TSNNU0, FSNNU0, WSNNU0, LAINU0 
USE YOMGP1S1 ,  ONLY : GP1, LAINU1
USE PTRGP1S  ,  ONLY : MFSNNU, MRSNNU, MTSNNU, MWSNNU  
USE YOMLOG1S,   ONLY : IDBGS1
USE YOMCT01S ,  ONLY : NSTART
USE YOMCST   ,  ONLY : RG
USE YOERIP   ,  ONLY : RCODECM  ,RSIDECM  ,RCOVSRM  ,RSIVSRM
USE YOERAD   ,  ONLY : NTSW, NLWEMISS
USE YOMDIM1S ,  ONLY : NPROMA
USE YOEPHY   ,  ONLY : NALBEDOSCHEME, LBVOC_EMIS
USE YOMGDI1S ,  ONLY : GDI1S    ,N2DDI ,&
      &                GDIAUX1S ,N2DDIAUX

USE YOMLUN1S, ONLY : NULOUT
USE YOMSURF_SSDP_MOD, ONLY : NSSDP2D, NSSDP3D

USE ECLAND_SURFACE_TYPE_MOD,  ONLY: SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,  ONLY: DDH_SURF_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD,      ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_FLUX_TYPE_MOD,     ONLY: FLUX_TYPE
USE ECLAND_ATMO_TYPE_MOD,     ONLY: ATMO_TYPE
USE ECLAND_INTERNAL_TYPE_MOD, ONLY: INTERNAL_TYPE
USE ECLAND_GEMS_TYPE_MOD,     ONLY: GEMS_LOCAL_TYPE

USE CALLPAR1S_LAYER_MOD, ONLY: CALLPAR1S_LAYER
USE UPDIAG_LAYER_MOD, ONLY: UPDDIAG_LAYER
USE OMP_LIB


#ifdef DOC
#endif

USE PARKIND1  ,ONLY : JPIM     ,JPRB,    JPRD
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK
IMPLICIT NONE


CHARACTER*1 :: CDCONF 
INTEGER(KIND=JPIM) :: IST,IEND,IPROMA,IFLEV, IBL, NTHREADS
INTEGER(KIND=JPIM) :: JL,J
! INTEGER(KIND=JPIM) :: OMP_GET_MAX_THREADS

TYPE(SURF_AND_MORE_TYPE),       SAVE :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), SAVE :: PSURFL
TYPE(AUX_DIAG_TYPE),            SAVE :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE),      SAVE :: PAUXL
TYPE(AUX_TYPE),                 SAVE :: PAUX
TYPE(FLUX_TYPE),                SAVE :: PFLUX
TYPE(ATMO_TYPE),                SAVE :: STATE
TYPE(INTERNAL_TYPE),            SAVE :: PINTER 
TYPE(GEMS_LOCAL_TYPE),          SAVE :: GEMSL
TYPE(KEYS_LOCAL_TYPE),          SAVE :: LLKEYS
TYPE(DDH_SURF_TYPE),            SAVE :: PDDHS

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('ECLAND_DRV_UNSPLIT_LAYER',0,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

IF (NSTEP.EQ.NSTART) THEN
   CALL PSURF%INIT(NPROMA, NGPP,NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS)
   CALL PSURFL%INIT(NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
   CALL PDIAG%INIT(NPROMA, NBLOCKS)
   CALL PAUXL%INIT(NPROMA, NBLOCKS)
   CALL PAUX%INIT(NPROMA,NLEV,NBLOCKS)
   CALL PFLUX%INIT(NPROMA, NLEV, NCSS, NBLOCKS)
   CALL STATE%INIT()
   CALL PINTER%INIT()
   CALL GEMSL%INIT(NPROMA,NBLOCKS,NTRAC,NDHVBVOCS)
   CALL LLKEYS%INIT(NPROMA,NBLOCKS)
   CALL PDDHS%INIT(NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )
ENDIF

ASSOCIATE(LEOCML=>YSURF%YOCEAN_ML%LEOCML,RTT=>YSURF%YCST%RTT)
ASSOCIATE(GEMU=>PAUX%PGEMU,GELAM=>PAUX%GELAM,ZMU0M=>PAUX%PMU0M,ZAPHIF=>PAUX%PGEOM1,ZAPRS=>PAUX%PAPRS)
ASSOCIATE(ZCFLX=>GEMSL%PCFLX)


!*       1.    INITIAL COMPUTATIONS.
!              ---------------------


!     TIME STEP




!*       1.1  INITIALIZING SURFACE VARIABLES AT T-DT (FIRST TIMESTEP).
!             --------------------------------------------------------    

! --- original setting without openMP
!IST=1
!IEND=NPOI
!IPROMA=NPOI
! ---
IFLEV=NLEV
!$OMP PARALLEL
NTHREADS=OMP_GET_MAX_THREADS()
!$OMP END PARALLEL 

IF ( IDBGS1 > 1 ) THEN
  WRITE(NULOUT,*) 'CPG1S:',NPROMA,NPOI,NTHREADS
ENDIF


!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(IST,IEND,IBL,IPROMA) SHARED(GP0,GP1,GDI1S,GDIAUX1S)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1

  GP1(1:IPROMA,1:NGPP,IBL)=GP0(1:IPROMA,1:NGPP,IBL)

!     STAFF FOR CALLPAR1S

  ZAPHIF(1:IPROMA,:,IBL)=RG*RALT
  ZAPRS(1:IPROMA,IFLEV,IBL)=PNLP0(1:IPROMA,IBL)
  ZAPRS(1:IPROMA,IFLEV-1,IBL)=PNLP0(1:IPROMA,IBL)-RALT*0.0065_JPRB
! Added "MIN(1._JPRB , ... ) to computation of ZMU0M. This ensures ZMU0M is between physical boundaries.
  ZMU0M(1:IPROMA,IBL)=MIN(1._JPRB, MAX( RSIDECM*GEMU(1:IPROMA,IBL) &
     & -RCODECM*RCOVSRM*SQRT(1._JPRB-GEMU(1:IPROMA,IBL)**2)*COS(GELAM(1:IPROMA,IBL)) &
     & +RCODECM*RSIVSRM*SQRT(1._JPRB-GEMU(1:IPROMA,IBL)**2)*SIN(GELAM(1:IPROMA,IBL)) &
     & ,0._JPRB) )

  IF(LEOCML) THEN
! replace SST with the top layer temp. of the ocean mixed layer (~ 1m depth)
    VFSST(1:IPROMA,IBL) = TONU0(1:IPROMA,1,IBL) + RTT ! The unit of PSST(VFSST) is K.  
  ENDIF

!! init 
  ZCFLX(1:IPROMA,:,IBL) = 0._JPRB 

  PSURF%PUSTRC(:,IBL)=0.0_JPRB
  PSURF%PVSTRC(:,IBL)=0.0_JPRB
  PSURF%GSP%PUOC(:,:,IBL)=0.0_JPRB
  PSURF%GSP%PVOC(:,:,IBL)=0.0_JPRB
  PSURF%GSP%PSST(1:IPROMA,IBL)=VFSST(1:IPROMA,IBL)
  PSURFL%PLAILI(:,IBL)=LAINU0(:,1,IBL)
  PSURFL%PLAIHI(:,IBL)=LAINU0(:,2,IBL)

    IF (NALBEDOSCHEME == 2) THEN
      ! 6 components
      PSURF%GSD%ZALCOEFF(1:IPROMA,1,IBL) = VFALUVI(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,2,IBL) = VFALUVV(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,3,IBL) = VFALUVG(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,4,IBL) = VFALNII(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,5,IBL) = VFALNIV(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,6,IBL) = VFALNIG(1:IPROMA,IBL)
    ELSE
      ! 4 components
      PSURF%GSD%ZALCOEFF(1:IPROMA,1,IBL) = VFALUVP(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,2,IBL) = VFALUVD(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,3,IBL) = VFALNIP(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,4,IBL) = VFALNID(1:IPROMA,IBL)
    ENDIF
!*       1.1   FIRST TIME-STEP
IF (NSTEP.EQ.NSTART) THEN
  GEMSL%PZ0M(1:IPROMA,IBL)=MAX(0.001_JPRB ,VFZ0F(1:IPROMA,IBL))! PZ0MCL(IST:IEND))
  GEMSL%PZ0H(1:IPROMA,IBL)=MAX(0.0001_JPRB,VFZ0H(1:IPROMA,IBL))!PZ0HCL(IST:IEND))
ENDIF

!* Initialize dummy AVGPAR array, fill with zero if no BVOC emissions
IF ( LBVOC_EMIS ) THEN
      PSURF%GSD%ZAVGPARC(1:IPROMA,IBL) = VFAVGPAR(1:IPROMA,IBL) ! W/m2
ELSE
      PSURF%GSD%ZAVGPARC(1:IPROMA,IBL) = 0._JPRB
ENDIF

!*      2.   CALL PHYSICS.
!            -------------
  CDCONF='F'
  CALL CALLPAR1S_LAYER (CDCONF=CDCONF &
     & , IST=IST,IEND=IEND,IBL=IBL,IPROMA=IPROMA,NPROMA=NPROMA &
     & , KIDIA=1, KFDIA=NPOI   , KLON=NPROMA , KLEVS=NCSS  , KTILES=NTILES, KVTYPES=NVHILO & 
     & , KLEV=IFLEV  ,KSTART=NSTART ,KSTEP=NSTEP  ,KTRAC=NTRAC   &
     & , KLEVI=NLEVI  ,KLEVO=NCOM   ,KLEVSN=NCSNEC          &                 !KPP
     & , KDHVTLS=NDHVTLS,KDHFTLS=NDHFTLS,KDHVTSS=NDHVTSS,KDHFTSS=NDHFTSS &
     & , KDHVTTS=NDHVTTS,KDHFTTS=NDHFTTS,KDHVTIS=NDHVTIS,KDHFTIS=NDHFTIS &
     & , KDHVSSS=NDHVSSS,KDHFSSS=NDHFSSS,KDHVIIS=NDHVIIS,KDHFIIS=NDHFIIS &
     & , KDHVWLS=NDHVWLS,KDHFWLS=NDHFWLS,KDHVRESS=NDHVRESS,KDHFRESS=NDHFRESS &
     & , KDHVCO2S=NDHVCO2S,KDHFCO2S=NDHFCO2S &
     & , KDHVBIOS=NDHVBIOS,KDHFBIOS=NDHFBIOS,KDHVBVOCS=NDHVBVOCS,KDHVVEGS=NDHVVEGS,KDHFVEGS=NDHFVEGS  &
     & , PTSPHY=TDT &
!-----------------------------------------------------------------------
! - INPUT .
     & , LLKEYS=LLKEYS &
! - OUTPUT .
     & , PSURF=PSURF, PSURFL=PSURFL, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX &
     & , PDIAG=PDIAG, PINTER=PINTER,  STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)


!* CTESSEL >
!*           UPDATE DIAGNOSTICS
!     ------------------------------------------------------------------

  CALL UPDDIAG_LAYER( &
   & IST=IST,IEND=IEND,IBL=IBL,IPROMA=IPROMA, &
   & KIDIA=1, KFDIA=NPOI, KLON=NPROMA, KLEV=IFLEV, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES,  & 
   & PTSPHY=TDT, &
   & PPSURF=PNLP1, &
   & PSURF=PSURF, PSURFL=PSURFL, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX, PDIAG=PDIAG, STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)

!*       3.  COMPUTATION OF T+DT VALUES FOR SURFACE VARIABLES.
!            -------------------------------------------------
! WARM START FIX
  IF (NSTEP == 0) THEN 
    GP1(1:IPROMA, MRSNNU:MRSNNU+NCSNEC-1,IBL) = RSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MTSNNU:MTSNNU+NCSNEC-1,IBL) = TSNNU0(1:IPROMA, 1:NCSNEC, IBL)
    GP1(1:IPROMA, MFSNNU:MFSNNU+NCSNEC-1,IBL) = FSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MWSNNU:MWSNNU+NCSNEC-1,IBL) = WSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
  END IF

  GP1(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL) + TDT*PSURF%ZGPE(1:IPROMA,1:NGPP,IBL)
!*       4.  SWAPPING OF SURFACE VARIABLES.
!            ------------------------------

  GP0(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL)

!*       5.   ACCUMULATE 1D DIAGNOSTIC TENDENCIES.
!             ------------------------------------

  DO J=1,N2DDI
    GDI1S(1:IPROMA,J,2,IBL)=GDI1S(1:IPROMA,J,2,IBL)+TSTEP*GDI1S(1:IPROMA,J,1,IBL)
  ENDDO

!*       6.   AVERAGE AUXILIARY DIAGNOSTICS
!             ------------------------------------

  DO J=1,N2DDIAUX
    GDIAUX1S(1:IPROMA,J,2,IBL)=GDIAUX1S(1:IPROMA,J,2,IBL)+TSTEP*GDIAUX1S(1:IPROMA,J,1,IBL)
  ENDDO

ENDDO !IST LOOP
!$OMP END PARALLEL DO 


!     ------------------------------------------------------------------
!These shall be called at the last timestep only
!CALL PSURF%FINAL
!CALL PSURFL%FINAL
!CALL PDIAG%FINAL
!CALL PAUXL%FINAL
!CALL PAUX%FINAL
!CALL PFLUX%FINAL
!CALL STATE%FINAL
!CALL GEMSL%FINAL
!CALL LLKEYS%FINAL
!CALL PDDHS%FINAL

END ASSOCIATE
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('ECLAND_DRV_UNSPLIT_LAYER',1,ZHOOK_HANDLE)

END SUBROUTINE ECLAND_DRV_UNSPLIT_LAYER
