MODULE ECLAND_ATMO_TYPE_MOD

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMGF1S , ONLY: UNLEV0   ,VNLEV0   ,TNLEV0   ,QNLEV0   ,&
     &              PNLP0    ,UNLEV1   ,VNLEV1   ,TNLEV1   ,QNLEV1

IMPLICIT NONE

TYPE ATMO_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PGEOM1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PAPRS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU => NULL(),PV => NULL(),PT => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU1=> NULL(),PV1=> NULL(),PT1=> NULL() ! GMV fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ  => NULL() ! GFL fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ1 => NULL() ! GFL fields

CONTAINS
  PROCEDURE :: INIT  => ATMO_TYPE_INIT
  PROCEDURE :: FINAL => ATMO_TYPE_FINAL
END TYPE ATMO_TYPE

CONTAINS

  SUBROUTINE ATMO_TYPE_INIT(SELF,NPROMA,NLEV,NBLOCKS) 
    CLASS(ATMO_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NLEV,NBLOCKS

    SELF%PU =>UNLEV0
    SELF%PV =>VNLEV0
    SELF%PT =>TNLEV0
    SELF%PQ =>QNLEV0
    SELF%PU1=>UNLEV1
    SELF%PV1=>VNLEV1
    SELF%PT1=>TNLEV1
    SELF%PQ1=>QNLEV1

    ALLOCATE(SELF%PAPRS(NPROMA,0:NLEV,NBLOCKS))    
    ALLOCATE(SELF%PGEOM1(NPROMA,NLEV,NBLOCKS)) 
  END SUBROUTINE ATMO_TYPE_INIT

  SUBROUTINE ATMO_TYPE_FINAL(SELF)
    CLASS(ATMO_TYPE) :: SELF

    DEALLOCATE(SELF%PAPRS)
    DEALLOCATE(SELF%PGEOM1)

    NULLIFY(SELF%PU)
    NULLIFY(SELF%PV)
    NULLIFY(SELF%PT)
    NULLIFY(SELF%PQ)
    NULLIFY(SELF%PU1)
    NULLIFY(SELF%PV1)
    NULLIFY(SELF%PT1)
    NULLIFY(SELF%PQ1)
    NULLIFY(SELF%PAPRS)
    NULLIFY(SELF%PGEOM1)
  END SUBROUTINE ATMO_TYPE_FINAL

END MODULE ECLAND_ATMO_TYPE_MOD
