MODULE ECLAND_AUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGC1S  , ONLY : GEMU     ,GELAM    ,GELAT

IMPLICIT NONE

TYPE AUX_TYPE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PGEOM1 => NULL() !
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: PAPRS  => NULL() ! half level pressure
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: GELAT  => NULL() ! PLAT ! PGELAT  
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: GELAM  => NULL() ! PGELAM
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PMU0M  => NULL() ! PMU0 ! local cosine of instantaneous (mean) solar zenith angle
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PGEMU  => NULL() ! sine of latitude 

CONTAINS
  PROCEDURE :: INIT  => AUX_TYPE_INIT
  PROCEDURE :: FINAL => AUX_TYPE_FINAL
END TYPE AUX_TYPE

TYPE KEYS_LOCAL_TYPE
  LOGICAL, DIMENSION(:,:), POINTER  :: LLLAND, LLSICE, LLLICE, LLNH  
  LOGICAL, DIMENSION(:,:), POINTER  :: LLLAKE, LLOCN_KPP
CONTAINS
  PROCEDURE :: INIT => KEYS_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => KEYS_LOCAL_TYPE_FINAL
END TYPE KEYS_LOCAL_TYPE

CONTAINS

  SUBROUTINE AUX_TYPE_INIT(SELF,NPROMA,NLEV,NBLOCKS)
    CLASS(AUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NLEV,NBLOCKS

    SELF%PGEMU => GEMU 
    SELF%GELAT => GELAT
    SELF%GELAM => GELAM

    ALLOCATE(SELF%PMU0M(NPROMA,NBLOCKS))    
    ALLOCATE(SELF%PAPRS(NPROMA,0:NLEV,NBLOCKS))    
    ALLOCATE(SELF%PGEOM1(NPROMA,NLEV,NBLOCKS))    
  END SUBROUTINE AUX_TYPE_INIT

  SUBROUTINE AUX_TYPE_FINAL(SELF)
     CLASS(AUX_TYPE) :: SELF

     NULLIFY(SELF%PGEMU)
     NULLIFY(SELF%GELAT)
     NULLIFY(SELF%GELAM)

     DEALLOCATE(SELF%PMU0M)
     DEALLOCATE(SELF%PAPRS)
     DEALLOCATE(SELF%PGEOM1)
  END SUBROUTINE AUX_TYPE_FINAL

  SUBROUTINE KEYS_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS) 
    CLASS(KEYS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS

    ALLOCATE(SELF%LLLAND(NPROMA,NBLOCKS))    
    ALLOCATE(SELF%LLSICE(NPROMA,NBLOCKS))    
    ALLOCATE(SELF%LLNH(NPROMA,NBLOCKS))    
    ALLOCATE(SELF%LLLICE(NPROMA,NBLOCKS))    
    ALLOCATE(SELF%LLLAKE(NPROMA,NBLOCKS))    
    ALLOCATE(SELF%LLOCN_KPP(NPROMA,NBLOCKS))    

  END SUBROUTINE KEYS_LOCAL_TYPE_INIT

  SUBROUTINE KEYS_LOCAL_TYPE_FINAL(SELF)
    CLASS(KEYS_LOCAL_TYPE) :: SELF
    DEALLOCATE(SELF%LLLAND)
    DEALLOCATE(SELF%LLSICE)
    DEALLOCATE(SELF%LLNH)
    DEALLOCATE(SELF%LLLICE)
    DEALLOCATE(SELF%LLLAKE)
    DEALLOCATE(SELF%LLOCN_KPP)
  END SUBROUTINE KEYS_LOCAL_TYPE_FINAL

END MODULE ECLAND_AUX_TYPE_MOD
