MODULE ECLAND_AUX_DIAG_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

TYPE AUX_DIAG_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PVDIS => NULL()      ! Vert-integrated turbulent dissipation rate (W/m2)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PGUST => NULL()! PI10FG     ! WIND GUST AT 10 m FOR CURRENT TIME LEVEL (m/s)
  !    additional turbulence diagnostics
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZINV => NULL()         ! convective turbulent mixing height

CONTAINS
  PROCEDURE :: INIT  => AUX_DIAG_TYPE_INIT
  PROCEDURE :: FINAL => AUX_DIAG_TYPE_FINAL
END TYPE AUX_DIAG_TYPE

TYPE AUX_DIAG_LOCAL_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZPAPSRF => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZWND    => NULL()    ! horizontal wind in the lowest model level
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZCCNL => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZCCNO => NULL()

CONTAINS
  PROCEDURE :: INIT  => AUX_DIAG_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => AUX_DIAG_LOCAL_TYPE_FINAL
END TYPE AUX_DIAG_LOCAL_TYPE

CONTAINS

 SUBROUTINE AUX_DIAG_TYPE_INIT(SELF, NPROMA, NBLOCKS)
    CLASS(AUX_DIAG_TYPE) :: SELF

    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS
    ALLOCATE(SELF%PGUST(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZINV(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PVDIS(NPROMA,NBLOCKS))

 END SUBROUTINE AUX_DIAG_TYPE_INIT

 SUBROUTINE AUX_DIAG_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_TYPE) :: SELF

    DEALLOCATE(SELF%PGUST)
    DEALLOCATE(SELF%ZINV)
    DEALLOCATE(SELF%PVDIS)

    NULLIFY(SELF%PGUST)
    NULLIFY(SELF%ZINV)
    NULLIFY(SELF%PVDIS)
 END SUBROUTINE AUX_DIAG_TYPE_FINAL

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS

    ALLOCATE(SELF%ZPAPSRF(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZWND(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCCNL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCCNO(NPROMA,NBLOCKS))

  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF

    DEALLOCATE(SELF%ZPAPSRF)
    DEALLOCATE(SELF%ZWND)
    DEALLOCATE(SELF%ZCCNL)
    DEALLOCATE(SELF%ZCCNO)

    NULLIFY(SELF%ZPAPSRF)
    NULLIFY(SELF%ZWND)
    NULLIFY(SELF%ZCCNL)
    NULLIFY(SELF%ZCCNO)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL

END MODULE ECLAND_AUX_DIAG_TYPE_MOD
