MODULE ECLAND_FLUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGF1S, ONLY : FCRF,FCSF,FLSRF,FLSSF

IMPLICIT NONE

TYPE FLUX_TYPE
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PDIFTQ     ! TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PDIFTS     ! TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFPLCL     ! CONVECTIVE PRECIPITATION AS RAIN.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFPLCN     ! CONVECTIVE PRECIPITATION AS SNOW.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFPLSL     ! STRATIFORM PRECIPITATION AS RAIN.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFPLSN     ! STRATIFORM PRECIPITATION AS SNOW.
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PFRSO      ! SHORTWAVE RADIATIVE FLUX.
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PFRTH      ! LONGWAVE RADIATIVE FLUX.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: ZFRTH      ! LONGWAVE RADIATIVE FLUX.
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSTRTU,PSTRTV ! TURBULENT FLUX OF MOMENTUM (U and V)
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFTG12!PTSDFL          ! HEAT FLUX FROM LAYER 1 TO 2  ! NOT USED
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFWG12 !PWFSD          ! WATER FLUX FROM LAYER 1 TO 2  ! NOT USED
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFWEV           ! SURFACE WATER VAPOUR FLUX (EVAPORATION)
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFWSB           ! SURFACE WATER VAPOUR FLUX (SUBLIMATION)
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFWMLT !PFMLT         ! WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFWROD          ! RUN-OFF FLUX AT DEEPER LAYERS (2-4)
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFWRO1          ! RUN-OFF FLUX AT LAYER 1
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFTLHEV         ! SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
    REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PFTLHSB         ! SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
    REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZENES !PENES         !  ???

CONTAINS
  PROCEDURE :: INIT => FLUX_TYPE_INIT
  PROCEDURE :: FINAL => FLUX_TYPE_FINAL
END TYPE FLUX_TYPE

CONTAINS

  SUBROUTINE FLUX_TYPE_INIT(SELF, NPROMA, NLEV,  NCSS, NBLOCKS)
    CLASS(FLUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NCSS, NBLOCKS

    SELF%PFPLCL=>FCRF
    SELF%PFPLCN=>FCSF
    SELF%PFPLSL=>FLSRF
    SELF%PFPLSN=>FLSSF

    ALLOCATE(SELF%ZENES(NPROMA,NCSS,NBLOCKS))
    ALLOCATE(SELF%PDIFTQ(NPROMA,0:NLEV,NBLOCKS))
    ALLOCATE(SELF%PDIFTS(NPROMA,0:NLEV,NBLOCKS))
    ALLOCATE(SELF%PFRSO(NPROMA,0:NLEV,NBLOCKS))
    ALLOCATE(SELF%PFRTH(NPROMA,0:NLEV,NBLOCKS))
    ALLOCATE(SELF%ZFRTH(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PSTRTU(NPROMA,0:NLEV,NBLOCKS))
    ALLOCATE(SELF%PSTRTV(NPROMA,0:NLEV,NBLOCKS))
    ALLOCATE(SELF%PFTG12(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PFWEV(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PFWSB(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PFWG12(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PFWMLT(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PFWROD(NPROMA,NBLOCKS)) 
    ALLOCATE(SELF%PFWRO1(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PFTLHEV(NPROMA,NBLOCKS)) 
    ALLOCATE(SELF%PFTLHSB(NPROMA,NBLOCKS))

  END SUBROUTINE FLUX_TYPE_INIT

  SUBROUTINE FLUX_TYPE_FINAL(SELF)
    CLASS(FLUX_TYPE) :: SELF
    DEALLOCATE(SELF%ZENES)
    DEALLOCATE(SELF%PDIFTQ)
    DEALLOCATE(SELF%PDIFTS)
    DEALLOCATE(SELF%PFRSO)
    DEALLOCATE(SELF%PFRTH)
    DEALLOCATE(SELF%ZFRTH)
    DEALLOCATE(SELF%PSTRTU)
    DEALLOCATE(SELF%PSTRTV)
    DEALLOCATE(SELF%PFTG12)
    DEALLOCATE(SELF%PFWEV)
    DEALLOCATE(SELF%PFWSB)
    DEALLOCATE(SELF%PFWG12)
    DEALLOCATE(SELF%PFWMLT)
    DEALLOCATE(SELF%PFWROD)
    DEALLOCATE(SELF%PFWRO1)
    DEALLOCATE(SELF%PFTLHEV)
    DEALLOCATE(SELF%PFTLHSB)

  END SUBROUTINE FLUX_TYPE_FINAL

END MODULE ECLAND_FLUX_TYPE_MOD
