MODULE ECLAND_ATMO_TYPE_MOD

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMGF1S , ONLY: UNLEV0   ,VNLEV0   ,TNLEV0   ,QNLEV0   ,&
     &              PNLP0    ,UNLEV1   ,VNLEV1   ,TNLEV1   ,QNLEV1

IMPLICIT NONE

TYPE ATMO_TYPE

  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU,PV,PT      ! GMV fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PU1,PV1,PT1      ! GMV fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ ! GFL fields
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER :: PQ1 ! GFL fields

CONTAINS
  PROCEDURE :: INIT => ATMO_TYPE_INIT
  PROCEDURE :: FINAL => ATMO_TYPE_FINAL
END TYPE ATMO_TYPE

CONTAINS

  SUBROUTINE ATMO_TYPE_INIT(SELF) 
    CLASS(ATMO_TYPE) :: SELF

    SELF%PU=>UNLEV0
    SELF%PV=>VNLEV0
    SELF%PT=>TNLEV0
    SELF%PQ=>QNLEV0
    SELF%PU1=>UNLEV1
    SELF%PV1=>VNLEV1
    SELF%PT1=>TNLEV1
    SELF%PQ1=>QNLEV1

  END SUBROUTINE ATMO_TYPE_INIT

  SUBROUTINE ATMO_TYPE_FINAL(SELF)
    CLASS(ATMO_TYPE) :: SELF

  END SUBROUTINE ATMO_TYPE_FINAL

END MODULE ECLAND_ATMO_TYPE_MOD
