
SUBROUTINE ECLAND_DRV_LAYER

USE YOMDPHY  ,  ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, &
      &                 NVHILO, NGPP, NPOI, NLEV, NBLOCKS  
USE YOMCDH1S  , ONLY : NLEVI, NDHFCO2S , &
      &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
      &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
      &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
      &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
      &  NDHVCO2S,NDHFCO2S, &
      &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS
USE YOMDYN1S , ONLY : NSTEP    ,TDT,TSTEP
USE YOMGPD1S , ONLY : VFSST, VFALUVI,  VFALUVV, VFALUVG,&
      &            VFALNII, VFALNIV, VFALNIG, VFALUVP, VFALUVD, &
      &            VFALNIP, VFALNID, VFZ0F, VFZ0H, VFAVGPAR, &
      &            GPD_SDP2, GPD_SDP3
USE YOMGF1S  , ONLY : PNLP0, PNLP1, RALT
USE YOMGP1S0 , ONLY : GP0, TONU0, RSNNU0, TSNNU0, FSNNU0, WSNNU0, LAINU0 
USE YOMGP1S1 , ONLY : GP1, LAINU1
USE PTRGP1S  , ONLY : MFSNNU, MRSNNU, MTSNNU, MWSNNU  
USE YOMLOG1S,   ONLY: IDBGS1
USE YOMCT01S , ONLY : NSTART
USE YOMCST   , ONLY : RG
USE YOERIP   , ONLY : RCODECM  ,RSIDECM  ,RCOVSRM  ,RSIVSRM
USE YOERAD   , ONLY : NTSW, NLWEMISS
USE YOMDIM1S , ONLY : NPROMA
!
USE YOEPHY   , ONLY :  NALBEDOSCHEME, LBVOC_EMIS
!
USE YOMGDI1S , ONLY : GDI1S    ,N2DDI ,&
                      &GDIAUX1S ,N2DDIAUX

USE YOMLUN1S, ONLY : NULOUT
USE YOMSURF_SSDP_MOD, ONLY : NSSDP2D, NSSDP3D

USE ECLAND_SURFACE_TYPE_MOD, ONLY: SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD, ONLY: DDH_SURF_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD, ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_FLUX_TYPE_MOD, ONLY: FLUX_TYPE
USE ECLAND_STATE_TYPE_MOD, ONLY: STATE_TYPE
USE ECLAND_GEMS_TYPE_MOD, ONLY: GEMS_LOCAL_TYPE

USE CALLPAR1S_LAYER_MOD, ONLY: CALLPAR1S_LAYER_OPENMP
USE UPDIAG_LAYER_MOD, ONLY: UPDDIAG_LAYER_OPENMP
USE OMP_LIB


#ifdef DOC
! (C) Copyright 1995- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *CPG1S* - Grid point calculations.

!     Purpose.
!     --------
!           Grid point calculations .

!**   Interface.
!     ----------
!        *CALL* *CPG1S*

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Called by STEPO1S.

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the one column model

!     Author.
!     -------
!        Pedro Viterbo   *ECMWF*

!     Modifications.
!     --------------
!        Original : 95-03-21
!        Bart vd Hurk (KNMI): multi-column setup
!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on:
!        Marita Voogt (KNMI) "C-Tessel" 09/2005
!        Sebastien Lafont (ECMWF) "C-TESSEL"

!     ------------------------------------------------------------------
#endif
USE PARKIND1  ,ONLY : JPIM     ,JPRB,    JPRD
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK
IMPLICIT NONE


CHARACTER*1 :: CDCONF 
INTEGER(KIND=JPIM) :: IST,IEND,IPROMA,IFLEV, IBL, NTHREADS
INTEGER(KIND=JPIM) :: JL,J
! INTEGER(KIND=JPIM) :: OMP_GET_MAX_THREADS

TYPE(SURF_AND_MORE_TYPE),SAVE :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE),SAVE :: PSURFL
TYPE(AUX_DIAG_TYPE),SAVE :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE),SAVE :: PAUXL
TYPE(AUX_TYPE),SAVE :: PAUX
TYPE(FLUX_TYPE),SAVE :: PFLUX
TYPE(STATE_TYPE),SAVE :: STATE
TYPE(GEMS_LOCAL_TYPE),SAVE :: GEMSL
TYPE(KEYS_LOCAL_TYPE),SAVE :: LLKEYS
TYPE(DDH_SURF_TYPE),SAVE :: PDDHS

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CPG1S',0,ZHOOK_HANDLE)


!     ------------------------------------------------------------------

IF (NSTEP.EQ.NSTART) THEN
CALL PSURF%INIT(NPROMA, NGPP,NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS)
CALL PSURFL%INIT(NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
CALL PDIAG%INIT(NPROMA, NBLOCKS)
CALL PAUXL%INIT(NPROMA, NBLOCKS)
CALL PAUX%INIT(NPROMA,NLEV,NBLOCKS)
CALL PFLUX%INIT(NPROMA, NLEV, NCSS, NBLOCKS)
CALL STATE%INIT()
CALL GEMSL%INIT(NPROMA,NBLOCKS,NTRAC,NDHVBVOCS)
CALL LLKEYS%INIT(NPROMA,NBLOCKS)
CALL PDDHS%INIT(NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )

ENDIF
ASSOCIATE(LEOCML=>YSURF%YOCEAN_ML%LEOCML,RTT=>YSURF%YCST%RTT)
ASSOCIATE(GEMU=>PAUX%PGEMU,GELAM=>PAUX%GELAM,ZMU0M=>PAUX%PMU0M,ZAPHIF=>PAUX%PGEOM1,ZAPRS=>PAUX%PAPRS)
ASSOCIATE(ZCFLX=>GEMSL%PCFLX)

! Some initialisations
!ZDHRESS(:,:,:,:)=0._JPRB
!PDDHS%PDHTTS(:,:,:,:)=0._JPRB
!PDDHS%PDHVEGS(:,:,:,:)=0._JPRB

! Allocate variables
!ALLOCATE (ZGPE(NPROMA,NGPP,NBLOCKS))
!ZTSAE1 = ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)
!ZWSAE1 = ZGPE(:,MQLINU:MQLINU+NCSS-1,:)
!ZSNSE1 = ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:)
!ZTSNE1 = ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:)
!ZWSNE1 = ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:)
!ZRSNE1 = ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:)
!ZASNE1 = ZGPE(:,MASNNU,:)
!ZTLE1  = ZGPE(:,MTRENU,:)
!ZWLE1  = ZGPE(:,MWRENU,:)
!ZTILE1 = ZGPE(:,MTILNU:MTILNU+NCSS-1,:)
!
!!* < FLAKE
!ZTLICENE1 = ZGPE(:,MTLICENU,:)
!ZTLMNWNE1 = ZGPE(:,MTLMNWNU,:)
!ZTLWMLNE1 = ZGPE(:,MTLWMLNU,:)
!ZTLBOTNE1 = ZGPE(:,MTLBOTNU,:)
!ZTLSFNE1  = ZGPE(:,MTLSFNU,:)
!ZHLICENE1 = ZGPE(:,MHLICENU,:)
!ZHLMLNE1  = ZGPE(:,MHLMLNU,:)
!!* FLAKE > 
!
!ZUOE1 = ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  !KPP
!ZVOE1 = ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  !KPP
!ZTOE1 = ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  !KPP
!ZSOE1 = ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  !KPP

!UONUC(:,:)=0.0_JPRB     !KPP 
!VONUC(:,:)=0.0_JPRB     !KPP
!USTRCNU(:)=0.0_JPRB     !KPP
!VSTRNUC(:)=0.0_JPRB     !KPP
!
!!* < CTESSEL
!ZLAIE1 = ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)
!ZBSTRE1 = ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)
!ZBSTR2E1 = ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:)
!!* CTESSEL >



!*       1.    INITIAL COMPUTATIONS.
!              ---------------------


!     TIME STEP




!*       1.1  INITIALIZING SURFACE VARIABLES AT T-DT (FIRST TIMESTEP).
!             --------------------------------------------------------    

! --- original setting without openMP
!IST=1
!IEND=NPOI
!IPROMA=NPOI
! ---
IFLEV=NLEV
!$OMP PARALLEL
NTHREADS=OMP_GET_MAX_THREADS()
!$OMP END PARALLEL 

IF ( IDBGS1 > 1 ) THEN
  WRITE(NULOUT,*) 'CPG1S:',NPROMA,NPOI,NTHREADS
ENDIF

CALL NORMAL_TO_BLOCK()


!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1

  GP1(1:IPROMA,1:NGPP,IBL)=GP0(1:IPROMA,1:NGPP,IBL)

!     STAFF FOR CALLPAR1S

  ZAPHIF(1:IPROMA,:,IBL)=RG*RALT
  ZAPRS(1:IPROMA,IFLEV,IBL)=PNLP0(1:IPROMA,IBL)
  ZAPRS(1:IPROMA,IFLEV-1,IBL)=PNLP0(1:IPROMA,IBL)-RALT*0.0065_JPRB
! Added "MIN(1._JPRB , ... ) to computation of ZMU0M. This ensures ZMU0M is between physical boundaries.
  ZMU0M(1:IPROMA,IBL)=MIN(1._JPRB, MAX( RSIDECM*GEMU(1:IPROMA,IBL) &
     & -RCODECM*RCOVSRM*SQRT(1._JPRB-GEMU(1:IPROMA,IBL)**2)*COS(GELAM(1:IPROMA,IBL)) &
     & +RCODECM*RSIVSRM*SQRT(1._JPRB-GEMU(1:IPROMA,IBL)**2)*SIN(GELAM(1:IPROMA,IBL)) &
     & ,0._JPRB) )

  IF(LEOCML) THEN
! replace SST with the top layer temp. of the ocean mixed layer (~ 1m depth)
    VFSST(1:IPROMA,IBL) = TONU0(1:IPROMA,1,IBL) + RTT ! The unit of PSST(VFSST) is K.  
  ENDIF

!! init 
  ZCFLX(1:IPROMA,:,IBL) = 0._JPRB 

  PSURF%PUSTRC(:,IBL)=0.0_JPRB
  PSURF%PVSTRC(:,IBL)=0.0_JPRB
  PSURF%GSP%PUOC(:,:,IBL)=0.0_JPRB
  PSURF%GSP%PVOC(:,:,IBL)=0.0_JPRB
  PSURF%GSD%PSSDP2(1:IPROMA,:,IBL)  =GPD_SDP2(IST:IEND,:)
  PSURF%GSD%PSSDP3(1:IPROMA,:,:,IBL)=GPD_SDP3(IST:IEND,:,:)
  PSURF%GSP%PSST(1:IPROMA,IBL)=VFSST(1:IPROMA,IBL)
  PSURFL%PLAILI(:,IBL)=LAINU0(:,1,IBL)
  PSURFL%PLAIHI(:,IBL)=LAINU0(:,2,IBL)

    IF (NALBEDOSCHEME == 2) THEN
      ! 6 components
      PSURF%GSD%ZALCOEFF(1:IPROMA,1,IBL) = VFALUVI(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,2,IBL) = VFALUVV(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,3,IBL) = VFALUVG(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,4,IBL) = VFALNII(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,5,IBL) = VFALNIV(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,6,IBL) = VFALNIG(1:IPROMA,IBL)
    ELSE
      ! 4 components
      PSURF%GSD%ZALCOEFF(1:IPROMA,1,IBL) = VFALUVP(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,2,IBL) = VFALUVD(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,3,IBL) = VFALNIP(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,4,IBL) = VFALNID(1:IPROMA,IBL)
    ENDIF
!*       1.1   FIRST TIME-STEP
IF (NSTEP.EQ.NSTART) THEN
  GEMSL%PZ0M(1:IPROMA,IBL)=MAX(0.001_JPRB ,VFZ0F(1:IPROMA,IBL))! PZ0MCL(IST:IEND))
  GEMSL%PZ0H(1:IPROMA,IBL)=MAX(0.0001_JPRB,VFZ0H(1:IPROMA,IBL))!PZ0HCL(IST:IEND))
ENDIF

!* Initialize dummy AVGPAR array, fill with zero if no BVOC emissions
!      PSURF%GSD%ZAVGPARC=>ZAVGPARC
IF ( LBVOC_EMIS ) THEN
      PSURF%GSD%ZAVGPARC(1:IPROMA,IBL) = VFAVGPAR(1:IPROMA,IBL) ! W/m2
ELSE
      PSURF%GSD%ZAVGPARC(1:IPROMA,IBL) = 0._JPRB
ENDIF
ENDDO !IST LOOP
!$OMP END PARALLEL DO 

!*      2.   CALL PHYSICS.
!            -------------
  CDCONF='F'
  CALL CALLPAR1S_LAYER_OPENMP (CDCONF=CDCONF &
     & , KIDIA=1, KFDIA=NPOI   , KLON=NPROMA , KLEVS=NCSS  , KTILES=NTILES, KVTYPES=NVHILO & 
     & , KLEV=IFLEV  ,KSTART=NSTART ,KSTEP=NSTEP  ,KTRAC=NTRAC   &
     & , KLEVI=NLEVI  ,KLEVO=NCOM   ,KLEVSN=NCSNEC          &                 !KPP
     & , KDHVTLS=NDHVTLS,KDHFTLS=NDHFTLS,KDHVTSS=NDHVTSS,KDHFTSS=NDHFTSS &
     & , KDHVTTS=NDHVTTS,KDHFTTS=NDHFTTS,KDHVTIS=NDHVTIS,KDHFTIS=NDHFTIS &
     & , KDHVSSS=NDHVSSS,KDHFSSS=NDHFSSS,KDHVIIS=NDHVIIS,KDHFIIS=NDHFIIS &
     & , KDHVWLS=NDHVWLS,KDHFWLS=NDHFWLS,KDHVRESS=NDHVRESS,KDHFRESS=NDHFRESS &
     & , KDHVCO2S=NDHVCO2S,KDHFCO2S=NDHFCO2S &
     & , KDHVBIOS=NDHVBIOS,KDHFBIOS=NDHFBIOS,KDHVBVOCS=NDHVBVOCS,KDHVVEGS=NDHVVEGS,KDHFVEGS=NDHFVEGS  &
     & , PTSPHY=TDT &
!-----------------------------------------------------------------------
! - INPUT .
     & , LLKEYS=LLKEYS &
! - OUTPUT .
     & , PSURF=PSURF, PSURFL=PSURFL, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX, PDIAG=PDIAG, STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)


!  CALL BLOCK_TO_NORMAL
!* CTESSEL >
!*           UPDATE DIAGNOSTICS
!     ------------------------------------------------------------------

  CALL UPDDIAG_LAYER_OPENMP( &
   & KIDIA=1, KFDIA=NPOI, KLON=NPROMA, KLEV=IFLEV, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES,  & 
   & PTSPHY=TDT, &
   & PPSURF=PNLP1, &
   & PSURF=PSURF, PSURFL=PSURFL, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX, PDIAG=PDIAG, STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(IST,IEND,IBL,IPROMA) SHARED(GP0,GP1,GDI1S,GDIAUX1S)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1
!*       3.  COMPUTATION OF T+DT VALUES FOR SURFACE VARIABLES.
!            -------------------------------------------------
! WARM START FIX
  IF (NSTEP == 0) THEN 
    GP1(1:IPROMA, MRSNNU:MRSNNU+NCSNEC-1,IBL) = RSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MTSNNU:MTSNNU+NCSNEC-1,IBL) = TSNNU0(1:IPROMA, 1:NCSNEC, IBL)
    GP1(1:IPROMA, MFSNNU:MFSNNU+NCSNEC-1,IBL) = FSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MWSNNU:MWSNNU+NCSNEC-1,IBL) = WSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
  END IF

  GP1(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL) + TDT*PSURF%ZGPE(1:IPROMA,1:NGPP,IBL)
!*       4.  SWAPPING OF SURFACE VARIABLES.
!            ------------------------------

  GP0(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL)

!*       5.   ACCUMULATE 1D DIAGNOSTIC TENDENCIES.
!             ------------------------------------

  DO J=1,N2DDI
    GDI1S(1:IPROMA,J,2,IBL)=GDI1S(1:IPROMA,J,2,IBL)+TSTEP*GDI1S(1:IPROMA,J,1,IBL)
  ENDDO

!*       6.   AVERAGE AUXILIARY DIAGNOSTICS
!             ------------------------------------

  DO J=1,N2DDIAUX
    GDIAUX1S(1:IPROMA,J,2,IBL)=GDIAUX1S(1:IPROMA,J,2,IBL)+TSTEP*GDIAUX1S(1:IPROMA,J,1,IBL)
  ENDDO

ENDDO !IST LOOP
!$OMP END PARALLEL DO 


!     ------------------------------------------------------------------

!CALL PSURF%FINAL
!CALL PSURFL%FINAL
!CALL PDIAG%FINAL
!CALL PAUXL%FINAL
!CALL PAUX%FINAL
!CALL PFLUX%FINAL
!CALL STATE%FINAL
!CALL GEMSL%FINAL
!CALL LLKEYS%FINAL
!CALL PDDHS%FINAL
END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPG1S',1,ZHOOK_HANDLE)
CONTAINS
SUBROUTINE NORMAL_TO_BLOCK
! ZVFISOP_EP=VFISOP_EP
! PSURF%PISOP_EP=>ZVFISOP_EP
! ZVFFWET=VFFWET
! PSURF%PFWET=>ZVFFWET
! ZVFAVGPAR=VFAVGPAR
! PSURF%ZAVGPAR=>ZVFAVGPAR
! ZVFSDOR=VFSDOR
! PSURF%PSDOR=>ZVFSDOR
! ZVFCIL=VFCIL
! PSURF%PCIL=>ZVFCIL
! ZVDIEWSSTL=VDIEWSSTL
! PSURF%PUSTRTI=>ZVDIEWSSTL
! ZVDINSSSTL=VDINSSSTL
! PSURF%PVSTRTI=>ZVDINSSSTL
! ZVDISSHFTL=VDISSHFTL
! PSURF%PAHFSTI=>ZVDISSHFTL
! ZVDIETL=VDIETL
! PSURF%PEVAPTI=>ZVDIETL
! ZVDTSKTL=VDTSKTL
! PSURF%PTSKTI=>ZVDTSKTL
! ZVDRESPBSTR=VDRESPBSTR
! PSURF%PRESPBSTR=>ZVDRESPBSTR 
! ZVDRESPBSTR2=VDRESPBSTR
! PSURF%PRESPBSTR2=>ZVDRESPBSTR2 
! ZVDBIOMASS_LAST=VDBIOMASS_LAST
! PSURF%PBIOMASS_LAST=>ZVDBIOMASS_LAST
! ZBSTRNU0=BSTRNU0
! PSURF%PBIOMASSTR_LAST=>ZBSTRNU0
! ZBSTR2NU0=BSTR2NU0
! PSURF%PBIOMASSTR2_LAST=>ZBSTR2NU0
! ZVDBLOSSVT=VDBLOSSVT
! PSURF%PBLOSSVT=>ZVDBLOSSVT
! ZVDBGAINVT=VDBGAINVT
! PSURF%PBGAINVT=>ZVDBGAINVT
! ZASNNU0=ASNNU0
! PSURF%GSP%PASN=>ZASNNU0
! ZTSNNU0=TSNNU0
! PSURF%GSP%PTSN=>ZTSNNU0
! ZTSLNU0=TSLNU0
! PSURF%GSP%PTSA=>ZTSLNU0
! ZTRENU0=TRENU0
! PSURF%GSP%PTL=>ZTRENU0
! ZQLINU0=QLINU0
! PSURF%GSP%PWSA=>ZQLINU0
! ZTILNU0=TILNU0
! PSURF%GSP%PTIA=>ZTILNU0
! ZTLICENU0=TLICENU0
! PSURF%GSP%PTLICE=>ZTLICENU0
! ZTLMNWNU0=TLMNWNU0
! PSURF%GSP%PTLMNW=>ZTLMNWNU0
! ZTLWMLNU0=TLWMLNU0
! PSURF%GSP%PTLWML=>ZTLWMLNU0
! ZTLBOTNU0=TLBOTNU0
! PSURF%GSP%PTLBOT=>ZTLBOTNU0
! ZTLSFNU0=TLSFNU0
! PSURF%GSP%PTLSF=>ZTLSFNU0
! ZHLICENU0=HLICENU0
! PSURF%GSP%PHLICE=>ZHLICENU0
! ZHLMLNU0=HLMLNU0
! PSURF%GSP%PHLML=>ZHLMLNU0
! ZUONU0=UONU0
! PSURF%GSP%PUO0=>ZUONU0
! ZVONU0=VONU0
! PSURF%GSP%PVO0=>ZVONU0
! ZTONU0=TONU0
! PSURF%GSP%PTO0=>ZTONU0
! ZSONU0=SONU0
! PSURF%GSP%PSO0=>ZSONU0
! ZVFLDEPTH=VFLDEPTH
! PSURF%GSD%PLDEPTH=>ZVFLDEPTH
! ZVFCLAKEF=VFCLAKEF
! PSURF%GSD%PCLAKE=>ZVFCLAKEF
! ZVFALBF=VFALBF
! PSURF%GSD%PALBF=>ZVFALBF  
! ZVFCVL=VFCVL
! PSURF%GSD%PCVL=>ZVFCVL
! ZVFCVH=VFCVH
! PSURF%GSD%PCVH=>ZVFCVH
! ZVFCUR=VFCUR
! PSURF%GSD%PCUR=>ZVFCUR
! ZVFTVL=VFTVL
! PSURF%GSD%PTVL=>ZVFTVL
! ZVFCO2TYP=VFCO2TYP
! PSURF%GSD%PCO2TYP=>ZVFCO2TYP
! ZVFTVH=VFTVH
! PSURF%GSD%PTVH=>ZVFTVH
! ZVFLAIL=VFLAIL
! PSURF%GSD%PLAILC=>ZVFLAIL
! ZVFLAIH=VFLAIH
! PSURF%GSD%PLAIHC=>ZVFLAIH
! ZVFSOTY=VFSOTY
! PSURF%GSD%PSOTY=>ZVFSOTY
! ZVFCI=VFCI
! PSURF%GSD%PCI=>ZVFCI
! ZVFITM=VFITM
! PSURF%GSD%PLSM=>ZVFITM
! ZVFZO=VFZO
! PSURF%GSD%PZO=>ZVFZO
! ZVFHO=VFHO
! PSURF%GSD%PHO=>ZVFHO
! ZVFHO_INV=VFHO_INV
! PSURF%GSD%PHO_INV=>ZVFHO_INV
! ZVFDO=VFDO
! PSURF%GSD%PDO=>ZVFDO
! ZVFOCDEPTH=VFOCDEPTH
! PSURF%GSD%POCDEPTH=>ZVFOCDEPTH
! ZVFADVT=VFADVT
! PSURF%GSD%PADVT=>ZVFADVT
! ZVFADVS=VFADVS
! PSURF%GSD%PADVS=>ZVFADVS 
! ZVFTRI0=VFTRI0
! PSURF%GSD%PTRI0=>ZVFTRI0
! ZVFTRI1=VFTRI1
! PSURF%GSD%PTRI1=>ZVFTRI1
! ZVFSWDK_SAVE=VFSWDK_SAVE
! PSURF%GSD%PSWDK_SAVE=>ZVFSWDK_SAVE
! ZVDALB=VDALB
! PSURF%GSD%PALB=>ZVDALB
!  PSURF%PUSTRC=>ZPUSTRC 
!  PSURF%PVSTRC=>ZPVSTRC
!! PSURF%PSRSOD=>FSSRD
!! PSURF%PSRTHD=>FSTRD
!  PSURF%ZCVL=>ZCVL
!  PSURF%ZCVH=>ZCVH
!  PSURF%ZCUR=>ZCUR
!  PSURF%PAN=>ZAN
!  PSURF%PAG=>ZAG
!  PSURF%PRD=>ZRD
!  PSURF%PRSOIL_STR=>ZRSOIL_STR
!  PSURF%PRECO=>ZRECO
!  PSURF%PCO2FLUX=>ZCO2FLUX
!  PSURF%PCH4FLUX=>ZCH4FLUX
!  PSURF%PLAI=>ZLAI
!  PSURF%ZEMIS=>ZEMIS
!  PSURF%ZLAILP=>ZLAILP
!  PSURF%ZLAIHP=>ZLAIHP
!  PSURF%ZCHAR=>ZCHAR
!  PSURF%ZCHARHQ=>ZCHARHQ
!  PSURF%ZUCURR=>ZUCURR
!  PSURF%ZVCURR=>ZVCURR
!  PSURF%PUSTOKES=>PUSTOKES
!  PSURF%PVSTOKES=>PVSTOKES
!  PSURF%GSD%PTAUOCX=>PTAUOCX
!  PSURF%GSD%PTAUOCY=>PTAUOCY
!  PSURF%PPHIOC=>PPHIOC
!  PSURF%PWSEMEAN=>PWSEMEAN
!  PSURF%PWSFMEAN=>PWSFMEAN
!  PSURF%PBIOM=>ZBIOM
!  PSURF%PBLOSS=>ZBLOSS
!  PSURF%PBGAIN=>ZBGAIN
!  PSURF%PBIOMSTR=>ZBIOMSTR
!  PSURF%PBIOMSTR2=>ZBIOMSTR2
!  PSURF%PDIFM=>ZDIFM
!  PSURF%PDIFT=>ZDIFT
!  PSURF%PDIFS=>ZDIFS
!  PSURF%PSNSE1=>ZSNSE1
!  PSURF%PASNE1=>ZASNE1
!  PSURF%PRSNE1=>ZRSNE1
!  PSURF%PTSNE1=>ZTSNE1
!  PSURF%PWSNE1=>ZWSNE1
!  PSURF%PTSAE1=>ZTSAE1
!  PSURF%PWLE1=>ZWLE1
!  PSURF%PTLE1=>ZTLE1
!  PSURF%PWSAE1=>ZWSAE1
!  PSURF%PTIAE1=>ZTILE1
!  PSURF%PTLICEE1=>ZTLICENE1
!  PSURF%PTLMNWE1=>ZTLMNWNE1
!  PSURF%PTLWMLE1=>ZTLWMLNE1
!  PSURF%PTLBOTE1=>ZTLBOTNE1
!  PSURF%PTLSFE1=>ZTLSFNE1
!  PSURF%PHLICEE1=>ZHLICENE1
!  PSURF%PHLMLE1=>ZHLMLNE1
!  PSURF%PUOE1=>ZUOE1
!  PSURF%PVOE1=>ZVOE1
!  PSURF%PTOE1=>ZTOE1
!  PSURF%PSOE1=>ZSOE1
!  PSURF%PLAIE1=>ZLAIE1
!  PSURF%PBSTRE1=>ZBSTRE1
!  PSURF%PBSTR2E1=>ZBSTR2E1
!  PSURF%ZTE => ZTE
!  PSURF%ZQE => ZQE
!  PSURF%ZVOM => ZVOM
!  PSURF%ZVOL => ZVOL
!  PSURF%ZTENC => ZTENC
!  PSURF%ITVL => ITVL
!  PSURF%ITVH => ITVH
!  PSURF%ISOTY => ISOTY
!  PSURF%ICO2TYP => ICO2TYP
!  PSURF%IVEG => IVEG
!  PSURF%GSP%PUOC=>ZPUOC
!  PSURF%GSP%PVOC=>ZPVOC
!  PSURF%GSP%PSST=>ZVFSST
!  PSURF%GSP%ZWS1=>ZWS1
!  PSURF%GSD%PSSDP2=>BLK_GPD_SDP2
!  PSURF%GSD%PSSDP3=>BLK_GPD_SDP3
!  PSURF%GSD%PEVAPTIU=>ZEVAPTIU
!  PSURF%GSD%PU10M=>ZU10M
!  PSURF%GSD%PV10M=>ZV10M
!  PSURF%GSD%PT2M=>ZT2M
!  PSURF%GSD%PD2M=>ZD2M
!  PSURF%GSD%PQ2M=>ZQ2M
!  PSURF%GSD%POTKE=>ZOTKE
!  PSURF%GSD%ZALCOEFF => ZALCOEFF 
!  PSURF%GSD%PALBICEF => PALBICEF 
!  PSURFL%PLAILI=>ZLAILI
!  PSURFL%PLAIHI=>ZLAIHI
!  PSURFL%ZLAIL=>ZLAIL
!  PSURFL%ZLAIH=>ZLAIH
!  ZWRENU0=WRENU0
!  PSURFL%PWL=>ZWRENU0
!  PSURFL%PZIDLWV=>ZZIDLWV
!  ZFSNNU0=FSNNU0
!  PSURFL%PSNS=>ZFSNNU0
!  ZRSNNU0=RSNNU0
!  PSURFL%PRSN=>ZRSNNU0
!  ZWSNNU0=WSNNU0
!  PSURFL%PWSN=>ZWSNNU0
!  PSURFL%ZTHKICE=>ZTHKICE
!  PSURFL%ZWLMX=>ZWLMX
!  PSURFL%ZCSN => ZCSN
!  PSURFL%ZCVT => ZCVT
!  PSURFL%ZLAIVT => ZLAIVT
!  PSURFL%ZKH=>ZKH
!  PSURFL%ZEXDIAG=>ZEXDIAG
!  PSURFL%ZSPECTRALEMISS=>ZSPECTRALEMISS
!  PSURFL%ZEVAPSNW=>ZEVAPSNW
!  PSURFL%ZFRTI=>ZFRTI
!  PSURFL%ZALBTI=>ZALBTI
!  PSURFL%ZFRSOTI=>ZFRSOTI
!  PSURFL%PSLRFLTI=>ZSLRFLTI
!  PSURFL%ZALBD=>ZALBD
!  PSURFL%ZALBP=>ZALBP
!  ZVDANDAYVT=VDANDAYVT
!  PSURFL%PANDAYVT=>ZVDANDAYVT
!  ZVDANFMVT=VDANFMVT
!  PSURFL%PANFMVT=>ZVDANFMVT
! PFLUX%PFPLCL=>FCRF
! PFLUX%PFPLCN=>FCSF
! PFLUX%PFPLSL=>FLSRF
! PFLUX%PFPLSN=>FLSSF
! PFLUX%ZENES=>ZENES
! PFLUX%PDIFTQ=>ZDIFTQ
! PFLUX%PDIFTS=>ZDIFTS
! PFLUX%PFRSO=>ZFRSO
! PFLUX%PFRTH=>PFRTH
! PFLUX%ZFRTH=>ZFRTH
! PFLUX%PSTRTU=>ZSTRTU
! PFLUX%PSTRTV=>ZSTRTV
! PFLUX%PFTG12=>ZFTG12
! PFLUX%PFWEV=>ZFWEV
! PFLUX%PFWSB=>ZFWSB
! PFLUX%PFWG12=>ZFWG12
! PFLUX%PFWMLT=>ZFWMLT
! PFLUX%PFWROD=>ZFWROD
! PFLUX%PFWRO1=>ZFWRO1
! PFLUX%PFTLHEV=>ZFTLHEV
! PFLUX%PFTLHSB=>ZFTLHSB
! GEMSL%PC=>CNLEV0
! GEMSL%PC1=>CNLEV1
! GEMSL%PCFLX=>ZCFLX
! GEMSL%PBVOCFLUX=>ZBVOCFLUX
! PDIAG%PGUST=>ZGUST
! PDIAG%PVDIS=>PVDIS
! PDIAG%ZINV=>ZINV
! STATE%PU=>UNLEV0
! STATE%PV=>VNLEV0
! STATE%PT=>TNLEV0
! STATE%PQ=>QNLEV0
! STATE%PU1=>UNLEV1
! STATE%PV1=>VNLEV1
! STATE%PT1=>TNLEV1
! STATE%PQ1=>QNLEV1
! PAUX%PGEMU=>GEMU 
! PAUX%GELAT=>GELAT
! PAUX%GELAM=>GELAM
! PAUX%PMU0M=>ZMU0M
! PAUX%PGEOM1=>ZAPHIF
! PAUX%PAPRS=>ZAPRS
!  PAUXL%ZPAPSRF=>ZPAPSRF
!  PAUXL%ZWND=>ZWND
!  PAUXL%ZCCNL=>ZCCNL
!  PAUXL%ZCCNO=>ZCCNO
! PDDHS%PDHTLS=>ZDHTLS
! PDDHS%PDHTSS=>ZDHTSS
! PDDHS%PDHSSS=>ZDHSSS
! PDDHS%PDHTTS=>ZDHTTS
! PDDHS%PDHWLS=>ZDHWLS
! PDDHS%PDHTIS=>ZDHTIS
! PDDHS%PDHIIS=>ZDHIIS
! PDDHS%PDHCO2S=>ZDHCO2S
! PDDHS%PDHBVOCS=>ZDHBVOCS
! PDDHS%PDHBIOS=>ZDHBIOS
! PDDHS%PDHVEGS=>ZDHVEGS
 !ZVDZ0F=VDZ0F
 !GEMSL%PZ0M=>ZVDZ0F
 !ZVDZ0H=VDZ0H
 !GEMSL%PZ0H=>ZVDZ0H

END SUBROUTINE NORMAL_TO_BLOCK

SUBROUTINE BLOCK_TO_NORMAL
! ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)   = ZTSAE1 
! ZGPE(:,MQLINU:MQLINU+NCSS-1,:)   = ZWSAE1 
! ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:) = ZSNSE1 
! ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:) = ZTSNE1 
! ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:) = ZWSNE1 
! ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:) = ZRSNE1 
! ZGPE(:,MASNNU,:)                 = ZASNE1 
! ZGPE(:,MTRENU,:)                 = ZTLE1  
! ZGPE(:,MWRENU,:)                 = ZWLE1  
! ZGPE(:,MTILNU:MTILNU+NCSS-1,:)   = ZTILE1 
!
!!* < FLAKE
! ZGPE(:,MTLICENU,:) = ZTLICENE1
! ZGPE(:,MTLMNWNU,:) = ZTLMNWNE1
! ZGPE(:,MTLWMLNU,:) = ZTLWMLNE1
! ZGPE(:,MTLBOTNU,:) = ZTLBOTNE1
! ZGPE(:,MTLSFNU,:)  = ZTLSFNE1 
! ZGPE(:,MHLICENU,:) = ZHLICENE1
! ZGPE(:,MHLMLNU,:)  = ZHLMLNE1 
!!* FLAKE > 
!
!ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  = ZUOE1 !KPP
!ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  = ZVOE1 !KPP
!ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  = ZTOE1 !KPP
!ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  = ZSOE1 !KPP
!
!!* < CTESSEL
!ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)     = ZLAIE1   
!ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)   = ZBSTRE1  
!ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:) = ZBSTR2E1 
!
!
!VFISOP_EP      = ZVFISOP_EP
!VFFWET         = ZVFFWET
!VFAVGPAR       = ZVFAVGPAR
!VFSDOR         = ZVFSDOR
!VFCIL          = ZVFCIL
!VDIEWSSTL      = ZVDIEWSSTL
!VDINSSSTL      = ZVDINSSSTL
!VDISSHFTL      = ZVDISSHFTL
!VDIETL         = ZVDIETL
!VDTSKTL        = ZVDTSKTL
!VDRESPBSTR     = ZVDRESPBSTR
!VDRESPBSTR     = ZVDRESPBSTR2
!VDBIOMASS_LAST = ZVDBIOMASS_LAST
!BSTRNU0        = ZBSTRNU0
!BSTR2NU0       = ZBSTR2NU0
!VDBLOSSVT      = ZVDBLOSSVT
!VDBGAINVT      = ZVDBGAINVT
!ASNNU0         = ZASNNU0
!TSNNU0         = ZTSNNU0
!TSLNU0         = ZTSLNU0
!TRENU0         = ZTRENU0
!QLINU0         = ZQLINU0
!TILNU0         = ZTILNU0
!TLICENU0       = ZTLICENU0
!TLMNWNU0       = ZTLMNWNU0
!TLWMLNU0       = ZTLWMLNU0
!TLBOTNU0       = ZTLBOTNU0
!TLSFNU0        = ZTLSFNU0
!HLICENU0       = ZHLICENU0
!HLMLNU0        = ZHLMLNU0
!UONU0          = ZUONU0
!VONU0          = ZVONU0
!TONU0          = ZTONU0
!SONU0          = ZSONU0
!VFSST          = ZVFSST
!VFLDEPTH       = ZVFLDEPTH
!VFCLAKEF       = ZVFCLAKEF
!VFALBF         = ZVFALBF
!VFCVL          = ZVFCVL
!VFCVH          = ZVFCVH
!VFCUR          = ZVFCUR
!VFTVL          = ZVFTVL
!VFCO2TYP       = ZVFCO2TYP
!VFTVH          = ZVFTVH
!VFLAIL         = ZVFLAIL
!VFLAIH         = ZVFLAIH
!VFSOTY         = ZVFSOTY
!VFCI           = ZVFCI
!VFITM          = ZVFITM
!VFZO           = ZVFZO
!VFHO           = ZVFHO
!VFHO_INV       = ZVFHO_INV
!VFDO           = ZVFDO
!VFOCDEPTH      = ZVFOCDEPTH
!VFADVT         = ZVFADVT
!VFADVS         = ZVFADVS
!VFTRI0         = ZVFTRI0
!VFTRI1         = ZVFTRI1
!VFSWDK_SAVE    = ZVFSWDK_SAVE
!VDALB          = ZVDALB
!FSNNU0         = ZFSNNU0
!RSNNU0         = ZRSNNU0
!WSNNU0         = ZWSNNU0
!WRENU0         = ZWRENU0
!VDANDAYVT      = ZVDANDAYVT
!VDANFMVT       = ZVDANFMVT
!LAINU0(:,1,:)  = ZLAILI
!LAINU0(:,2,:)  = ZLAIHI
!VDZ0F          = ZVDZ0F
!VDZ0H          = ZVDZ0H
END SUBROUTINE BLOCK_TO_NORMAL

END SUBROUTINE ECLAND_DRV_LAYER
