MODULE ECLAND_DDH_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMCDH1S ,                 ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB
USE FIELD_FACTORY_MODULE, ONLY: FIELD_NEW, FIELD_DELETE

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: DDH_SURF_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTLS   => NULL() ! Diagnostic array for tiles (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTLS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTSS   => NULL() ! Diagnostic array for snow T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTTS   => NULL() ! Diagnostic array for soil T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTTS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTIS   => NULL() ! Diagnostic array for ice T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTIS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHCO2S  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHCO2S  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHBVOCS => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHBVOCS => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHBIOS  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHBIOS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHVEGS  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHVEGS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHSSS   => NULL() ! Diagnostic array for snow mass (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHSSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,     POINTER :: PDHIIS   => NULL() ! Diagnostic array for interception layer (see module yomcdh)
  CLASS(FIELD_3RB), POINTER :: F_PDHIIS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHWLS   => NULL() ! Diagnostic array for soil water (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHWLS   => NULL()

CONTAINS
  PROCEDURE :: INIT  => DDH_SURF_TYPE_INIT
  PROCEDURE :: FINAL => DDH_SURF_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => DDH_SURF_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST => DDH_SURF_TYPE_SYNC_HOST
END TYPE DDH_SURF_TYPE

CONTAINS

  SUBROUTINE DDH_SURF_TYPE_INIT(SELF, NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO, PERSISTENT)
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
    LOGICAL :: LLPERSIST
    INTEGER(KIND=JPIM) :: JIBL
    REAL(KIND=JPRB), POINTER :: ZPDHTTS(:,:,:)
    REAL(KIND=JPRB), POINTER :: ZPDHVEGS(:,:,:)

    LLPERSIST = .FALSE.
    IF (PRESENT(PERSISTENT)) LLPERSIST = PERSISTENT

    CALL FIELD_NEW(SELF%F_PDHBVOCS, UBOUNDS=[NPROMA,NVHILO,NDHVBVOCS,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHTLS, UBOUNDS=[NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHTSS, UBOUNDS=[NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHSSS, UBOUNDS=[NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHTTS, UBOUNDS=[NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHWLS, UBOUNDS=[NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHTIS, UBOUNDS=[NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHIIS, UBOUNDS=[NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHCO2S, UBOUNDS=[NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHBIOS, UBOUNDS=[NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDHVEGS, UBOUNDS=[NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS], PERSISTENT = LLPERSIST)
!$OMP PARALLEL DO PRIVATE(JIBL, ZPDHTTS, ZPDHVEGS) SCHEDULE(STATIC)
    DO JIBL = 1, NBLOCKS
      ZPDHTTS  => SELF%F_PDHTTS%GET_VIEW(JIBL)
      ZPDHVEGS => SELF%F_PDHVEGS%GET_VIEW(JIBL)
      ZPDHTTS(1:NPROMA,:,:)  = 0._JPRB
      ZPDHVEGS(1:NPROMA,:,:) = 0._JPRB
    ENDDO
!$OMP END PARALLEL DO
  END SUBROUTINE DDH_SURF_TYPE_INIT

  SUBROUTINE DDH_SURF_TYPE_FINAL(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF

    IF (ASSOCIATED(SELF%F_PDHTLS)) CALL FIELD_DELETE(SELF%F_PDHTLS)
    NULLIFY( SELF%PDHTLS)
    IF (ASSOCIATED(SELF%F_PDHTSS)) CALL FIELD_DELETE(SELF%F_PDHTSS)
    NULLIFY( SELF%PDHTSS)
    IF (ASSOCIATED(SELF%F_PDHSSS)) CALL FIELD_DELETE(SELF%F_PDHSSS)
    NULLIFY( SELF%PDHSSS)
    IF (ASSOCIATED(SELF%F_PDHTTS)) CALL FIELD_DELETE(SELF%F_PDHTTS)
    NULLIFY( SELF%PDHTTS)
    IF (ASSOCIATED(SELF%F_PDHWLS)) CALL FIELD_DELETE(SELF%F_PDHWLS)
    NULLIFY( SELF%PDHWLS)
    IF (ASSOCIATED(SELF%F_PDHTIS)) CALL FIELD_DELETE(SELF%F_PDHTIS)
    NULLIFY( SELF%PDHTIS)
    IF (ASSOCIATED(SELF%F_PDHIIS)) CALL FIELD_DELETE(SELF%F_PDHIIS)
    NULLIFY( SELF%PDHIIS)
    IF (ASSOCIATED(SELF%F_PDHCO2S)) CALL FIELD_DELETE(SELF%F_PDHCO2S)
    NULLIFY( SELF%PDHCO2S)
    IF (ASSOCIATED(SELF%F_PDHBIOS)) CALL FIELD_DELETE(SELF%F_PDHBIOS)
    NULLIFY( SELF%PDHBIOS)
    IF (ASSOCIATED(SELF%F_PDHBVOCS)) CALL FIELD_DELETE(SELF%F_PDHBVOCS)
    NULLIFY( SELF%PDHBVOCS)
    IF (ASSOCIATED(SELF%F_PDHVEGS)) CALL FIELD_DELETE(SELF%F_PDHVEGS)
    NULLIFY( SELF%PDHVEGS)
  END SUBROUTINE DDH_SURF_TYPE_FINAL

  SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PDHTLS))   SELF%PDHTLS   => SELF%F_PDHTLS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTSS))   SELF%PDHTSS   => SELF%F_PDHTSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTTS))   SELF%PDHTTS   => SELF%F_PDHTTS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTIS))   SELF%PDHTIS   => SELF%F_PDHTIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHCO2S))  SELF%PDHCO2S  => SELF%F_PDHCO2S%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHBVOCS)) SELF%PDHBVOCS => SELF%F_PDHBVOCS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHBIOS))  SELF%PDHBIOS  => SELF%F_PDHBIOS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHVEGS))  SELF%PDHVEGS  => SELF%F_PDHVEGS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHSSS))   SELF%PDHSSS   => SELF%F_PDHSSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHIIS))   SELF%PDHIIS   => SELF%F_PDHIIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHWLS))   SELF%PDHWLS   => SELF%F_PDHWLS%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW

  SUBROUTINE DDH_SURF_TYPE_SYNC_HOST(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF

    IF (ASSOCIATED(SELF%F_PDHTLS))   CALL SELF%F_PDHTLS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHTSS))   CALL SELF%F_PDHTSS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHTTS))   CALL SELF%F_PDHTTS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHTIS))   CALL SELF%F_PDHTIS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHCO2S))  CALL SELF%F_PDHCO2S%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHBVOCS)) CALL SELF%F_PDHBVOCS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHBIOS))  CALL SELF%F_PDHBIOS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHVEGS))  CALL SELF%F_PDHVEGS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHSSS))   CALL SELF%F_PDHSSS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHIIS))   CALL SELF%F_PDHIIS%SYNC_HOST_RDWR()
    IF (ASSOCIATED(SELF%F_PDHWLS))   CALL SELF%F_PDHWLS%SYNC_HOST_RDWR()
  END SUBROUTINE DDH_SURF_TYPE_SYNC_HOST

END MODULE ECLAND_DDH_TYPE_MOD
