MODULE ECLAND_AUX_DIAG_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
!USE FIELD_MODULE
!USE FIELD_FACTORY_MODULE
!USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY

IMPLICIT NONE

TYPE AUX_DIAG_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PVDIS      ! Vert-integrated turbulent dissipation rate (W/m2)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PGUST! PI10FG     ! WIND GUST AT 10 m FOR CURRENT TIME LEVEL (m/s)
  !    additional turbulence diagnostics
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZINV          ! convective turbulent mixing height


!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_PCAPE, F_PPDEPL, F_PCBASE, F_PCBASEA, F_PCTOPC, F_P0DEGL, F_PM10DEGL, F_PVISIH, F_PVDISCU, F_PVDIS, &
!  CLASS(FIELD_3RB), POINTER :: F_PCONVIND, F_PZTWETB, F_PQSAT, F_PZTENQ, F_PMFUDE_RATE, F_PMFDDE_RATE, F_PKH_VDF, &
!   & F_PCOVPTOT, F_PMFU, F_PMFD, F_ZLUDE, F_ZLU, F_ZLRAIN, F_PKM_VDF, F_ZRI, F_ZCAPE, F_PCIN
!  CLASS (FIELD_4RB), POINTER :: F_ZLUDELI, F_ZSNDE, F_PRSUD
!  CLASS (FIELD_2IM), POINTER :: F_ITYPE, F_ICBOT, F_ICTOP, F_IPBLTYPE, F_ICBOT_LIG, F_ICTOP_LIG
!
CONTAINS
  PROCEDURE :: INIT => AUX_DIAG_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => AUX_DIAG_TYPE_FINAL
END TYPE AUX_DIAG_TYPE


TYPE AUX_DIAG_LOCAL_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZPAPSRF
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZWND     ! horizontal wind in the lowest model level
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZCCNL, ZCCNO

!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_ZWND, F_ZCCNL, F_ZCCNO, F_ZRAINFRAC_TOPRFZ, F_ZEMIT, F_ZTRSOD, F_ZSUDU, F_ZTSKRAD
!
CONTAINS
  PROCEDURE :: INIT => AUX_DIAG_LOCAL_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => AUX_DIAG_LOCAL_TYPE_FINAL
END TYPE AUX_DIAG_LOCAL_TYPE


CONTAINS
!
 SUBROUTINE AUX_DIAG_TYPE_INIT(SELF, NPROMA, NBLOCKS) ! REGISTRY, NLEV, PERSISTENT)
    CLASS(AUX_DIAG_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS
    ALLOCATE(SELF%PGUST(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZINV(NPROMA,NBLOCKS))
    ALLOCATE(SELF%PVDIS(NPROMA,NBLOCKS))
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_PCAPE      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!
 END SUBROUTINE AUX_DIAG_TYPE_INIT
!
!  SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(AUX_DIAG_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%PCAPE => SELF%F_PCAPE%GET_VIEW(BLOCK_INDEX)
!        
!  END SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW
!
  SUBROUTINE AUX_DIAG_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_TYPE) :: SELF
    DEALLOCATE(SELF%PGUST)
    DEALLOCATE(SELF%ZINV)
    DEALLOCATE(SELF%PVDIS)
!
!    CALL FIELD_DELETE (SELF%F_PCAPE)
  END SUBROUTINE AUX_DIAG_TYPE_FINAL
!
!
  SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS) !, REGISTRY, NLEV, PERSISTENT)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS
    ALLOCATE(SELF%ZPAPSRF(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZWND(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCCNL(NPROMA,NBLOCKS))
    ALLOCATE(SELF%ZCCNO(NPROMA,NBLOCKS))
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_ZWND            , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT
!
!  SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%ZWND => SELF%F_ZWND%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW
!
  SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
    DEALLOCATE(SELF%ZPAPSRF)
    DEALLOCATE(SELF%ZWND)
    DEALLOCATE(SELF%ZCCNL)
    DEALLOCATE(SELF%ZCCNO)
!
!    CALL FIELD_DELETE (SELF%F_ZWND)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL
!
END MODULE ECLAND_AUX_DIAG_TYPE_MOD
