MODULE RDNML_PARAMS

CONTAINS
  SUBROUTINE RDNML_SNOW(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),      INTENT(INOUT) :: TMP_SURF

    ! * snow related (new parameterization) constants
    REAL(KIND=JPRB) :: RLWCSWEA
    REAL(KIND=JPRB) :: RLWCSWEB
    REAL(KIND=JPRB) :: RLWCSWEC
    REAL(KIND=JPRB) :: RTEMPAMP
    REAL(KIND=JPRB) :: RHOMINSNA
    REAL(KIND=JPRB) :: RHOMINSNB
    REAL(KIND=JPRB) :: RHOMINSNC
    REAL(KIND=JPRB) :: RHOMINSND
    REAL(KIND=JPRB) :: RSNDTOVERA
    REAL(KIND=JPRB) :: RSNDTOVERB
    REAL(KIND=JPRB) :: RSNDTOVERC
    REAL(KIND=JPRB) :: RSNDTDESTA
    REAL(KIND=JPRB) :: RSNDTDESTB
    REAL(KIND=JPRB) :: RSNDTDESTC
    REAL(KIND=JPRB) :: RSNDTDESTROI

    ! * Snow wind-induced densification parameters
    REAL(KIND=JPRB) :: RSNDAMOB
    REAL(KIND=JPRB) :: RSNDMOB
    REAL(KIND=JPRB) :: RSNDAW
    REAL(KIND=JPRB) :: RSNDBW
    REAL(KIND=JPRB) :: RSNDKV
    REAL(KIND=JPRB) :: RSNDATAUW
    REAL(KIND=JPRB) :: RSNDBTAUW
    REAL(KIND=JPRB) :: RSNDWCOMPMAX

    ! * Snow solar absorption parameters
    REAL(KIND=JPRB) :: SSAG1
    REAL(KIND=JPRB) :: SSAG2
    REAL(KIND=JPRB) :: SSAG3
    REAL(KIND=JPRB) :: SSAGSNSMAX
    REAL(KIND=JPRB) :: SSASNEXTMIN
    REAL(KIND=JPRB) :: SSASNEXTMAX
    REAL(KIND=JPRB) :: SSASNEXTCNST

    ! * New snow heat conductivity parameters
    REAL(KIND=JPRB) :: SNHCONDAV
    REAL(KIND=JPRB) :: SNHCONDBV
    REAL(KIND=JPRB) :: SNHCONDCV
    REAL(KIND=JPRB) :: SNHCONDPOV

    REAL(KIND=JPRB) :: RHOMAXSN_NEW


    ! ! * vlamsk
    REAL(KIND=JPRB) :: RSNLARGE
    REAL(KIND=JPRB) :: RSNLARGESN
    REAL(KIND=JPRB) :: RSNLARGEWT
    REAL(KIND=JPRB) :: RSNSNOW
    REAL(KIND=JPRB) :: RSNSNOWHVEG
    REAL(KIND=JPRB) :: RSNRTTEMP

    ! * Other snow parameters
    REAL(KIND=JPRB) :: RSNPERT
    REAL(KIND=JPRB) :: RSNGLC
    REAL(KIND=JPRB) :: RSMINZ
    REAL(KIND=JPRB) :: RSFRESH
    REAL(KIND=JPRB) :: RALFMINSN
    REAL(KIND=JPRB) :: RALFMAXSN

    ! parameter Snow thermal conductivity function
    REAL(KIND=JPRB) :: FSNTCONDA
    REAL(KIND=JPRB) :: FSNTCONDB
    REAL(KIND=JPRB) :: FSNTCONDC

    REAL(KIND=JPRB) :: RLICE
    REAL(KIND=JPRB) :: RQSNCRINV

    ! sea ice related
    REAL(KIND=JPRB) :: RDARSICE
    REAL(KIND=JPRB) :: RDANSICE
    REAL(KIND=JPRB) :: RRCSICE
    REAL(KIND=JPRB) :: RCONDSICE

    REAL(KIND=JPRB) :: RSNPER
    REAL(KIND=JPRB) :: RHOMINSN
    REAL(KIND=JPRB) :: RHODELTASN
    REAL(KIND=JPRB) :: RTAUF
    REAL(KIND=JPRB) :: RTAUA
    REAL(KIND=JPRB) :: RALAMSN
    REAL(KIND=JPRB) :: RDSNMAX

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "namparsnow.h"


    IF (LHOOK) CALL DR_HOOK('RDNML_SNOW',0,ZHOOK_HANDLE)

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global snow parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPARSNOW)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------

    TMP_SURF%RLWCSWEA     = RLWCSWEA
    TMP_SURF%RLWCSWEB     = RLWCSWEB
    TMP_SURF%RLWCSWEC     = RLWCSWEC
    TMP_SURF%RTEMPAMP     = RTEMPAMP
    TMP_SURF%RHOMINSNA    = RHOMINSNA
    TMP_SURF%RHOMINSNB    = RHOMINSNB
    TMP_SURF%RHOMINSNC    = RHOMINSNC
    TMP_SURF%RHOMINSND    = RHOMINSND
    TMP_SURF%RSNDTOVERA   = RSNDTOVERA
    TMP_SURF%RSNDTOVERB   = RSNDTOVERB
    TMP_SURF%RSNDTOVERC   = RSNDTOVERC
    TMP_SURF%RSNDTDESTA   = RSNDTDESTA
    TMP_SURF%RSNDTDESTB   = RSNDTDESTB
    TMP_SURF%RSNDTDESTC   = RSNDTDESTC
    TMP_SURF%RSNDTDESTROI = RSNDTDESTROI
    TMP_SURF%RHOMAXSN_NEW = RHOMAXSN_NEW

    TMP_SURF%RSNDAMOB     = RSNDAMOB
    TMP_SURF%RSNDMOB      = RSNDMOB
    TMP_SURF%RSNDAW       = RSNDAW
    TMP_SURF%RSNDBW       = RSNDBW
    TMP_SURF%RSNDKV       = RSNDKV
    TMP_SURF%RSNDATAUW    = RSNDATAUW
    TMP_SURF%RSNDBTAUW    = RSNDBTAUW
    TMP_SURF%RSNDWCOMPMAX = RSNDWCOMPMAX

    TMP_SURF%SSAG1        = SSAG1
    TMP_SURF%SSAG2        = SSAG2
    TMP_SURF%SSAG3        = SSAG3
    TMP_SURF%SSAGSNSMAX   = SSAGSNSMAX
    TMP_SURF%SSASNEXTMIN  = SSASNEXTMIN
    TMP_SURF%SSASNEXTMAX  = SSASNEXTMAX
    TMP_SURF%SSASNEXTCNST = SSASNEXTCNST

    TMP_SURF%SNHCONDAV    = SNHCONDAV
    TMP_SURF%SNHCONDBV    = SNHCONDBV
    TMP_SURF%SNHCONDCV    = SNHCONDCV
    TMP_SURF%SNHCONDPOV   = SNHCONDPOV
    
    TMP_SURF%RSNLARGE     = RSNLARGE
    TMP_SURF%RSNLARGESN   = RSNLARGESN
    TMP_SURF%RSNLARGEWT   = RSNLARGEWT
    TMP_SURF%RSNSNOW      = RSNSNOW
    TMP_SURF%RSNSNOWHVEG  = RSNSNOWHVEG
    TMP_SURF%RSNRTTEMP    = RSNRTTEMP

    TMP_SURF%RSNPERT      = RSNPERT
    TMP_SURF%RSNGLC       = RSNGLC
    TMP_SURF%RSMINZ       = RSMINZ

    TMP_SURF%RLICE        = RLICE
    TMP_SURF%RQSNCRINV    = RQSNCRINV
    TMP_SURF%RDARSICE     = RDARSICE
    TMP_SURF%RDANSICE     = RDANSICE
    TMP_SURF%RRCSICE      = RRCSICE
    TMP_SURF%RCONDSICE    = RCONDSICE

    TMP_SURF%FSNTCONDA    = FSNTCONDA
    TMP_SURF%FSNTCONDB    = FSNTCONDB
    TMP_SURF%FSNTCONDC    = FSNTCONDC

    TMP_SURF%RSNPER       = RSNPER
    TMP_SURF%RHOMINSN     = RHOMINSN
    TMP_SURF%RHODELTASN   = RHODELTASN
    TMP_SURF%RTAUF        = RTAUF
    TMP_SURF%RTAUA        = RTAUA
    TMP_SURF%RALAMSN      = RALAMSN
    TMP_SURF%RDSNMAX      = RDSNMAX
    TMP_SURF%RSFRESH      = RSFRESH

    TMP_SURF%RALFMINSN    = RALFMINSN
    TMP_SURF%RALFMAXSN    = RALFMAXSN
  
    IF (LHOOK) CALL DR_HOOK('RDNML_SNOW',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_SNOW

  SUBROUTINE RDNML_SOIL(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB, JPRM
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),       INTENT(INOUT) :: TMP_SURF

    REAL(KIND=JPRB) :: RTF1
    REAL(KIND=JPRB) :: RTF2
    REAL(KIND=JPRB) :: RLAMBDAICE
    REAL(KIND=JPRB) :: RLAMBDAWAT
    REAL(KIND=JPRB) :: RKERST1
    REAL(KIND=JPRB) :: RKERST2
    REAL(KIND=JPRB) :: RKERST3
    REAL(KIND=JPRB) :: RSRDEP
    REAL(KIND=JPRB) :: RSIGORMIN
    REAL(KIND=JPRB) :: RSIGORMAX
    REAL(KIND=JPRB) :: RWLMAX
    REAL(KIND=JPRB) :: RPSFR

    REAL(KIND=JPRB) :: RBARPWP
!    REAL(KIND=JPRB) :: RVGBARCAP
    REAL(KIND=JPRB) :: RBARCAP
    REAL(KIND=JPRB) :: RCLU
!    REAL(KIND=JPRB) :: RQEXP

    REAL(KIND=JPRB) :: RRSF1A
    REAL(KIND=JPRB) :: RRSF1B
    REAL(KIND=JPRB) :: RRSF1C

    REAL(KIND=JPRB) :: RRHOSM
    REAL(KIND=JPRB) :: RLAMBDAQ
    REAL(KIND=JPRB) :: RLAMBDAO
    REAL(KIND=JPRB) :: RLAMBDAMIN
    REAL(KIND=JPRB) :: RLAMBDAMAX

    REAL(KIND=JPRB) :: RLAMBDRYMA
    REAL(KIND=JPRB) :: RLAMBDRYMB
    REAL(KIND=JPRM) :: RLAMBDRYMC

    REAL(KIND=JPRB) :: RTFREEZSICECEL
    REAL(KIND=JPRB) :: RTMELTSICECEL

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "namparsoil.h"

    IF (LHOOK) CALL DR_HOOK('RDNML_SOIL',0,ZHOOK_HANDLE)


    !     ------------------------------------------------------------------
    !*         0.     ALLOCATE ARRAYS
    !                 -------------

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global soil parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPARSOIL)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------
    TMP_SURF%RTF1         = RTF1
    TMP_SURF%RTF2         = RTF2
    TMP_SURF%RLAMBDAICE   = RLAMBDAICE
    TMP_SURF%RLAMBDAWAT   = RLAMBDAWAT
    TMP_SURF%RKERST1      = RKERST1
    TMP_SURF%RKERST2      = RKERST2
    TMP_SURF%RKERST3      = RKERST3
    TMP_SURF%RSRDEP       = RSRDEP
    TMP_SURF%RSIGORMIN    = RSIGORMIN
    TMP_SURF%RSIGORMAX    = RSIGORMAX
    TMP_SURF%RWLMAX       = RWLMAX
    TMP_SURF%RPSFR        = RPSFR
    TMP_SURF%RBARPWP      = RBARPWP
!    TMP_SURF%RVGBARCAP    = RVGBARCAP
    TMP_SURF%RBARCAP      = RBARCAP
    TMP_SURF%RCLU         = RCLU
    TMP_SURF%RRSF1A       = RRSF1A
    TMP_SURF%RRSF1B       = RRSF1B
    TMP_SURF%RRSF1C       = RRSF1C
    TMP_SURF%RRHOSM       = RRHOSM
    TMP_SURF%RLAMBDAQ     = RLAMBDAQ
    TMP_SURF%RLAMBDAO     = RLAMBDAO
    TMP_SURF%RLAMBDAMIN   = RLAMBDAMIN
    TMP_SURF%RLAMBDAMAX   = RLAMBDAMAX
    TMP_SURF%RLAMBDRYMA   = RLAMBDRYMA
    TMP_SURF%RLAMBDRYMB   = RLAMBDRYMB
    TMP_SURF%RLAMBDRYMC   = RLAMBDRYMC
!    TMP_SURF%RQEXP        = RQEXP
    TMP_SURF%RTFREEZSICECEL = RTFREEZSICECEL
    TMP_SURF%RTMELTSICECEL = RTMELTSICECEL

    IF (LHOOK) CALL DR_HOOK('RDNML_SOIL',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_SOIL

  SUBROUTINE RDNML_VEG(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),       INTENT(INOUT) :: TMP_SURF

    REAL(KIND=JPRB) :: RVQ10A
    REAL(KIND=JPRB) :: RVQ10B
    REAL(KIND=JPRB) :: RVQ10C
    REAL(KIND=JPRB) :: RVQ10D
    REAL(KIND=JPRB) :: RVQ10MIN

    REAL(KIND=JPRB) :: RVINTER
    REAL(KIND=JPRB) :: RLHAERO
    REAL(KIND=JPRB) :: RLHAEROS
    REAL(KIND=JPRB) :: RCEPSW

    REAL(KIND=JPRB) :: RVLAMSK_DESERT
    REAL(KIND=JPRB) :: RVLAMSK_SNOW
    REAL(KIND=JPRB) :: RVLAMSKS_DESERT
    REAL(KIND=JPRB) :: RVLAMSKS_SNOW

    REAL(KIND=JPRB) :: RVZ0M_BARE
    REAL(KIND=JPRB) :: RVZ0M_SNOW
    REAL(KIND=JPRB) :: RVZ0H_BARE
    REAL(KIND=JPRB) :: RVZ0H_SNOW

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


#include "namparveg.h"

    IF (LHOOK) CALL DR_HOOK('RDNML_VEG',0,ZHOOK_HANDLE)

    !     ------------------------------------------------------------------
    !*         0.     ALLOCATE ARRAYS
    !                 -------------

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global veg parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPARVEG)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------
    TMP_SURF%RVQ10A       = RVQ10A
    TMP_SURF%RVQ10B       = RVQ10B
    TMP_SURF%RVQ10C       = RVQ10C
    TMP_SURF%RVQ10D       = RVQ10D
    TMP_SURF%RVQ10MIN     = RVQ10MIN

    TMP_SURF%RVINTER      = RVINTER
    TMP_SURF%RLHAERO      = RLHAERO
    TMP_SURF%RLHAEROS     = RLHAEROS
    TMP_SURF%RCEPSW       = RCEPSW

    TMP_SURF%RVLAMSK_DESERT = RVLAMSK_DESERT
    TMP_SURF%RVLAMSK_SNOW   = RVLAMSK_SNOW
    TMP_SURF%RVLAMSKS_DESERT= RVLAMSKS_DESERT
    TMP_SURF%RVLAMSKS_SNOW  = RVLAMSKS_SNOW

    TMP_SURF%RVZ0M_BARE     = RVZ0M_BARE
    TMP_SURF%RVZ0M_SNOW     = RVZ0M_SNOW
    TMP_SURF%RVZ0H_BARE     = RVZ0H_BARE
    TMP_SURF%RVZ0H_SNOW     = RVZ0H_SNOW

    IF (LHOOK) CALL DR_HOOK('RDNML_VEG',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_VEG

  SUBROUTINE RDNML_AGS(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),       INTENT(INOUT) :: TMP_SURF

    REAL(KIND=JPRB) :: RAW
    REAL(KIND=JPRB) :: RASW
    REAL(KIND=JPRB) :: RBW
    REAL(KIND=JPRB) :: RDMAXN
    REAL(KIND=JPRB) :: RDMAXX
    REAL(KIND=JPRB) :: RPARCF
    REAL(KIND=JPRB) :: RPCCO2
    REAL(KIND=JPRB) :: RIAOPT
    REAL(KIND=JPRB) :: RDSPOPT
    REAL(KIND=JPRB) :: RXGT
    REAL(KIND=JPRB) :: RDIFRACF
    REAL(KIND=JPRB) :: RSHP1AMMAX
    REAL(KIND=JPRB) :: RSHP2AMMAX
    REAL(KIND=JPRB) :: RSHP1GMES
    REAL(KIND=JPRB) :: RSHP2GMES
    REAL(KIND=JPRB) :: RMAXFZERO
    REAL(KIND=JPRB) :: RCC_NIT_BASE_DIL
    REAL(KIND=JPRB) :: RLAIB_NITROA
    REAL(KIND=JPRB) :: RLAIB_NITROB
    REAL(KIND=JPRB) :: RLAIB_NITROMIN
    REAL(KIND=JPRB) :: RVGMES_FLDEXP
    REAL(KIND=JPRB) :: RESPBSTR_COEF
    REAL(KIND=JPRB) :: REPS_COEF
    REAL(KIND=JPRB) :: RGSC_COEF
    REAL(KIND=JPRB) :: RXBOMEGA
    REAL(KIND=JPRB) :: RRDCF
    REAL(KIND=JPRB) :: RCONDCTMIN
    REAL(KIND=JPRB) :: RCONDSTMIN
    REAL(KIND=JPRB) :: RANFMINIT
    REAL(KIND=JPRB) :: RRESPFACTOR_NIT
    REAL(KIND=JPRB) :: RCNS_NIT
    REAL(KIND=JPRB) :: RCA_1X_CO2_NIT
    REAL(KIND=JPRB) :: RCA_2X_CO2_NIT
    REAL(KIND=JPRB) :: RCC_NIT
    REAL(KIND=JPRB) :: RCO2FRAC

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "namparags.h"

    IF (LHOOK) CALL DR_HOOK('RDNML_AGS',0,ZHOOK_HANDLE)

    !     ------------------------------------------------------------------
    !*         0.     ALLOCATE ARRAYS
    !                 -------------

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global ags parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPARAGS)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------
    TMP_SURF%RAW          = RAW
    TMP_SURF%RASW         = RASW
    TMP_SURF%RBW          = RBW
    TMP_SURF%RDMAXN       = RDMAXN
    TMP_SURF%RDMAXX       = RDMAXX
    TMP_SURF%RPARCF       = RPARCF
    TMP_SURF%RPCCO2       = RPCCO2
    TMP_SURF%RIAOPT       = RIAOPT
    TMP_SURF%RDSPOPT      = RDSPOPT
    TMP_SURF%RXGT         = RXGT
    TMP_SURF%RDIFRACF     = RDIFRACF
    TMP_SURF%RSHP1AMMAX   = RSHP1AMMAX
    TMP_SURF%RSHP2AMMAX   = RSHP2AMMAX
    TMP_SURF%RSHP1GMES    = RSHP1GMES
    TMP_SURF%RSHP2GMES    = RSHP2GMES
    TMP_SURF%RMAXFZERO    = RMAXFZERO
    TMP_SURF%RCC_NIT_BASE_DIL = RCC_NIT_BASE_DIL
    TMP_SURF%RLAIB_NITROA = RLAIB_NITROA
    TMP_SURF%RLAIB_NITROB = RLAIB_NITROB
    TMP_SURF%RLAIB_NITROMIN = RLAIB_NITROMIN
    TMP_SURF%RVGMES_FLDEXP = RVGMES_FLDEXP
    TMP_SURF%RESPBSTR_COEF = RESPBSTR_COEF
    TMP_SURF%REPS_COEF    = REPS_COEF
    TMP_SURF%RGSC_COEF    = RGSC_COEF

    TMP_SURF%RXBOMEGA     = RXBOMEGA
    TMP_SURF%RRDCF        = RRDCF
    TMP_SURF%RCONDCTMIN   = RCONDCTMIN
    TMP_SURF%RCONDSTMIN   = RCONDSTMIN
    TMP_SURF%RANFMINIT    = RANFMINIT
    TMP_SURF%RRESPFACTOR_NIT = RRESPFACTOR_NIT
    TMP_SURF%RCNS_NIT     = RCNS_NIT
    TMP_SURF%RCA_1X_CO2_NIT = RCA_1X_CO2_NIT
    TMP_SURF%RCA_2X_CO2_NIT = RCA_2X_CO2_NIT
    TMP_SURF%RCC_NIT      = RCC_NIT
    TMP_SURF%RCO2FRAC     = RCO2FRAC
    
    IF (LHOOK) CALL DR_HOOK('RDNML_AGS',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_AGS

  SUBROUTINE RDNML_FLAKE(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB     ,JPRD
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),       INTENT(INOUT) :: TMP_SURF

    REAL(KIND=JPRB) :: RC_SHAPE
    REAL(KIND=JPRB) :: RC_OC_MAXICEZ
    REAL(KIND=JPRB) :: RC_OC_MAXDEPTH

    !  Dimensionless constants
    !  in the equations for the mixed-layer depth
    !  and for the shape factor with respect to the temperature profile in the thermocline
    REAL(KIND=JPRD) :: RC_CBL_1
    REAL(KIND=JPRD) :: RC_CBL_2
    REAL(KIND=JPRD) :: RC_SBL_ZM_N
    REAL(KIND=JPRD) :: RC_SBL_ZM_S
    REAL(KIND=JPRD) :: RC_SBL_ZM_I
    REAL(KIND=JPRD) :: RC_RELAX_H
    REAL(KIND=JPRD) :: RC_RELAX_C

    !  Parameters of the shape functions
    REAL(KIND=JPRB) :: RC_T_MIN
    REAL(KIND=JPRB) :: RC_T_MAX
    REAL(KIND=JPRD) :: RPHI_T_PR0_1
    REAL(KIND=JPRD) :: RPHI_T_PR0_2
    REAL(KIND=JPRD) :: RC_TT_1
    REAL(KIND=JPRD) :: RC_TT_2
    REAL(KIND=JPRD) :: RC_B1
    REAL(KIND=JPRD) :: RC_B2
    REAL(KIND=JPRB) :: RC_S_LIN
    REAL(KIND=JPRB) :: RPHI_S_PR0_LIN
    REAL(KIND=JPRB) :: RC_I_LIN
    REAL(KIND=JPRB) :: RPHI_I_PR0_LIN
    REAL(KIND=JPRB) :: RPHI_I_PR1_LIN
    REAL(KIND=JPRB) :: RPHI_I_AST_MR
    REAL(KIND=JPRD) :: RC_I_MR
    REAL(KIND=JPRB) :: RH_ICE_MAX

    REAL(KIND=JPRB) :: RTPL_A_T

    REAL(KIND=JPRD) :: ROPT_WAT_EXTC1_REF
    REAL(KIND=JPRD) :: ROPT_WAT_FRAC1_TRANS
    REAL(KIND=JPRD) :: ROPT_WAT_EXTC1_TRANS
    REAL(KIND=JPRD) :: ROPT_WAT_EXTC2_TRANS
    REAL(KIND=JPRD) :: ROPT_WICE_EXTC1_REF
    REAL(KIND=JPRD) :: ROPT_BICE_EXTC1_REF
    REAL(KIND=JPRD) :: ROPT_ICE_EXTC1_OP

    !  Parameters used in flakeen flakerad module
    REAL(KIND=JPRD) :: RDEPTH_W_MAX
    REAL(KIND=JPRD) :: RDEPTH_W_MIN
    REAL(KIND=JPRD) :: RD_C_T_DT_MAX_A
    REAL(KIND=JPRD) :: RC_I_FLK_A
    REAL(KIND=JPRD) :: RH_ICE_FUSION_A
    REAL(KIND=JPRD) :: RH_ICE_FUSION_B
    REAL(KIND=JPRD) :: RT_ICE_MIN_FLK
    REAL(KIND=JPRD) :: RCONV_EQUIL_A
    REAL(KIND=JPRD) :: RCONV_EQUIL_B
    REAL(KIND=JPRD) :: RCONV_EQUIL_C

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE    

#include "namparflake.h"

    IF (LHOOK) CALL DR_HOOK('RDNML_FLAKE',0,ZHOOK_HANDLE)

    !     ------------------------------------------------------------------
    !*         0.     ALLOCATE ARRAYS
    !                 -------------

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global flake parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPARFLAKE)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------
    TMP_SURF%RC_SHAPE        = RC_SHAPE
    TMP_SURF%RC_OC_MAXICEZ   = RC_OC_MAXICEZ
    TMP_SURF%RC_OC_MAXDEPTH  = RC_OC_MAXDEPTH

    TMP_SURF%RC_CBL_1        = RC_CBL_1
    TMP_SURF%RC_CBL_2        = RC_CBL_2
    TMP_SURF%RC_SBL_ZM_N     = RC_SBL_ZM_N
    TMP_SURF%RC_SBL_ZM_S     = RC_SBL_ZM_S
    TMP_SURF%RC_SBL_ZM_I     = RC_SBL_ZM_I
    TMP_SURF%RC_RELAX_H      = RC_RELAX_H
    TMP_SURF%RC_RELAX_C      = RC_RELAX_C

    TMP_SURF%RC_T_MIN        = RC_T_MIN
    TMP_SURF%RC_T_MAX        = RC_T_MAX
    TMP_SURF%RPHI_T_PR0_1    = RPHI_T_PR0_1
    TMP_SURF%RPHI_T_PR0_2    = RPHI_T_PR0_2
    TMP_SURF%RC_TT_1         = RC_TT_1
    TMP_SURF%RC_TT_2         = RC_TT_2
    TMP_SURF%RC_B1           = RC_B1
    TMP_SURF%RC_B2           = RC_B2
    TMP_SURF%RC_S_LIN        = RC_S_LIN
    TMP_SURF%RPHI_S_PR0_LIN  = RPHI_S_PR0_LIN
    TMP_SURF%RC_I_LIN        = RC_I_LIN
    TMP_SURF%RPHI_I_PR0_LIN  = RPHI_I_PR0_LIN
    TMP_SURF%RPHI_I_PR1_LIN  = RPHI_I_PR1_LIN
    TMP_SURF%RPHI_I_AST_MR   = RPHI_I_AST_MR
    TMP_SURF%RC_I_MR         = RC_I_MR
    TMP_SURF%RH_ICE_MAX      = RH_ICE_MAX

    TMP_SURF%RTPL_A_T        = RTPL_A_T

    TMP_SURF%ROPT_WAT_EXTC1_REF     = ROPT_WAT_EXTC1_REF
    TMP_SURF%ROPT_WAT_FRAC1_TRANS   = ROPT_WAT_FRAC1_TRANS
    TMP_SURF%ROPT_WAT_EXTC1_TRANS   = ROPT_WAT_EXTC1_TRANS
    TMP_SURF%ROPT_WAT_EXTC2_TRANS   = ROPT_WAT_EXTC2_TRANS
    TMP_SURF%ROPT_WICE_EXTC1_REF    = ROPT_WICE_EXTC1_REF
    TMP_SURF%ROPT_BICE_EXTC1_REF    = ROPT_BICE_EXTC1_REF
    TMP_SURF%ROPT_ICE_EXTC1_OP      = ROPT_ICE_EXTC1_OP

    TMP_SURF%RDEPTH_W_MAX    = RDEPTH_W_MAX
    TMP_SURF%RDEPTH_W_MIN    = RDEPTH_W_MIN
    TMP_SURF%RD_C_T_DT_MAX_A = RD_C_T_DT_MAX_A
    TMP_SURF%RC_I_FLK_A      = RC_I_FLK_A
    TMP_SURF%RH_ICE_FUSION_A = RH_ICE_FUSION_A
    TMP_SURF%RH_ICE_FUSION_B = RH_ICE_FUSION_B
    TMP_SURF%RT_ICE_MIN_FLK  = RT_ICE_MIN_FLK
    TMP_SURF%RCONV_EQUIL_A   = RCONV_EQUIL_A
    TMP_SURF%RCONV_EQUIL_B   = RCONV_EQUIL_B
    TMP_SURF%RCONV_EQUIL_C   = RCONV_EQUIL_C

    IF (LHOOK) CALL DR_HOOK('RDNML_FLAKE',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_FLAKE

  SUBROUTINE RDNML_EXC(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),       INTENT(INOUT) :: TMP_SURF

    REAL(KIND=JPRB) :: RSSRFLTIMAX
    REAL(KIND=JPRB) :: RBLENDWMO
    REAL(KIND=JPRB) :: RZ0MWMO
    REAL(KIND=JPRB) :: RETACONV
    REAL(KIND=JPRB) :: RCDFC
    REAL(KIND=JPRB) :: RBLENDSNVEG
    
    REAL(KIND=JPRB) :: RUGNA
    REAL(KIND=JPRB) :: RUGNB
    REAL(KIND=JPRB) :: RUGN

    REAL(KIND=JPRB) :: RKAP
    REAL(KIND=JPRB) :: RPARZIINI
    REAL(KIND=JPRB) :: RZ0ICEINI
    REAL(KIND=JPRB) :: REPUST
    REAL(KIND=JPRB) :: RNUINI
    REAL(KIND=JPRB) :: RNUMINI
    REAL(KIND=JPRB) :: RNUHINI
    REAL(KIND=JPRB) :: RNUQINI
    REAL(KIND=JPRB) :: RCHAR
!    REAL(KIND=JPRB) :: REPDU2

    REAL(KIND=JPRB) :: RAZ0ICE
    REAL(KIND=JPRB) :: RBZ0ICE
    REAL(KIND=JPRB) :: RCZ0ICE
    REAL(KIND=JPRB) :: RDZ0ICE
 !   INTEGER(KIND=JPIM) :: REZ0ICE

    INTEGER(KIND=JPIM) :: RITZ0WN
    REAL(KIND=JPRB) :: RACDZ0WN
    REAL(KIND=JPRB) :: RBCDZ0WN
    REAL(KIND=JPRB) :: RXEPSZ0WN
    REAL(KIND=JPRB) :: RUSTMINZ0WN
    REAL(KIND=JPRB) :: RPCHARMAXZ0WN
    REAL(KIND=JPRB) :: RZ0FGZ0WN
    REAL(KIND=JPRB) :: RSALIN
    REAL(KIND=JPRB) :: RBLENDZ0

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "namparexc.h"


    IF (LHOOK) CALL DR_HOOK('RDNML_EXC',0,ZHOOK_HANDLE)

    !     ------------------------------------------------------------------
    !*         0.     ALLOCATE ARRAYS
    !                 -------------

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global exc parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPAREXC)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------
    TMP_SURF%RSSRFLTIMAX       = RSSRFLTIMAX
    TMP_SURF%RBLENDWMO         = RBLENDWMO
    TMP_SURF%RZ0MWMO           = RZ0MWMO
    TMP_SURF%RETACONV          = RETACONV
    TMP_SURF%RCDFC             = RCDFC
    TMP_SURF%RBLENDSNVEG       = RBLENDSNVEG
    
    TMP_SURF%RUGNA             = RUGNA
    TMP_SURF%RUGNB             = RUGNB
    TMP_SURF%RUGN              = RUGN

    TMP_SURF%RKAP              = RKAP
    TMP_SURF%RPARZIINI         = RPARZIINI
    TMP_SURF%RZ0ICEINI         = RZ0ICEINI
    TMP_SURF%REPUST            = REPUST
    TMP_SURF%RNUINI            = RNUINI
    TMP_SURF%RNUMINI           = RNUMINI
    TMP_SURF%RNUHINI           = RNUHINI
    TMP_SURF%RNUQINI           = RNUQINI
    TMP_SURF%RCHAR             = RCHAR
!    TMP_SURF%REPDU2            = REPDU2

    TMP_SURF%RAZ0ICE           = RAZ0ICE
    TMP_SURF%RBZ0ICE           = RBZ0ICE
    TMP_SURF%RCZ0ICE           = RCZ0ICE
    TMP_SURF%RDZ0ICE           = RDZ0ICE
!    TMP_SURF%REZ0ICE           = REZ0ICE

    TMP_SURF%RITZ0WN           = RITZ0WN
    TMP_SURF%RACDZ0WN          = RACDZ0WN
    TMP_SURF%RBCDZ0WN          = RBCDZ0WN
    TMP_SURF%RXEPSZ0WN         = RXEPSZ0WN
    TMP_SURF%RUSTMINZ0WN       = RUSTMINZ0WN
    TMP_SURF%RPCHARMAXZ0WN     = RPCHARMAXZ0WN
    TMP_SURF%RZ0FGZ0WN         = RZ0FGZ0WN

    TMP_SURF%RSALIN            = RSALIN
    TMP_SURF%RBLENDZ0          = RBLENDZ0

    IF (LHOOK) CALL DR_HOOK('RDNML_EXC',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_EXC

  SUBROUTINE RDNML_URB(TMP_SURF)

    USE YOMLUN1S, ONLY : NULNAM
    USE YOS_NAMPARS1, ONLY : TESURF
    USE PARKIND1, ONLY : JPIM     ,JPRB
    USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

    IMPLICIT NONE

    TYPE(TESURF),       INTENT(INOUT) :: TMP_SURF

    REAL(KIND=JPRB) :: RBUIZ0M
    REAL(KIND=JPRB) :: RWALALB
    REAL(KIND=JPRB) :: RROOALB
    REAL(KIND=JPRB) :: RROAALB
    REAL(KIND=JPRB) :: RWALEMIS
    REAL(KIND=JPRB) :: RROOEMIS
    REAL(KIND=JPRB) :: RROAEMIS
    REAL(KIND=JPRB) :: RWALVHC
    REAL(KIND=JPRB) :: RROOVHC
    REAL(KIND=JPRB) :: RROAVHC
    REAL(KIND=JPRB) :: RWALTC
    REAL(KIND=JPRB) :: RROOTC
    REAL(KIND=JPRB) :: RROATC
    REAL(KIND=JPRB) :: RURBALP
    REAL(KIND=JPRB) :: RURBCON
    REAL(KIND=JPRB) :: RURBLAM
    REAL(KIND=JPRB) :: RURBSAT
    REAL(KIND=JPRB) :: RURBSRES 

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "namparurb.h"


    IF (LHOOK) CALL DR_HOOK('RDNML_URB',0,ZHOOK_HANDLE)

    !     ------------------------------------------------------------------
    !*         0.     ALLOCATE ARRAYS
    !                 -------------

    !     ------------------------------------------------------------------
    !*         1.     READ NAMELIST
    !                 -------------

!    WRITE(*,*) "Reading global urban parameters from namelist..."

    REWIND(NULNAM)
    READ(NULNAM,NAMPARURB)

    !     ------------------------------------------------------------------
    !*         2.     WRITE VALUES TO TMP_SURF
    !                 -------------
    TMP_SURF%RBUIZ0M  = RBUIZ0M
    TMP_SURF%RWALALB  = RWALALB
    TMP_SURF%RROOALB  = RROOALB
    TMP_SURF%RROAALB  = RROAALB
    TMP_SURF%RWALEMIS = RWALEMIS
    TMP_SURF%RROOEMIS = RROOEMIS
    TMP_SURF%RROAEMIS = RROAEMIS
    TMP_SURF%RWALVHC  = RWALVHC
    TMP_SURF%RROOVHC  = RROOVHC
    TMP_SURF%RROAVHC  = RROAVHC 
    TMP_SURF%RWALTC   = RWALTC
    TMP_SURF%RROOTC   = RROOTC
    TMP_SURF%RROATC   = RROATC
    TMP_SURF%RURBALP  = RURBALP
    TMP_SURF%RURBCON  = RURBCON
    TMP_SURF%RURBLAM  = RURBLAM
    TMP_SURF%RURBSAT  = RURBSAT
    TMP_SURF%RURBSRES = RURBSRES

    IF (LHOOK) CALL DR_HOOK('RDNML_URB',1,ZHOOK_HANDLE)

  END SUBROUTINE RDNML_URB

END MODULE RDNML_PARAMS
