MODULE SURFBC_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE SURFBC_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

CALL SURFBC_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)

END SUBROUTINE SURFBC_LAYER_PARALLEL

SUBROUTINE SURFBC_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI
USE YOMDIM1S, ONLY : NPROMA
USE YOEPHY  , ONLY : LESNICE

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surfbc.h"

IF (LHOOK) CALL DR_HOOK('SURFBC_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PINTER, LLKEYS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)

  CALL SURFBC(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
   & KLON=NPROMA, KTILES=NTILES, KLEVSN=NCSNEC, &
   & PSSDP2=PINTER%PSSDP2, PTVL=PCLIM%PTVL, PCO2TYP=PCLIM%PCO2TYP, &
   & PTVH=PCLIM%PTVH, PSOTY=PCLIM%PSOTY, PSDOR=ZSURF%PSDOR, PCVLC=PCLIM%PCVL, &
   & PCVHC=PCLIM%PCVH, PCURC=PCLIM%PCUR, &
   & PLAILC=ZSURF%GSD%PLAILC, PLAIHC=ZSURF%GSD%PLAIHC, &
   & PLAILI=PSURFL%PLAILI, PLAIHI=PSURFL%PLAIHI, &
   & PLAILCP=ZSURF%GSD%PLAILC, PLAIHCP=ZSURF%GSD%PLAIHC, &
   & PAVGPARC=ZSURF%GSD%ZAVGPARC, &
   & PLSM=PCLIM%PLSM, PCI=PCLIM%PCI, PCIL=ZSURF%PCIL, &
   & PCLAKE=PCLIM%PCLAKE, PHLICE=ZSURF%GSP%PHLICE, &
   & PGEMU=PAUX%PGEMU, PSNM1M=PSURFL%PSNS, PWLM1M=PSURFL%PWL, PRSNM1M=PSURFL%PRSN, &
   & LESNICE=LESNICE, &
   & LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDLICE=LLKEYS%LLLICE, &
   & LDLAKE=LLKEYS%LLLAKE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP, &
   & KTVL=ZSURF%ITVL, KCO2TYP=ZSURF%ICO2TYP, KTVH=ZSURF%ITVH, KSOTY=ZSURF%ISOTY, &
   & PCVL=ZSURF%ZCVL, PCVH=ZSURF%ZCVH, PCUR=ZSURF%ZCUR, PLAIL=PSURFL%ZLAIL, &
   & PLAIH=PSURFL%ZLAIH, PLAILP=ZSURF%ZLAILP, PLAIHP=ZSURF%ZLAIHP, &
   & PAVGPAR=ZSURF%ZAVGPAR, &
   & PWLMX=PSURFL%ZWLMX, PFRTI=PSURFL%ZFRTI, PCSN=PSURFL%ZCSN)
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('SURFBC_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE SURFBC_LAYER_OPENMP

END MODULE SURFBC_LAYER_MOD
