MODULE SURFRAD_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB, JPRD, JPIB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE ECLAND_ATMO_TYPE_MOD,       ONLY : ATMO_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY : AUX_DIAG_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY : FLUX_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE SURFRAD_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

CALL SURFRAD_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)

END SUBROUTINE SURFRAD_LAYER_PARALLEL

SUBROUTINE SURFRAD_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)
USE YOMDPHY         , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI, NLEV
USE YOMDIM1S        , ONLY : NPROMA
USE YOEPHY          , ONLY : LERADS, LESNICE
USE YOERAD          , ONLY : NSW, NLWEMISS
USE YOMSURF_SSDP_MOD, ONLY : NSSDP3D
USE YOMRIP          , ONLY : RSTATI, NSSSSS
USE YOMCST          , ONLY : RSIGMA, RDAY
USE YOMLOG1S        , ONLY : LSEMISS
USE YOERDI1S        , ONLY : REMISS

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
INTEGER(KIND=JPIM) :: IDD, IMM, IYY, IINC, ISEC0, IYMD, IHM, IMON(12), JK, KULOUT
REAL(KIND=JPRD) :: ZJUL
LOGICAL :: LNEMOLIMALB
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surfrad.h"
#include "updcal.intfb.h"
#include "fcttim.h"

IF (LHOOK) CALL DR_HOOK('SURFRAD_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, IDD, IMM, IYY, IINC, ISEC0, IYMD, IHM, IMON, JK, KULOUT, &
!$OMP  & ZJUL, LNEMOLIMALB, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)

  IF (LERADS) THEN
    CALL DATTIM(ZJUL, IYMD, IHM)
    IDD=NDD(IYMD)
    IMM=NMM(IYMD)
    IYY=NCCAA(IYMD)
    IINC=0
    ISEC0=MOD(NSSSSS+NINT(RSTATI,JPIB),NINT(RDAY))
    KULOUT=-1_JPIM
    CALL UPDCAL(IDD, IMM, IYY, IINC, IDD, IMM, IYY, IMON, KULOUT)
    PAUXL%ZWND(KIDIA:KFDIA)=SQRT(STATE%PU(KIDIA:KFDIA)**2 + STATE%PV(KIDIA:KFDIA)**2)
    ZSURF%GSP%ZWS1(KIDIA:KFDIA)=ZSURF%GSP%PWSA(KIDIA:KFDIA,1)
    LNEMOLIMALB=.FALSE.
    ZSURF%GSD%PALBICEF(KIDIA:KFDIA) = -999._JPRB

    CALL SURFRAD &
     &     ( YSURF=YSURF, KDD=IDD, KMM=IMM, KMON=IMON  , KSECO=ISEC0 &
     &     , KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA  , KTILES=NTILES , KCSS=NCSS, KSSDP3D=NSSDP3D, KSW=NSW, KLW=NLWEMISS &
     &     , LDNH=LLKEYS%LLNH, LDLAND=LLKEYS%LLLAND &
     &     , PSSDP3=PINTER%PSSDP3 &
     &     , PALBF=ZSURF%GSD%PALBF, PALBICEF=ZSURF%GSD%PALBICEF, PTVH=PCLIM%PTVH &
     &     , PALCOEFF=ZSURF%GSD%ZALCOEFF, PCUR=PCLIM%PCUR, PCVH=PCLIM%PCVH &
     &     , PASN=ZSURF%GSP%PASN, PMU0=PAUX%PMU0M, PTS=ZSURF%GSP%PTL, PWND=PAUXL%ZWND &
     &     , PWS1=ZSURF%GSP%ZWS1, KSOTY=ZSURF%ISOTY &
     &     , PFRTI=PSURFL%ZFRTI, PHLICE=ZSURF%GSP%PHLICE, PTLICE=ZSURF%GSP%PTLICE &
     &     , PALBD=PSURFL%ZALBD(:,1:NSW), PALBP=PSURFL%ZALBP(:,1:NSW), PALB=PCLIM%PALB &
     &     , PSPECTRALEMISS=PSURFL%ZSPECTRALEMISS(:,1:NLWEMISS), PEMIT=ZSURF%ZEMIS &
     &     , PALBTI=PSURFL%ZALBTI, PCCNL=PAUXL%ZCCNL, PCCNO=PAUXL%ZCCNO &
     &     , LNEMOLIMALB=LNEMOLIMALB &
     &     , LESNICE=LESNICE)
  ELSE
    DO JK=1,NTILES
      PSURFL%ZALBTI(KIDIA:KFDIA,JK)=ZSURF%GSD%PALBF(KIDIA:KFDIA)
    ENDDO
    PCLIM%PALB(KIDIA:KFDIA)=ZSURF%GSD%PALBF(KIDIA:KFDIA)
    ZSURF%ZEMIS(KIDIA:KFDIA)=REMISS
  ENDIF
  IF (LSEMISS) ZSURF%ZEMIS(KIDIA:KFDIA)=REMISS
  PFLUX%PFRSO(KIDIA:KFDIA,NLEV)=ZSURF%PSRSOD(KIDIA:KFDIA)*(1._JPRB-PCLIM%PALB(KIDIA:KFDIA))
  PFLUX%PFRTH(KIDIA:KFDIA,NLEV)=ZSURF%ZEMIS(KIDIA:KFDIA)* &
     &       (ZSURF%PSRTHD(KIDIA:KFDIA)-RSIGMA*ZSURF%GSP%PTL(KIDIA:KFDIA)**4)
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('SURFRAD_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE SURFRAD_LAYER_OPENMP

END MODULE SURFRAD_LAYER_MOD
