MODULE SURFTSTP_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_SURF, ONLY : TSURF

USE ECLAND_ATMO_TYPE_MOD,       ONLY : ATMO_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY : AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_DDH_TYPE_MOD,        ONLY : DDH_SURF_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY : FLUX_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE SURFTSTP_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)

TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS

CALL SURFTSTP_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)

END SUBROUTINE SURFTSTP_LAYER_PARALLEL

SUBROUTINE SURFTSTP_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI, NLEV
USE YOMCDH1S, ONLY : NLEVI, NDHVTSS, NDHFTSS, NDHVTTS, NDHFTTS, NDHVTIS, NDHFTIS, &
     &               NDHVSSS, NDHFSSS, NDHVIIS, NDHFIIS, NDHVWLS, NDHFWLS, &
     &               NDHVBIOS, NDHFBIOS, NDHVVEGS, NDHFVEGS
USE YOMCT01S, ONLY : NSTART
USE YOMDIM1S, ONLY : NPROMA
USE YOMDYN1S, ONLY : NSTEP, TDT
USE YOEPHY  , ONLY : LESICE, LESURF, NCWS

TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
LOGICAL :: LNEMOICETHK
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surftstp.h"

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, LNEMOICETHK, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)

  IF ( LESURF ) THEN
    PAUXL%ZPAPSRF(KIDIA:KFDIA)=STATE%PAPRS(KIDIA:KFDIA,NLEV)
    PFLUX%ZFRTH(KIDIA:KFDIA)=PFLUX%PFRTH(KIDIA:KFDIA,NLEV)
    PSURFL%ZTHKICE(KIDIA:KFDIA)=1.5_JPRB
    LNEMOICETHK=.FALSE.

    CALL SURFTSTP(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
     & KLON=NPROMA, KLEVS=NCSS, KCWS=NCWS, KTILES=NTILES, &
     & KLEVSN=NCSNEC, KLEVO=NCOM, KLEVI=NLEVI, KSTART=NSTART, KSTEP=NSTEP, &
     & KDHVTSS=NDHVTSS, KDHFTSS=NDHFTSS, &
     & KDHVTTS=NDHVTTS, KDHFTTS=NDHFTTS, &
     & KDHVTIS=NDHVTIS, KDHFTIS=NDHFTIS, &
     & KDHVSSS=NDHVSSS, KDHFSSS=NDHFSSS, &
     & KDHVIIS=NDHVIIS, KDHFIIS=NDHFIIS, &
     & KDHVWLS=NDHVWLS, KDHFWLS=NDHFWLS, &
     & KDHVBIOS=NDHVBIOS, KDHFBIOS=NDHFBIOS, &
     & KDHVVEGS=NDHVVEGS, KDHFVEGS=NDHFVEGS, &
     & KVTYPES=NVHILO, &
     & KTVL=ZSURF%ITVL, KTVH=ZSURF%ITVH, KVEG=ZSURF%IVEG, KSOTY=ZSURF%ISOTY, &
     & PSSDP2=PINTER%PSSDP2, PSSDP3=PINTER%PSSDP3, &
     & PTSPHY=TDT, PSDOR=ZSURF%PSDOR, PFRTI=PSURFL%ZFRTI, &
     & PSST=ZSURF%GSP%PSST, PUSTRTI=ZSURF%PUSTRTI, PVSTRTI=ZSURF%PVSTRTI, &
     & PAHFSTI=ZSURF%PAHFSTI, PEVAPTI=ZSURF%PEVAPTI, &
     & PSSRFLTI=PSURFL%ZFRSOTI, PSLRFLTI=PSURFL%PSLRFLTI, &
     & PLAT=PAUX%GELAT, PANFMVT=PSURFL%PANFMVT, PANDAYVT=PSURFL%PANDAYVT, PMU0=PAUX%PMU0M, &
     & PCVT=PSURFL%ZCVT, PLAIVT=PSURFL%ZLAIVT, &
     & PLAIL=PSURFL%ZLAIL, PLAIH=PSURFL%ZLAIH, &
     & PCIL=ZSURF%PCIL, &
     & PLAILC=ZSURF%GSD%PLAILC, PLAIHC=ZSURF%GSD%PLAIHC, &
     & LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDLICE=LLKEYS%LLLICE, &
     & LDSI=LESICE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP, &
     & PSNM1M=PSURFL%PSNS, PTSNM1M=ZSURF%GSP%PTSN, PASNM1M=ZSURF%GSP%PASN, &
     & PRSNM1M=PSURFL%PRSN, PWSNM1M=PSURFL%PWSN, &
     & PAPRS=PAUXL%ZPAPSRF, PTSKM1M=ZSURF%GSP%PTL, &
     & PTSAM1M=ZSURF%GSP%PTSA, PTIAM1M=ZSURF%GSP%PTIA, &
     & PWLM1M=PSURFL%PWL, PWSAM1M=ZSURF%GSP%PWSA, &
     & PTLICEM1M=ZSURF%GSP%PTLICE, PTLMNWM1M=ZSURF%GSP%PTLMNW, &
     & PTLWMLM1M=ZSURF%GSP%PTLWML, PTLBOTM1M=ZSURF%GSP%PTLBOT, &
     & PTLSFM1M=ZSURF%GSP%PTLSF, &
     & PHLICEM1M=ZSURF%GSP%PHLICE, PHLMLM1M=ZSURF%GSP%PHLML, &
     & PGEMU=PAUX%PGEMU, &
     & PLDEPTH=PCLIM%PLDEPTH, LDLAKE=LLKEYS%LLLAKE, PCLAKE=PCLIM%PCLAKE, &
     & PRSFC=PFLUX%PFPLCL, PRSFL=PFLUX%PFPLSL, &
     & PSLRFL=PFLUX%ZFRTH, PSSFC=PFLUX%PFPLCN, PSSFL=PFLUX%PFPLSN, &
     & PCVL=ZSURF%ZCVL, PCVH=ZSURF%ZCVH, PCUR=PCLIM%PCUR, &
     & PWLMX=PSURFL%ZWLMX, PEVAPSNW=PSURFL%ZEVAPSNW, &
     & PUSRF=STATE%PU, PVSRF=STATE%PV, PTSRF=STATE%PT, &
     & PZO=PCLIM%PZO, PHO=ZSURF%GSD%PHO, &
     & PHO_INV=ZSURF%GSD%PHO_INV, PDO=ZSURF%GSD%PDO, &
     & POCDEPTH=ZSURF%GSD%POCDEPTH, &
     & PUO0=ZSURF%GSP%PUO0, PVO0=ZSURF%GSP%PVO0, &
     & PUOC=ZSURF%GSP%PUOC, PVOC=ZSURF%GSP%PVOC, &
     & PTO0=ZSURF%GSP%PTO0, &
     & PSO0=ZSURF%GSP%PSO0, PADVT=ZSURF%GSD%PADVT, &
     & PADVS=ZSURF%GSD%PADVS, PTRI0=ZSURF%GSD%PTRI0, &
     & PTRI1=ZSURF%GSD%PTRI1, &
     & PSWDK_SAVE=ZSURF%GSD%PSWDK_SAVE, PUSTRC=ZSURF%PUSTRC, &
     & PVSTRC=ZSURF%PVSTRC, &
     & PUSTOKES=ZSURF%PUSTOKES, PVSTOKES=ZSURF%PVSTOKES, &
     & PTAUOCX=ZSURF%GSD%PTAUOCX, PTAUOCY=ZSURF%GSD%PTAUOCY, &
     & PPHIOC=ZSURF%PPHIOC, &
     & PWSEMEAN=ZSURF%PWSEMEAN, PWSFMEAN=ZSURF%PWSFMEAN, &
     & LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL%ZTHKICE, &
     & PTSDFL=PFLUX%PFTG12, PROFD=PFLUX%PFWROD, PROFS=PFLUX%PFWRO1, &
     & PWFSD=PFLUX%PFWG12, PMELT=PFLUX%PFWMLT, PFWEV=PFLUX%PFWEV, PENES=PFLUX%ZENES, &
     & PDIFM=ZSURF%PDIFM, PDIFT=ZSURF%PDIFT, &
     & PDIFS=ZSURF%PDIFS, POTKE=ZSURF%GSD%POTKE, &
     & PRESPBSTR=ZSURF%PRESPBSTR, PRESPBSTR2=ZSURF%PRESPBSTR2, PBIOMASS_LAST=ZSURF%PBIOMASS_LAST, &
     & PBIOMASSTR_LAST=ZSURF%PBIOMASSTR_LAST, PBIOMASSTR2_LAST=ZSURF%PBIOMASSTR2_LAST, &
     & PBLOSSVT=ZSURF%PBLOSSVT, PBGAINVT=ZSURF%PBGAINVT, &
     & PLAI=ZSURF%PLAI, PBIOM=ZSURF%PBIOM, PBLOSS=ZSURF%PBLOSS, PBGAIN=ZSURF%PBGAIN, &
     & PBIOMSTR=ZSURF%PBIOMSTR, PBIOMSTR2=ZSURF%PBIOMSTR2, &
     & PSNE1=ZSURF%PSNSE1, PTSNE1=ZSURF%PTSNE1, PASNE1=ZSURF%PASNE1, &
     & PRSNE1=ZSURF%PRSNE1, PWSNE1=ZSURF%PWSNE1, PTSAE1=ZSURF%PTSAE1, PTIAE1=ZSURF%PTIAE1, &
     & PWLE1=ZSURF%PWLE1, PWSAE1=ZSURF%PWSAE1, &
     & PTLICEE1=ZSURF%PTLICEE1, PTLMNWE1=ZSURF%PTLMNWE1, PTLWMLE1=ZSURF%PTLWMLE1, &
     & PTLBOTE1=ZSURF%PTLBOTE1, PTLSFE1=ZSURF%PTLSFE1, &
     & PHLICEE1=ZSURF%PHLICEE1, PHLMLE1=ZSURF%PHLMLE1, &
     & PUOE1=ZSURF%PUOE1, PVOE1=ZSURF%PVOE1, PTOE1=ZSURF%PTOE1, PSOE1=ZSURF%PSOE1, &
     & PLAIE1=ZSURF%PLAIE1, PBSTRE1=ZSURF%PBSTRE1, PBSTR2E1=ZSURF%PBSTR2E1, &
     & PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, PDHTIS=PDDHS%PDHTIS, &
     & PDHSSS=PDDHS%PDHSSS, PDHIIS=PDDHS%PDHIIS, PDHWLS=PDDHS%PDHWLS, &
     & PDHBIOS=PDDHS%PDHBIOS, PDHVEGS=PDDHS%PDHVEGS)
  ELSE
    PFLUX%PFTG12(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWROD(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWRO1(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWMLT(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWG12(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWEV(KIDIA:KFDIA)=0._JPRB
  ENDIF
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE SURFTSTP_LAYER_OPENMP

SUBROUTINE SURFTSTP_LAYER(YSURF, KIDIA, KFDIA, KLON, KLEVS, KTILES, KLEV, KSTART, KSTEP, &
 & KLEVSN, KLEVI, KLEVO, KDHVTSS, KDHFTSS, KDHVTTS, KDHFTTS, KDHVTIS, KDHFTIS, &
 & KDHVSSS, KDHFSSS, KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS, KDHVBIOS, KDHFBIOS, &
 & KDHVVEGS, KDHFVEGS, KVTYPES, KCWS, LESICE, PTSPHY, PAUX, PAUXL, PCLIM, &
 & PFLUX, PINTER, STATE, LLKEYS, PSURF, PSURFL, PDDHS)

TYPE(TSURF)                   , INTENT(INOUT) :: YSURF
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KIDIA, KFDIA, KLON, KLEVS, KTILES
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KLEV, KSTART, KSTEP, KLEVSN, KLEVI, KLEVO
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVTSS, KDHFTSS, KDHVTTS, KDHFTTS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVTIS, KDHFTIS, KDHVSSS, KDHFSSS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVBIOS, KDHFBIOS, KDHVVEGS, KDHFVEGS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KVTYPES, KCWS
LOGICAL                       , INTENT(IN)    :: LESICE
REAL(KIND=JPRB)               , INTENT(IN)    :: PTSPHY
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS

LOGICAL :: LNEMOICETHK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surftstp.h"

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER',0,ZHOOK_HANDLE)

PAUXL%ZPAPSRF(KIDIA:KFDIA)=STATE%PAPRS(KIDIA:KFDIA,KLEV)
PFLUX%ZFRTH(KIDIA:KFDIA)=PFLUX%PFRTH(KIDIA:KFDIA,KLEV)
PSURFL%ZTHKICE(KIDIA:KFDIA)=1.5_JPRB
LNEMOICETHK=.FALSE.

CALL SURFTSTP(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
 & KLON=KLON, KLEVS=KLEVS, KCWS=KCWS, KTILES=KTILES, &
 & KLEVSN=KLEVSN, KLEVO=KLEVO, KLEVI=KLEVI, KSTART=KSTART, KSTEP=KSTEP, &
 & KDHVTSS=KDHVTSS, KDHFTSS=KDHFTSS, &
 & KDHVTTS=KDHVTTS, KDHFTTS=KDHFTTS, &
 & KDHVTIS=KDHVTIS, KDHFTIS=KDHFTIS, &
 & KDHVSSS=KDHVSSS, KDHFSSS=KDHFSSS, &
 & KDHVIIS=KDHVIIS, KDHFIIS=KDHFIIS, &
 & KDHVWLS=KDHVWLS, KDHFWLS=KDHFWLS, &
 & KDHVBIOS=KDHVBIOS, KDHFBIOS=KDHFBIOS, &
 & KDHVVEGS=KDHVVEGS, KDHFVEGS=KDHFVEGS, &
 & KVTYPES=KVTYPES, &
 & KTVL=PSURF%ITVL, KTVH=PSURF%ITVH, KVEG=PSURF%IVEG, KSOTY=PSURF%ISOTY, &
 & PSSDP2=PINTER%PSSDP2, PSSDP3=PINTER%PSSDP3, &
 & PTSPHY=PTSPHY, PSDOR=PSURF%PSDOR, PFRTI=PSURFL%ZFRTI, &
 & PSST=PSURF%GSP%PSST, PUSTRTI=PSURF%PUSTRTI, PVSTRTI=PSURF%PVSTRTI, &
 & PAHFSTI=PSURF%PAHFSTI, PEVAPTI=PSURF%PEVAPTI, &
 & PSSRFLTI=PSURFL%ZFRSOTI, PSLRFLTI=PSURFL%PSLRFLTI, &
 & PLAT=PAUX%GELAT, PANFMVT=PSURFL%PANFMVT, PANDAYVT=PSURFL%PANDAYVT, PMU0=PAUX%PMU0M, &
 & PCVT=PSURFL%ZCVT, PLAIVT=PSURFL%ZLAIVT, &
 & PLAIL=PSURFL%ZLAIL, PLAIH=PSURFL%ZLAIH, &
 & PCIL=PSURF%PCIL, &
 & PLAILC=PSURF%GSD%PLAILC, PLAIHC=PSURF%GSD%PLAIHC, &
 & LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDLICE=LLKEYS%LLLICE, &
 & LDSI=LESICE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP, &
 & PSNM1M=PSURFL%PSNS, PTSNM1M=PSURF%GSP%PTSN, PASNM1M=PSURF%GSP%PASN, &
 & PRSNM1M=PSURFL%PRSN, PWSNM1M=PSURFL%PWSN, &
 & PAPRS=PAUXL%ZPAPSRF, PTSKM1M=PSURF%GSP%PTL, &
 & PTSAM1M=PSURF%GSP%PTSA, PTIAM1M=PSURF%GSP%PTIA, &
 & PWLM1M=PSURFL%PWL, PWSAM1M=PSURF%GSP%PWSA, &
 & PTLICEM1M=PSURF%GSP%PTLICE, PTLMNWM1M=PSURF%GSP%PTLMNW, &
 & PTLWMLM1M=PSURF%GSP%PTLWML, PTLBOTM1M=PSURF%GSP%PTLBOT, &
 & PTLSFM1M=PSURF%GSP%PTLSF, &
 & PHLICEM1M=PSURF%GSP%PHLICE, PHLMLM1M=PSURF%GSP%PHLML, &
 & PGEMU=PAUX%PGEMU, &
 & PLDEPTH=PCLIM%PLDEPTH, LDLAKE=LLKEYS%LLLAKE, PCLAKE=PCLIM%PCLAKE, &
 & PRSFC=PFLUX%PFPLCL, PRSFL=PFLUX%PFPLSL, &
 & PSLRFL=PFLUX%ZFRTH, PSSFC=PFLUX%PFPLCN, PSSFL=PFLUX%PFPLSN, &
 & PCVL=PSURF%ZCVL, PCVH=PSURF%ZCVH, PCUR=PCLIM%PCUR, &
 & PWLMX=PSURFL%ZWLMX, PEVAPSNW=PSURFL%ZEVAPSNW, &
 & PUSRF=STATE%PU, PVSRF=STATE%PV, PTSRF=STATE%PT, &
 & PZO=PCLIM%PZO, PHO=PSURF%GSD%PHO, &
 & PHO_INV=PSURF%GSD%PHO_INV, PDO=PSURF%GSD%PDO, &
 & POCDEPTH=PSURF%GSD%POCDEPTH, &
 & PUO0=PSURF%GSP%PUO0, PVO0=PSURF%GSP%PVO0, &
 & PUOC=PSURF%GSP%PUOC, PVOC=PSURF%GSP%PVOC, &
 & PTO0=PSURF%GSP%PTO0, &
 & PSO0=PSURF%GSP%PSO0, PADVT=PSURF%GSD%PADVT, &
 & PADVS=PSURF%GSD%PADVS, PTRI0=PSURF%GSD%PTRI0, &
 & PTRI1=PSURF%GSD%PTRI1, &
 & PSWDK_SAVE=PSURF%GSD%PSWDK_SAVE, PUSTRC=PSURF%PUSTRC, &
 & PVSTRC=PSURF%PVSTRC, &
 & PUSTOKES=PSURF%PUSTOKES, PVSTOKES=PSURF%PVSTOKES, &
 & PTAUOCX=PSURF%GSD%PTAUOCX, PTAUOCY=PSURF%GSD%PTAUOCY, &
 & PPHIOC=PSURF%PPHIOC, &
 & PWSEMEAN=PSURF%PWSEMEAN, PWSFMEAN=PSURF%PWSFMEAN, &
 & LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL%ZTHKICE, &
 & PTSDFL=PFLUX%PFTG12, PROFD=PFLUX%PFWROD, PROFS=PFLUX%PFWRO1, &
 & PWFSD=PFLUX%PFWG12, PMELT=PFLUX%PFWMLT, PFWEV=PFLUX%PFWEV, PENES=PFLUX%ZENES, &
 & PDIFM=PSURF%PDIFM, PDIFT=PSURF%PDIFT, &
 & PDIFS=PSURF%PDIFS, POTKE=PSURF%GSD%POTKE, &
 & PRESPBSTR=PSURF%PRESPBSTR, PRESPBSTR2=PSURF%PRESPBSTR2, PBIOMASS_LAST=PSURF%PBIOMASS_LAST, &
 & PBIOMASSTR_LAST=PSURF%PBIOMASSTR_LAST, PBIOMASSTR2_LAST=PSURF%PBIOMASSTR2_LAST, &
 & PBLOSSVT=PSURF%PBLOSSVT, PBGAINVT=PSURF%PBGAINVT, &
 & PLAI=PSURF%PLAI, PBIOM=PSURF%PBIOM, PBLOSS=PSURF%PBLOSS, PBGAIN=PSURF%PBGAIN, &
 & PBIOMSTR=PSURF%PBIOMSTR, PBIOMSTR2=PSURF%PBIOMSTR2, &
 & PSNE1=PSURF%PSNSE1, PTSNE1=PSURF%PTSNE1, PASNE1=PSURF%PASNE1, &
 & PRSNE1=PSURF%PRSNE1, PWSNE1=PSURF%PWSNE1, PTSAE1=PSURF%PTSAE1, PTIAE1=PSURF%PTIAE1, &
 & PWLE1=PSURF%PWLE1, PWSAE1=PSURF%PWSAE1, &
 & PTLICEE1=PSURF%PTLICEE1, PTLMNWE1=PSURF%PTLMNWE1, PTLWMLE1=PSURF%PTLWMLE1, &
 & PTLBOTE1=PSURF%PTLBOTE1, PTLSFE1=PSURF%PTLSFE1, &
 & PHLICEE1=PSURF%PHLICEE1, PHLMLE1=PSURF%PHLMLE1, &
 & PUOE1=PSURF%PUOE1, PVOE1=PSURF%PVOE1, PTOE1=PSURF%PTOE1, PSOE1=PSURF%PSOE1, &
 & PLAIE1=PSURF%PLAIE1, PBSTRE1=PSURF%PBSTRE1, PBSTR2E1=PSURF%PBSTR2E1, &
 & PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, PDHTIS=PDDHS%PDHTIS, &
 & PDHSSS=PDDHS%PDHSSS, PDHIIS=PDDHS%PDHIIS, PDHWLS=PDDHS%PDHWLS, &
 & PDHBIOS=PDDHS%PDHBIOS, PDHVEGS=PDDHS%PDHVEGS)

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER',1,ZHOOK_HANDLE)

END SUBROUTINE SURFTSTP_LAYER

END MODULE SURFTSTP_LAYER_MOD
