MODULE VDFMAIN1S_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE ECLAND_ATMO_TYPE_MOD,       ONLY : ATMO_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY : AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_DDH_TYPE_MOD,        ONLY : DDH_SURF_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY : FLUX_TYPE
USE ECLAND_GEMS_TYPE_MOD,       ONLY : GEMS_LOCAL_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE VDFMAIN1S_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(AUX_DIAG_TYPE)             , INTENT(INOUT) :: PDIAG
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(GEMS_LOCAL_TYPE)           , INTENT(INOUT) :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)             , INTENT(INOUT) :: PDDHS

CALL VDFMAIN1S_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)

END SUBROUTINE VDFMAIN1S_LAYER_PARALLEL

SUBROUTINE VDFMAIN1S_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, NVHILO, NPOI, NLEV
USE YOMCDH1S, ONLY : NLEVI, NDHVTLS, NDHFTLS, NDHVTSS, NDHFTSS, NDHVTTS, NDHFTTS, &
     &               NDHVTIS, NDHFTIS, NDHVCO2S, NDHFCO2S, NDHVBVOCS, NDHVVEGS, NDHFVEGS
USE YOMCT01S, ONLY : NSTART
USE YOMDIM1S, ONLY : NPROMA
USE YOMDYN1S, ONLY : NSTEP, TDT
USE YOEPHY  , ONLY : LESNICE, LEVDIF, LEWARMSTART

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(AUX_DIAG_TYPE)             , INTENT(INOUT) :: PDIAG
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(GEMS_LOCAL_TYPE)           , INTENT(INOUT) :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)             , INTENT(INOUT) :: PDDHS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA, JTILE
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surfws.h"
#include "vdfmain1s.intfb.h"

IF (LHOOK) CALL DR_HOOK('VDFMAIN1S_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, JTILE, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL GEMSL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)

!*      1.3   GLOBAL AUXILLIARY VARIABLES
  ZSURF%ZCHAR(KIDIA:KFDIA)  =0.018_JPRB
  ZSURF%ZCHARHQ(KIDIA:KFDIA)=0.006_JPRB

!*      1.3a   GLOBAL OCEAN TEMPORALY SET TO ZERO (to check with PJ)
  ZSURF%PUSTOKES(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PVSTOKES(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%GSD%PTAUOCX(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%GSD%PTAUOCY(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PPHIOC(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PWSEMEAN(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PWSFMEAN(KIDIA:KFDIA)=0.0_JPRB

!*       1.4  SET SURFACE TENDENCIES TO ZERO
  ZSURF%PTSAE1(KIDIA:KFDIA,1:NCSS)=0.0_JPRB
  ZSURF%PWSAE1(KIDIA:KFDIA,1:NCSS)=0.0_JPRB
  ZSURF%PTIAE1(KIDIA:KFDIA,1:NCSS)=0.0_JPRB
  ZSURF%PTLE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PWLE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PSNSE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PTSNE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PRSNE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PWSNE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PASNE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%ZUCURR(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%ZVCURR(KIDIA:KFDIA)=0.0_JPRB

!* FLAKE
  ZSURF%PTLICEE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLMNWE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLWMLE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLBOTE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLSFE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PHLICEE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PHLMLE1(KIDIA:KFDIA)=0.0_JPRB

  ZSURF%PUOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%PVOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%PTOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%PSOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%GSP%PUOC(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB  !KPP
  ZSURF%GSP%PVOC(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB  !KPP
  ZSURF%PUSTRC(KIDIA:KFDIA)=0.0_JPRB          !KPP
  ZSURF%PVSTRC(KIDIA:KFDIA)=0.0_JPRB          !KPP

!* CTESSEL
  ZSURF%PLAIE1(KIDIA:KFDIA,1:NVHILO)=0.0_JPRB
  ZSURF%PBSTRE1(KIDIA:KFDIA,1:NVHILO)=0.0_JPRB
  ZSURF%PBSTR2E1(KIDIA:KFDIA,1:NVHILO)=0.0_JPRB

  IF ( (NSTEP==NSTART) .AND. (LEWARMSTART) )  THEN
    CALL SURFWS(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES &
         &     ,PSDOR=ZSURF%PSDOR, LDSICE=LLKEYS%LLSICE &
         &     ,PLSM=PCLIM%PLSM, PCIL=ZSURF%PCIL, PFRTI=PSURFL%ZFRTI, PMU0=PAUX%PMU0M &
         &     ,PTSAM1M=ZSURF%GSP%PTSA, PTSKIN=ZSURF%GSP%PTL, PALBSN=ZSURF%GSP%PASN &
         &     ,PTSNM1M=ZSURF%GSP%PTSN, PSNM1M=PSURFL%PSNS, PRSNM1M=PSURFL%PRSN, PWSNM1M=PSURFL%PWSN)
  ENDIF

  PSURFL%ZEXDIAG(KIDIA:KFDIA,11)=PAUX%GELAT(KIDIA:KFDIA) ! Latitude
  PSURFL%ZEXDIAG(KIDIA:KFDIA,12)=PAUX%GELAM(KIDIA:KFDIA) ! Longitude

  IF ( LEVDIF ) THEN
    CALL VDFMAIN1S ( &
     & KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA, KLEV=NLEV, KLEVS=NCSS, &
     & KSTEP=NSTEP, KTILES=NTILES, KVTYPES=NVHILO, KDIAG=12_JPIM, &
     & KTRAC=NTRAC, KLEVSN=NCSNEC, KLEVI=NLEVI, LDLAND=LLKEYS%LLLAND, &
     & KDHVTLS=NDHVTLS, KDHFTLS=NDHFTLS, KDHVTSS=NDHVTSS, KDHFTSS=NDHFTSS, &
     & KDHVTTS=NDHVTTS, KDHFTTS=NDHFTTS, KDHVTIS=NDHVTIS, KDHFTIS=NDHFTIS, &
     & KDHVCO2S=NDHVCO2S, KDHFCO2S=NDHFCO2S, KDHVBVOCS=NDHVBVOCS, KDHVVEGS=NDHVVEGS, KDHFVEGS=NDHFVEGS, &
     & LESNICE=LESNICE, &
     & PMU0=PAUX%PMU0M, &
     & PTSPHY=TDT, &
     & KTVL=ZSURF%ITVL, KCO2TYP=ZSURF%ICO2TYP, KTVH=ZSURF%ITVH, PCVL=ZSURF%ZCVL, PCVH=ZSURF%ZCVH, &
     & PCUR=PCLIM%PCUR, PFWET=ZSURF%PFWET, PLAT=PAUX%GELAT, PLAIL=PSURFL%ZLAIL, PLAIH=PSURFL%ZLAIH, &
     & PLAILP=ZSURF%ZLAILP, PLAIHP=ZSURF%ZLAIHP, PAVGPAR=ZSURF%ZAVGPAR, PISOP_EP=ZSURF%PISOP_EP, &
     & PCIL=ZSURF%PCIL, &
     & PSNM1M=PSURFL%PSNS, PRSNM1M=PSURFL%PRSN, &
     & PUM1=STATE%PU, PVM1=STATE%PV, PTM1=STATE%PT, &
     & PQM1=STATE%PQ, PCM1=GEMSL%PC, &
     & PAPHM1=STATE%PAPRS, PGEOM1=STATE%PGEOM1, &
     & PTSKM1M=ZSURF%GSP%PTL ,PTSAM1M=ZSURF%GSP%PTSA,PWSAM1M=ZSURF%GSP%PWSA, &
     & PSSRFL=PFLUX%PFRSO(:,NLEV),PSLRFL=PFLUX%PFRTH(:,NLEV),PEMIS=ZSURF%ZEMIS, &
     & PTSN=ZSURF%GSP%PTSN, PTICE=ZSURF%GSP%PTIA, &
     & PHLICE=ZSURF%GSP%PHLICE, PTLICE=ZSURF%GSP%PTLICE, PTLWML=ZSURF%GSP%PTLWML, &
     & PSST=ZSURF%GSP%PSST, KSOTY=ZSURF%ISOTY, PFRTI=PSURFL%ZFRTI, PALBTI=PSURFL%ZALBTI, PWLMX=PSURFL%ZWLMX, &
     & PCHAR=ZSURF%ZCHAR, PCHARHQ=ZSURF%ZCHARHQ, PUCURR=ZSURF%ZUCURR, PVCURR=ZSURF%ZVCURR, &
     & PTSKRAD=ZSURF%GSP%PTL, &
     & PCFLX=GEMSL%PCFLX, &
     & PSSDP2=PINTER%PSSDP2, PSSDP3=PINTER%PSSDP3, &
     & PZ0M=GEMSL%PZ0M, PZ0H=GEMSL%PZ0H, &
     & PVDIS=PDIAG%PVDIS, PAHFLEV=PFLUX%PFTLHEV, &
     & PAHFLSB=PFLUX%PFTLHSB, &
     & PFWSB=PFLUX%PFWSB, &
     & PU10M=ZSURF%GSD%PU10M, PV10M=ZSURF%GSD%PV10M, &
     & PT2M=ZSURF%GSD%PT2M, PD2M=ZSURF%GSD%PD2M, &
     & PQ2M=ZSURF%GSD%PQ2M, PZINV=PDIAG%ZINV, &
     & PSSRFLTI=PSURFL%ZFRSOTI, PEVAPSNW=PSURFL%ZEVAPSNW, &
     & PEXDIAG=PSURFL%ZEXDIAG, PGUST=PDIAG%PGUST, PZIDLWV=PSURFL%PZIDLWV, &
     & PTE=ZSURF%ZTE, PQE=ZSURF%ZQE, PVOM=ZSURF%ZVOM, &
     & PVOL=ZSURF%ZVOL, PTENC=ZSURF%ZTENC, PTSKE1=ZSURF%PTLE1, &
     & PUSTRTI=ZSURF%PUSTRTI, PVSTRTI=ZSURF%PVSTRTI, PAHFSTI=ZSURF%PAHFSTI, &
     & PEVAPTI=ZSURF%PEVAPTI, PTSKTI=ZSURF%PTSKTI, PSLRFLTI=PSURFL%PSLRFLTI, &
     & PANDAYVT=PSURFL%PANDAYVT, PANFMVT=PSURFL%PANFMVT, &
     & PEVAPTIU=ZSURF%GSD%PEVAPTIU, PDIFTS=PFLUX%PDIFTS, PDIFTQ=PFLUX%PDIFTQ, &
     & PSTRTU=PFLUX%PSTRTU, PSTRTV=PFLUX%PSTRTV, PKH=PSURFL%ZKH, &
     & PAN=ZSURF%PAN, PAG=ZSURF%PAG, PRD=ZSURF%PRD, PRSOIL_STR=ZSURF%PRSOIL_STR, &
     & PRECO=ZSURF%PRECO, PCO2FLUX=ZSURF%PCO2FLUX, PCH4FLUX=ZSURF%PCH4FLUX, &
     & PBVOCFLUX=GEMSL%PBVOCFLUX, &
     & PDHTLS=PDDHS%PDHTLS, PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, &
     & PDHTIS=PDDHS%PDHTIS, PDHCO2S=PDDHS%PDHCO2S, PDHBVOCS=PDDHS%PDHBVOCS, PDHVEGS=PDDHS%PDHVEGS)
  ELSE
    PDIAG%PVDIS(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFTLHEV(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFTLHSB(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWSB(KIDIA:KFDIA)=0._JPRB
    PSURFL%ZEVAPSNW(KIDIA:KFDIA)=0._JPRB
    PFLUX%PDIFTQ(KIDIA:KFDIA,1:NCSS)=0._JPRB
    PFLUX%PDIFTS(KIDIA:KFDIA,1:NCSS)=0._JPRB
    PFLUX%PSTRTU(KIDIA:KFDIA,1:NCSS)=0._JPRB
    PFLUX%PSTRTV(KIDIA:KFDIA,1:NCSS)=0._JPRB
    DO JTILE=1,NTILES
      PSURFL%ZFRSOTI(KIDIA:KFDIA,JTILE)=PFLUX%PFRSO(KIDIA:KFDIA,NLEV)
      ZSURF%PUSTRTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PVSTRTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PAHFSTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PEVAPTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PTSKTI(KIDIA:KFDIA,JTILE)=ZSURF%GSP%PTL(KIDIA:KFDIA)
    ENDDO
  ENDIF
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('VDFMAIN1S_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE VDFMAIN1S_LAYER_OPENMP

END MODULE VDFMAIN1S_LAYER_MOD
